// Fragenpool AP1 – Ergänzungen aus dem Abgleich mit dem Prüfungskatalog und den Themen früherer Prüfungen
[
  // ---------------------------------------------------------------- Software
  { id: "S2-22", modul: "S2", typ: "mc", niveau: 1, abschnitt: "Programmierparadigmen", frage: "Was kennzeichnet die **objektorientierte** im Unterschied zur **prozeduralen** Programmierung?",
    optionen: ["Daten und die zugehörigen Methoden werden in Objekten gekapselt", "Das Programm besteht aus einer einzigen langen Befehlsfolge ohne Unterprogramme", "Es werden ausschließlich Schleifen und keine Verzweigungen verwendet", "Der Quelltext wird nicht übersetzt, sondern direkt von der Hardware gelesen"], richtig: 0,
    erklaerung: "Prozedural: Prozeduren und Funktionen arbeiten auf getrennten Daten. Objektorientiert: Attribute und Methoden gehören zusammen (Klasse → Objekt)." },
  { id: "S2-23", modul: "S2", typ: "mc", niveau: 2, abschnitt: "Fehlerbehandlung", frage: "Was versteht man in einem Programm unter einer **Exception** (Ausnahme)?",
    optionen: ["Ein Ereignis zur Laufzeit, das den normalen Ablauf unterbricht und gezielt behandelt werden kann (try/catch)", "Einen Syntaxfehler, den der Compiler vor dem Start meldet", "Eine Variable, die nur einmal beschrieben werden darf", "Eine Schleife, die nie beendet wird"], richtig: 0,
    erklaerung: "Beispiele: Division durch 0, Datei nicht gefunden, Index außerhalb des Arrays. Mit try/catch reagiert das Programm kontrolliert, statt abzustürzen." },
  { id: "S3-25", modul: "S3", typ: "mc", niveau: 2, abschnitt: "Insertion Sort", frage: "Wie arbeitet **Insertion Sort** (Sortieren durch Einfügen)?",
    optionen: ["Jedes Element wird an der passenden Stelle in den bereits sortierten Teil eingefügt", "Benachbarte Elemente werden vertauscht, bis nichts mehr zu tauschen ist", "Das kleinste Element des unsortierten Teils wird ans Ende des sortierten Teils getauscht", "Die Liste wird fortlaufend halbiert und die Hälften getrennt sortiert"], richtig: 0,
    erklaerung: "Option 2 beschreibt Bubble Sort, Option 3 Selection Sort. Insertion Sort verhält sich wie beim Sortieren von Spielkarten auf der Hand." },
  { id: "S3-26", modul: "S3", typ: "mc", niveau: 2, abschnitt: "Insertion Sort", frage: "Die Liste `[4, 3, 1, 2]` wird mit **Insertion Sort** aufsteigend sortiert. Wie sieht sie aus, nachdem das **dritte** Element (die 1) eingefügt wurde?",
    optionen: ["[1, 3, 4, 2]", "[1, 4, 3, 2]", "[3, 4, 1, 2]", "[1, 2, 3, 4]"], richtig: 0,
    erklaerung: "Start [4] → 3 einfügen: [3, 4] → 1 einfügen: **[1, 3, 4]**, die 2 steht noch unsortiert dahinter." },
  { id: "S3-27", modul: "S3", typ: "mc", niveau: 1, abschnitt: "Selection Sort", frage: "Was passiert bei **Selection Sort** in jedem Durchlauf?",
    optionen: ["Das kleinste Element des unsortierten Teils wird gesucht und an dessen Anfang getauscht", "Jedes Element wird mit seinem Nachbarn verglichen und ggf. vertauscht", "Das mittlere Element wird mit dem gesuchten Wert verglichen", "Die Liste wird rückwärts durchlaufen und gespiegelt"], richtig: 0,
    erklaerung: "Pro Durchlauf wird ein Element endgültig platziert. Auch hier gilt: zwei verschachtelte Schleifen, Laufzeit O(n²)." },
  { id: "S3-28", modul: "S3", typ: "mc", niveau: 1, abschnitt: "Darstellungsformen", frage: "Warum wird in Prüfungsaufgaben oft **Pseudocode** statt Quelltext einer bestimmten Programmiersprache verwendet?",
    optionen: ["Er ist unabhängig von der Sprache lesbar, Syntaxfehler sind unwichtig, die Logik steht im Mittelpunkt", "Er lässt sich direkt kompilieren und ausführen", "Er ist schneller als jede Programmiersprache", "Er wird von der Hardware ohne Übersetzung verstanden"], richtig: 0,
    erklaerung: "Pseudocode muss nicht kompilierbar sein; die Kontrollstrukturen (Verzweigung, Schleife) müssen aber erkennbar sein." },
  { id: "S7-26", modul: "S7", typ: "mc", niveau: 1, abschnitt: "Datentypen", frage: "Eine Datenbanktabelle soll zu jedem Kunden das **eingescannte Vertrags-PDF** speichern. Welcher Datentyp passt?",
    optionen: ["BLOB (Binary Large Object)", "BOOLEAN", "DATE", "CHAR(1)"], richtig: 0,
    erklaerung: "BLOB speichert Binärdaten wie Bilder, PDFs oder Audio. Geokoordinaten legt man als Dezimalzahlen oder in einem speziellen Geodatentyp ab." },
  { id: "S7-27", modul: "S7", typ: "mc", niveau: 2, abschnitt: "Vom ER-Modell zu Tabellen", frage: "Beim Fremdschlüssel Auftrag → Kunde ist die **Löschweitergabe** (`ON DELETE CASCADE`) eingestellt. Was passiert, wenn ein Kunde gelöscht wird?",
    optionen: ["Seine Aufträge werden automatisch mit gelöscht", "Das Löschen wird verweigert, solange Aufträge existieren", "Die Aufträge bleiben ohne Kundenbezug bestehen", "Der Kunde wird nur ausgeblendet und bleibt in der Tabelle"], richtig: 0,
    erklaerung: "Option 2 wäre `RESTRICT`/`NO ACTION`. Die Weitergabe hält die referenzielle Integrität ein, kann aber ungewollt viele Daten entfernen." },
  { id: "S8-23", modul: "S8", typ: "mc", niveau: 1, abschnitt: "Entwurfsverfahren", frage: "Ein Entwickler zerlegt die Gesamtaufgabe „Rechnungsprogramm“ schrittweise in immer kleinere Teilaufgaben. Wie heißt dieses Vorgehen?",
    optionen: ["Top-down-Entwurf", "Bottom-up-Entwurf", "Black-Box-Test", "Refactoring"], richtig: 0,
    erklaerung: "**Top-down**: vom Ganzen zu den Details. **Bottom-up**: aus fertigen Bausteinen (z. B. Bibliotheken) wird das Gesamtsystem zusammengesetzt." },
  { id: "S8-24", modul: "S8", typ: "multi", niveau: 2, abschnitt: "Klassendiagramm", frage: "Welche UML-Diagramme zeigen das **dynamische Verhalten** eines Systems? (mehrere richtig)",
    optionen: ["Aktivitätsdiagramm", "Sequenzdiagramm", "Zustandsdiagramm", "Klassendiagramm", "Objektdiagramm"], richtig: [0, 1, 2],
    erklaerung: "Statische Sicht (Struktur): Klassen- und Objektdiagramm. Dynamische Sicht (Ablauf, Zeit, Zustände): Aktivitäts-, Sequenz- und Zustandsdiagramm." },
  { id: "S9-21", modul: "S9", typ: "mc", niveau: 1, abschnitt: "Unternehmenssoftware", frage: "Was kennzeichnet **Industrie 4.0**?",
    optionen: ["Die Vernetzung von Maschinen, Sensoren und Software, sodass Produktionsdaten in Echtzeit ausgetauscht und ausgewertet werden", "Die vierte Hochschulstufe der Informatik", "Den Wechsel von Dampfmaschinen zu Elektromotoren", "Den ausschließlichen Einsatz von Robotern ohne Datenverarbeitung"], richtig: 0,
    erklaerung: "Grundlage sind cyber-physische Systeme und das Internet der Dinge (IoT); typische Anwendung: vorausschauende Wartung und flexible Fertigung." },
  { id: "S9-22", modul: "S9", typ: "mc", niveau: 2, abschnitt: "Unternehmenssoftware", frage: "Eine Mitarbeiterin äußert sich auf ihrem **privaten Social-Media-Konto** abfällig über ihren Arbeitgeber und nennt interne Kundendaten. Welche Folge ist realistisch?",
    optionen: ["Datenschutzverstoß, Imageschaden und arbeitsrechtliche Konsequenzen wie Abmahnung oder Kündigung", "Keine Folgen, weil das Konto privat ist", "Das Unternehmen muss das Konto der Mitarbeiterin löschen lassen", "Die Aussage ist automatisch durch die Meinungsfreiheit geschützt, auch mit Kundendaten"], richtig: 0,
    erklaerung: "Verschwiegenheit und Datenschutz gelten auch im privaten Netz. Zwei Maßnahmen: klare Social-Media-Richtlinie und Schulung." },
  { id: "I3-22", modul: "I3", typ: "mc", niveau: 2, abschnitt: "Backupmedien", frage: "Was ermöglicht **LTFS** (Linear Tape File System) bei LTO-Bändern?",
    optionen: ["Zugriff auf die Bandinhalte wie auf ein Dateisystem mit Ordnern und Dateien", "Spiegeln des Bandes auf eine zweite Kassette in Echtzeit", "Verschlüsselung des Bandes mit einem Passwort ohne Hardware", "Umwandlung eines Bandes in eine SSD"], richtig: 0,
    erklaerung: "Das Band wird mit einem lesbaren Inhaltsverzeichnis beschrieben und lässt sich wie ein Laufwerk öffnen (einzelne Dateien kopieren), bleibt aber sequenziell." },
  { id: "I4-21", modul: "I4", typ: "mc", niveau: 2, abschnitt: "Grundbegriffe", frage: "Wodurch lassen sich Einträge in einer **Blockchain** nachträglich kaum unbemerkt verändern?",
    optionen: ["Jeder Block enthält den Hashwert des Vorgängers; die Kette liegt dezentral auf vielen Rechnern", "Alle Blöcke werden mit demselben Passwort verschlüsselt", "Ein zentraler Server speichert alle Einträge und prüft sie täglich", "Die Blöcke werden nach 24 Stunden automatisch gelöscht"], richtig: 0,
    erklaerung: "Ändert man einen Block, ändert sich sein Hash und damit passt die Verkettung zu den Folgeblöcken nicht mehr – das fällt allen Teilnehmern auf." },
  { id: "I5-25", modul: "I5", typ: "mc", niveau: 2, abschnitt: "Schadsoftware", frage: "Was kennzeichnet einen **APT-Angriff** (Advanced Persistent Threat)?",
    optionen: ["Ein gezielter, lange andauernder und getarnter Angriff meist auf eine bestimmte Organisation", "Eine massenhafte Spam-Welle an zufällige Empfänger", "Ein kurzer Ausfall durch Überlastung eines Servers", "Eine Warnmeldung der Antivirensoftware ohne echte Bedrohung"], richtig: 0,
    erklaerung: "Angreifer verschaffen sich dauerhaft Zugang, bewegen sich unbemerkt im Netz und greifen Daten ab. Schutz: Segmentierung, Monitoring, Rechtebeschränkung." },
  { id: "I5-26", modul: "I5", typ: "mc", niveau: 2, abschnitt: "Schadsoftware", frage: "Was ist eine **Zero-Day-Schwachstelle**?",
    optionen: ["Eine Sicherheitslücke, für die es noch keinen Patch gibt, weil sie dem Hersteller noch nicht oder erst kurz bekannt ist", "Eine Lücke, die nach dem Tag null der Lizenz auftritt", "Ein Fehler, der nach genau einem Tag automatisch behoben wird", "Eine Schwachstelle, die nur auf nicht aktualisierten Betriebssystemen vorkommt"], richtig: 0,
    erklaerung: "Gegen unbekannte Lücken helfen Härtung, Least Privilege, Segmentierung und Überwachung – ein Patch fehlt noch." },
  { id: "I5-27", modul: "I5", typ: "mc", niveau: 2, abschnitt: "Weitere Maßnahmen", frage: "Wozu setzt man einen **Schwachstellenscanner** (z. B. OpenVAS) ein?",
    optionen: ["Er prüft Systeme automatisiert auf bekannte Schwachstellen wie veraltete Software, offene Ports und Fehlkonfigurationen", "Er verschlüsselt alle Daten auf dem Server", "Er ersetzt die Firewall am Netzübergang", "Er löscht Schadsoftware automatisch ohne Rückfrage"], richtig: 0,
    erklaerung: "Ein Penetrationstest geht weiter: Er nutzt Lücken gezielt aus (meist manuell), um die tatsächliche Gefahr zu zeigen." },
  { id: "I5-28", modul: "I5", typ: "mc", niveau: 2, abschnitt: "Weitere Maßnahmen", frage: "Welche Aufgabe hat eine **Sandbox** im E-Mail-Eingang?",
    optionen: ["Verdächtige Anhänge werden in einer abgeschotteten Umgebung ausgeführt und ihr Verhalten beobachtet, bevor die Mail zugestellt wird", "Sie speichert alle Mails zehn Jahre revisionssicher", "Sie verschlüsselt eingehende Mails mit dem Schlüssel des Empfängers", "Sie blockiert grundsätzlich alle Mails mit Anhang"], richtig: 0,
    erklaerung: "Die Sandbox erkennt auch unbekannte Schadsoftware am Verhalten, nicht nur an Signaturen." },
  { id: "H2-24", modul: "H2", typ: "mc", niveau: 2, abschnitt: "Massenspeicher", frage: "Zwei Speicherlösungen sollen per **Benchmark** verglichen werden. Welche Testbedingung ist sinnvoll?",
    optionen: ["Gleiche Testdaten, Software und Einstellungen; keine Hintergrundlast; Messung mehrfach wiederholen", "Eine Lösung nachts, die andere tagsüber im laufenden Betrieb testen", "Nur eine Messung pro Lösung mit unterschiedlichen Dateigrößen", "Die schnellere Lösung zuerst testen und die zweite nur kurz"], richtig: 0,
    erklaerung: "Vergleichbarkeit entsteht nur bei gleichen Bedingungen. Mehrfachmessungen glätten Schwankungen." },
  // ---------------------------------------------------------------- Netzwerk
  { id: "N1-24", modul: "N1", typ: "mc", niveau: 1, abschnitt: "Netzarten nach Ausdehnung", frage: "Welche Reihenfolge ordnet Netzarten nach **wachsender Ausdehnung**?",
    optionen: ["PAN – LAN – MAN – WAN – GAN", "LAN – PAN – WAN – MAN – GAN", "GAN – WAN – MAN – LAN – PAN", "PAN – MAN – LAN – GAN – WAN"], richtig: 0,
    erklaerung: "PAN (Person) → LAN (Gebäude) → MAN (Stadt) → WAN (Länder) → GAN (weltweit, z. B. Satelliten)." },
  { id: "N5-23", modul: "N5", typ: "mc", niveau: 1, abschnitt: "Internetanbindung", frage: "Was bedeutet das **A** in **ADSL**?",
    optionen: ["Asymmetrisch – die Download-Rate ist höher als die Upload-Rate", "Analog – die Übertragung erfolgt ohne digitale Signale", "Automatisch – die Leitung wählt die Rate selbst", "Aktiv – es wird zusätzliche Hardware beim Kunden benötigt"], richtig: 0,
    erklaerung: "Bei **SDSL** sind beide Richtungen gleich schnell (wichtig für Firmen mit VPN und Servern), VDSL erreicht höhere Raten auf kurzen Strecken." },
  // ---------------------------------------------------------------- Wirtschaft
  { id: "W4-22", modul: "W4", typ: "mc", niveau: 2, abschnitt: "Rechtliche Grundlagen", frage: "Was regelt das **Gesetz gegen den unlauteren Wettbewerb (UWG)**?",
    optionen: ["Den Schutz vor irreführender oder aggressiver Werbung und anderen unlauteren geschäftlichen Handlungen", "Das Verbot von Preisabsprachen zwischen Unternehmen", "Die Kündigungsfristen in Arbeitsverhältnissen", "Die Pflicht zur Aufbewahrung von Rechnungen"], richtig: 0,
    erklaerung: "Beispiel: Werbeanrufe ohne Einwilligung. Preisabsprachen verbietet das GWB (Kartellrecht)." },
  { id: "W5-21", modul: "W5", typ: "mc", niveau: 2, abschnitt: "Unternehmensverbindungen", frage: "Rechtlich selbständige Unternehmen stehen unter **einheitlicher Leitung** eines Mutterunternehmens. Wie heißt diese Verbindung?",
    optionen: ["Konzern", "Kartell", "Fusion", "Genossenschaft"], richtig: 0,
    erklaerung: "**Fusion**: Unternehmen verschmelzen rechtlich. **Kartell**: selbständige Unternehmen sprechen sich ab (meist verboten). **Konzern**: einheitliche Leitung bei rechtlicher Selbständigkeit." },
  { id: "W5-22", modul: "W5", typ: "mc", niveau: 2, abschnitt: "Gesamtwirtschaft", frage: "Welche Wirtschaftsordnung verbindet Wettbewerb am Markt mit staatlichem **sozialem Ausgleich** (z. B. Sozialversicherung)?",
    optionen: ["Soziale Marktwirtschaft", "Zentralverwaltungswirtschaft", "Freie Marktwirtschaft ohne Staatseingriffe", "Planwirtschaft"], richtig: 0,
    erklaerung: "Deutschland: freier Wettbewerb und Privateigentum, aber Sozialstaat, Kartellkontrolle und Arbeitnehmerschutz." },
  { id: "W5-23", modul: "W5", typ: "mc", niveau: 2, abschnitt: "Lohn und Gehalt", frage: "Was sind **vermögenswirksame Leistungen (VL)**?",
    optionen: ["Geldbeträge, die der Arbeitgeber für den Arbeitnehmer langfristig anlegt (z. B. Bausparen oder Fondssparen) und die staatlich gefördert werden können", "Eine Nachzahlung des Gehalts bei verspäteter Überweisung", "Der Anteil des Gehalts, der als Sozialversicherung abgeführt wird", "Eine Zulage für Überstunden"], richtig: 0,
    erklaerung: "VL stehen auf der Gehaltsabrechnung; bei Tarifverträgen sind sie oft geregelt." },
  { id: "W6-21", modul: "W6", typ: "mc", niveau: 1, abschnitt: "Marketing", frage: "Wofür steht die **SWOT-Analyse**?",
    optionen: ["Stärken, Schwächen (intern) sowie Chancen, Risiken (extern)", "Standort, Wettbewerb, Organisation, Technik", "Sicherheit, Wartung, Optimierung, Test", "Strategie, Wirtschaftlichkeit, Ordnung, Termin"], richtig: 0,
    erklaerung: "Strengths, Weaknesses, Opportunities, Threats – Grundlage für strategische Entscheidungen." },
  { id: "W6-22", modul: "W6", typ: "mc", niveau: 1, abschnitt: "Betriebswirtschaftliche Kennzahlen", frage: "Was ist ein **KPI** (Key Performance Indicator)?",
    optionen: ["Eine Kennzahl, die den Erfüllungsgrad eines Ziels messbar macht (z. B. Erstlösungsquote im Support)", "Ein Vertragsbestandteil für Konventionalstrafen", "Eine Form der Abschreibung", "Eine Norm für Qualitätsmanagement"], richtig: 0,
    erklaerung: "KPIs vergleichen Ist- mit Zielwerten und zeigen Abweichungen früh." },
  // ---------------------------------------------------------------- Projekt und Service
  { id: "P1-21", modul: "P1", typ: "mc", niveau: 2, abschnitt: "Vorgehensmodelle", frage: "Was kennzeichnet das **Spiralmodell**?",
    optionen: ["Mehrere Durchläufe mit Zielfestlegung, Risikoanalyse, Entwicklung/Test und Planung des nächsten Umlaufs", "Streng nacheinander ablaufende Phasen ohne Rücksprünge", "Tägliche Abstimmung im Team über 15 Minuten", "Eine Aufgabentafel mit Spalten und WIP-Limit"], richtig: 0,
    erklaerung: "Besonders für große, riskante Projekte: Risiken werden in jedem Umlauf bewertet. Wasserfall = sequenziell, Scrum = Sprints, Kanban = Tafel." },
  { id: "P3-21", modul: "P3", typ: "mc", niveau: 2, abschnitt: "IT-Service-Management", frage: "Was ist eine **SOP (Standard Operating Procedure)**?",
    optionen: ["Eine standardisierte, dokumentierte Arbeitsanweisung für wiederkehrende Abläufe", "Ein Vertrag über Servicezeiten", "Eine Software zur Passwortverwaltung", "Eine Norm für Ergonomie am Arbeitsplatz"], richtig: 0,
    erklaerung: "Z. B. „Neuen Mitarbeiter einrichten“ oder „Störung eskalieren“ – sorgt für gleichbleibende Qualität und erleichtert die Einarbeitung." },
  { id: "P4-21", modul: "P4", typ: "mc", niveau: 1, abschnitt: "Präsentation und Einweisung", frage: "Wofür steht **Corporate Identity (CI)**?",
    optionen: ["Die einheitliche Identität eines Unternehmens in Verhalten, Kommunikation und Erscheinungsbild", "Die Kennnummer eines Unternehmens im Handelsregister", "Die Verschlüsselung der Firmenkommunikation", "Die Verteilung der Aufgaben im Projekt"], richtig: 0,
    erklaerung: "Das Corporate Design (Logo, Farben, Schrift) ist ein Teil davon und wird z. B. bei Präsentationen und Bildschirmmasken beachtet." },
  { id: "P4-22", modul: "P4", typ: "multi", niveau: 1, abschnitt: "Schriftliche Kommunikation", frage: "Welche Regeln gehören zur **Netiquette** bei dienstlichen E-Mails? (mehrere richtig)",
    optionen: ["Aussagekräftiger Betreff", "Höfliche, kurze und eindeutige Formulierung", "„Allen antworten“ nur, wenn alle die Antwort brauchen", "Alles in Großbuchstaben schreiben, damit es auffällt", "Verteiler offen halten, auch bei externen Empfängern"], richtig: [0, 1, 2],
    erklaerung: "Großbuchstaben wirken wie Schreien. Externe Empfänger gehören in BCC, damit Adressen nicht offengelegt werden." },
  { id: "P5-21", modul: "P5", typ: "mc", niveau: 2, abschnitt: "Arbeitssicherheit", frage: "Ein Gerät hat **Schutzklasse II** (Symbol: Doppelquadrat). Was bedeutet das?",
    optionen: ["Schutzisolierung – es braucht keinen Schutzleiteranschluss", "Das Gerät ist wasserdicht", "Das Gerät darf nur von Elektrofachkräften bedient werden", "Das Gerät ist für Niederspannung unter 12 V ausgelegt"], richtig: 0,
    erklaerung: "Schutzklasse I: Gehäuse mit Schutzleiter verbunden (Schuko). Schutzklasse II: doppelte oder verstärkte Isolierung. Die Schutzart (IP-Code) beschreibt dagegen Staub- und Wasserschutz." },
  { id: "P5-22", modul: "P5", typ: "mc", niveau: 1, abschnitt: "Brandschutz", frage: "Zu welcher **Brandklasse** gehört ein Brand von festen Stoffen wie Papier und Holz?",
    optionen: ["A", "B", "C", "D"], richtig: 0,
    erklaerung: "A feste Stoffe · B flüssige Stoffe · C Gase · D Metalle. (Fettbrände: F.)" },
  { id: "P5-23", modul: "P5", typ: "mc", niveau: 1, abschnitt: "Brandschutz", frage: "In der Teeküche gerät die Kleidung einer Kollegin in Brand. Welches Mittel setzen Sie am besten ein?",
    optionen: ["Löschdecke", "Wasserglas aus der Küche", "Eine Spraydose mit Druckluft", "Gar nichts, auf den Rettungsdienst warten"], richtig: 0,
    erklaerung: "Die Löschdecke erstickt die Flammen. Zusätzlich Notruf 112 absetzen und die Person nicht rennen lassen." },
  { id: "P5-24", modul: "P5", typ: "mc", niveau: 2, abschnitt: "Der ergonomische Bildschirmarbeitsplatz", frage: "Welche Vorsorgeuntersuchung muss der Arbeitgeber Beschäftigten an **Bildschirmarbeitsplätzen** anbieten?",
    optionen: ["Eine Untersuchung der Augen und des Sehvermögens", "Eine jährliche Röntgenuntersuchung der Wirbelsäule", "Einen Hörtest alle zwei Jahre", "Eine Blutuntersuchung auf Allergien"], richtig: 0,
    erklaerung: "Angebotsvorsorge nach der Verordnung zur arbeitsmedizinischen Vorsorge. Bei Beschwerden kann ggf. eine Bildschirmbrille nötig sein." },
  { id: "P5-25", modul: "P5", typ: "mc", niveau: 2, abschnitt: "Rechtlicher Rahmen", frage: "Welche Stelle überwacht staatlich die Einhaltung der **Arbeitsschutzvorschriften** im Betrieb?",
    optionen: ["Die Gewerbeaufsicht (Arbeitsschutzbehörde)", "Das Finanzamt", "Die Industrie- und Handelskammer", "Die Agentur für Arbeit"], richtig: 0,
    erklaerung: "Die Berufsgenossenschaft überwacht zusätzlich die Unfallverhütungsvorschriften (UVV) und berät die Betriebe." }
]
