// Fragenpool zu den Themen, die mit der zweiten Auflage des Prüfungskatalogs (ab Frühjahr 2025; Aufgabenerstellung ZPA Nord-West, bundeseinheitlich) hinzugekommen sind
[
  // ---------------------------------------------------------------- N7
  { id: "N7-01", modul: "N7", typ: "mc", niveau: 1, frage: "Welcher Teil der URL `https://www.firma.de/kontakt.php?lang=de#formular` ist der **Query-String**?",
    optionen: ["https", "www.firma.de", "?lang=de", "#formular"], richtig: 2, abschnitt: "Aufbau einer URL",
    erklaerung: "Parameter nach dem **?** als Name=Wert-Paare; `#formular` ist das Fragment." },
  { id: "N7-02", modul: "N7", typ: "mc", niveau: 2, frage: "Welcher Teil einer URL wird **nicht** an den Webserver übertragen?",
    optionen: ["Pfad", "Query-String", "Fragment (#…)", "Hostname"], richtig: 2, abschnitt: "Aufbau einer URL",
    erklaerung: "Das **Fragment** wertet nur der Browser aus (Sprung innerhalb der Seite)." },
  { id: "N7-03", modul: "N7", typ: "mc", niveau: 1, frage: "Was kennzeichnet eine **dynamische** Website?",
    optionen: ["Sie enthält Animationen und Videos", "Inhalte werden beim Aufruf auf dem Server erzeugt", "Sie besteht aus fertigen HTML-Dateien", "Sie wird vollständig im Browser gespeichert"], richtig: 1, abschnitt: "Statische und dynamische Websites",
    erklaerung: "Entscheidend ist die **serverseitige** Erzeugung – nicht Bewegung auf der Seite." },
  { id: "N7-04", modul: "N7", typ: "multi", niveau: 2, frage: "Welche Sprachen eignen sich für die **serverseitige** Entwicklung dynamischer Websites? (mehrere richtig)",
    optionen: ["PHP", "Python", "Java", "HTML", "CSS"], richtig: [0, 1, 2], abschnitt: "Die Sprachen des Webs",
    erklaerung: "PHP, Python, Java (auch C#, Node.js). HTML und CSS beschreiben Struktur und Gestaltung." },
  { id: "N7-05", modul: "N7", typ: "mc", niveau: 1, frage: "Wie wird die Web-Technologie **HTML** (HyperText Markup Language) fachlich korrekt eingeordnet?",
    optionen: ["eine Programmiersprache für Webserver", "eine Auszeichnungssprache für Webseiten", "ein Protokoll zur Übertragung von Seiten", "eine Sprache zur Gestaltung von Layouts"], richtig: 1, abschnitt: "Die Sprachen des Webs",
    erklaerung: "HTML = HyperText **Markup** Language – keine Programmiersprache." },
  { id: "N7-06", modul: "N7", typ: "mc", niveau: 1, frage: "Welche Hauptaufgabe übernimmt **CSS** (Cascading Style Sheets) bei der Webseitenerstellung?",
    optionen: ["Datenbankabfragen", "Optische Gestaltung und Layout", "Serverlogik", "Verschlüsselung"], richtig: 1, abschnitt: "Die Sprachen des Webs",
    erklaerung: "Farben, Schriften, Layout, Anpassung an Bildschirmgrößen." },
  { id: "N7-07", modul: "N7", typ: "zahl", niveau: 1, frage: "Welchen HTTP-Statuscode liefert ein Server, wenn die angeforderte Seite **nicht existiert**?", richtig: 404, toleranz: 0, abschnitt: "Was passiert beim Aufruf",
    erklaerung: "**404 Not Found**; 200 = OK, 500 = Serverfehler." },
  { id: "N7-08", modul: "N7", typ: "mc", niveau: 2, frage: "Womit erkennt ein Webserver einen eingeloggten Nutzer bei späteren Anfragen wieder, obwohl HTTP zustandslos ist?",
    optionen: ["an der MAC-Adresse des Clients", "über Cookies bzw. eine Sitzungs-ID", "am Namen und der Version des Browsers", "an der Portnummer der Verbindung"], richtig: 1, abschnitt: "Was passiert beim Aufruf",
    erklaerung: "**Cookies/Session-IDs** speichern den Zustand." },
  { id: "N7-09", modul: "N7", typ: "mc", niveau: 2, frage: "Mit welcher HTTP-Methode werden Formulardaten typischerweise an den Server **gesendet**?",
    optionen: ["GET", "POST", "HEAD", "TRACE"], richtig: 1, abschnitt: "Was passiert beim Aufruf",
    erklaerung: "**POST** überträgt Daten im Rumpf der Anfrage; GET ruft Daten ab." },
  { id: "N7-10", modul: "N7", typ: "mc", niveau: 1, frage: "Was versteht man unter dem Begriff **Responsive Webdesign**?",
    optionen: ["Die Seite lädt besonders schnell", "Das visuelle Layout passt sich dynamisch an unterschiedliche Bildschirmgrößen an", "Die Seite reagiert auf Spracheingaben", "Die Seite erfüllt alle WCAG-Kriterien"], richtig: 1, abschnitt: "Anforderungen an eine Firmenwebsite",
    erklaerung: "Per CSS (Media Queries, flexible Raster) für Smartphone, Tablet und Desktop." },
  { id: "N7-11", modul: "N7", typ: "multi", niveau: 2, frage: "Was gehört in das **Impressum** einer Firmenwebsite? (mehrere richtig)",
    optionen: ["Name und Anschrift des Unternehmens", "E-Mail-Adresse und Telefon", "Handelsregistereintrag und USt-IdNr.", "die Gehälter der Geschäftsführung"], richtig: [0, 1, 2], abschnitt: "Anforderungen an eine Firmenwebsite",
    erklaerung: "Anbieterkennzeichnung: Name, Anschrift, schnelle Kontaktmöglichkeit, Vertretungsberechtigte, Register, USt-IdNr." },
  { id: "N7-12", modul: "N7", typ: "mc", niveau: 2, frage: "Welcher Vorteil spricht für ein **CMS** bei einer Firmenwebsite?",
    optionen: ["Es benötigt keine Sicherheitsupdates", "Inhalte ohne HTML-Kenntnisse pflegen", "Es ist immer schneller als statisches HTML", "Es ersetzt den Webserver vollständig"], richtig: 1, abschnitt: "Webserver, Hosting und CMS",
    erklaerung: "Pflege über die Weboberfläche – Nachteil: regelmäßige Updates von Kern und Plugins nötig." },
  { id: "N7-13", modul: "N7", typ: "mc", niveau: 2, frage: "Welcher Vorteil gilt für eine **statische** Website?",
    optionen: ["personalisierte Inhalte je Besucher", "sicher, schnell und günstig zu hosten", "Onlineshop und Login direkt möglich", "Pflege ohne HTML-Kenntnisse"], richtig: 1, abschnitt: "Statische und dynamische Websites",
    erklaerung: "Keine Serverlogik und Datenbank → **wenig Angriffsfläche**, schnell, günstig." },
  { id: "N7-14", modul: "N7", typ: "mc", niveau: 2, frage: "Was ermöglichen **virtuelle Hosts** auf einem Webserver?",
    optionen: ["mehrere Domains auf einem Webserver", "Websites ohne Internetverbindung", "automatische Sicherung aller Websites", "verschlüsselte VPN-Zugänge für Besucher"], richtig: 0, abschnitt: "Webserver, Hosting und CMS",
    erklaerung: "Der Server unterscheidet die Anfragen am **Hostnamen**." },
  { id: "N7-15", modul: "N7", typ: "mc", niveau: 2, frage: "Wofür steht das `alt`-Attribut bei einem Bild in HTML?",
    optionen: ["Anzeigegröße des Bildes", "Alternativtext, z. B. für Screenreader", "Dateiformat des Bildes", "Link zur größeren Bildversion"], richtig: 1, abschnitt: "Die Sprachen des Webs",
    erklaerung: "Der **Alternativtext** macht Bilder für blinde Nutzer verständlich – Barrierefreiheit." },
  { id: "N7-16", modul: "N7", typ: "mc", niveau: 2, frage: "Ein Menü klappt im Browser per JavaScript auf. Wo läuft dieser Code?",
    optionen: ["auf dem Webserver", "clientseitig im Browser", "im DNS-Server", "in der Datenbank"], richtig: 1, abschnitt: "Statische und dynamische Websites",
    erklaerung: "JavaScript im Browser = **clientseitig**." },
  { id: "N7-17", modul: "N7", typ: "mc", niveau: 1, frage: "Welcher Dienst wandelt beim Aufruf von `www.firma.de` den Namen in eine IP-Adresse um?",
    optionen: ["DHCP", "DNS", "NTP", "SMTP"], richtig: 1, abschnitt: "Was passiert beim Aufruf",
    erklaerung: "**DNS** – erst danach baut der Browser die Verbindung auf." },
  { id: "N7-18", modul: "N7", typ: "mc", niveau: 2, frage: "Wofür braucht eine Website mit Statistik-Cookies eine **Einwilligung** der Besucher?",
    optionen: ["für technisch notwendige Cookies", "für Statistik- und Werbe-Cookies", "für jeden Aufruf einer Unterseite", "nur bei Onlineshops mit Kundenkonto"], richtig: 1, abschnitt: "Anforderungen an eine Firmenwebsite",
    erklaerung: "Nicht notwendige Cookies erst nach **Einwilligung** setzen." },
  { id: "N7-19", modul: "N7", typ: "mc", niveau: 1, frage: "Welches Format nutzen Web-APIs häufig für den Datenaustausch?",
    optionen: ["JSON", "BMP", "MP3", "EXE"], richtig: 0, abschnitt: "Die Sprachen des Webs",
    erklaerung: "**JSON** (auch XML) – strukturierte Daten als Text." },
  { id: "N7-20", modul: "N7", typ: "mc", niveau: 2, frage: "Welche Software ist ein **Webserver**?",
    optionen: ["nginx", "Excel", "Outlook", "VirtualBox"], richtig: 0, abschnitt: "Webserver, Hosting und CMS",
    erklaerung: "nginx, Apache und IIS sind verbreitete Webserver." },

  // ---------------------------------------------------------------- S9
  { id: "S9-01", modul: "S9", typ: "mc", niveau: 1, frage: "Was versteht man unter dem Begriff **maschinelles Lernen** (Machine Learning)?",
    optionen: ["Ein Roboter lernt durch physische Bewegung", "Ein algorithmisches System lernt eigenständig Muster und Regeln aus Trainingsdaten", "Ein Entwickler programmiert alle Entscheidungsregeln fest ein", "Ein Compiler optimiert den Maschinencode selbst"], richtig: 1, abschnitt: "Begriffe",
    erklaerung: "ML lernt aus **Daten** – die Qualität der Daten bestimmt die Qualität der Ergebnisse." },
  { id: "S9-02", modul: "S9", typ: "mc", niveau: 1, frage: "Was ist eine **Halluzination** bei generativer KI?",
    optionen: ["ein Absturz des KI-Dienstes", "eine überzeugende, aber falsche Ausgabe", "ein bewusst erzeugtes Bild", "eine Verzögerung bei der Antwort"], richtig: 1, abschnitt: "Begriffe",
    erklaerung: "Erfundene Fakten oder Quellen – deshalb Ergebnisse immer **prüfen**." },
  { id: "S9-03", modul: "S9", typ: "multi", niveau: 2, frage: "Welche **Vorteile** hat ein Chatbot auf der Website einer Kanzlei? (mehrere richtig)",
    optionen: ["rund um die Uhr erreichbar", "entlastet bei Routinefragen", "ersetzt die Rechtsberatung vollständig", "erfasst Anfragen strukturiert"], richtig: [0, 1, 3], abschnitt: "Chatbots",
    erklaerung: "Eine verbindliche Rechtsberatung darf der Chatbot **nicht** ersetzen – Fehlauskünfte sind ein Risiko." },
  { id: "S9-04", modul: "S9", typ: "mc", niveau: 2, frage: "Ein Mitarbeiter will einen Mandantenschriftsatz in einen kostenlosen öffentlichen KI-Dienst kopieren. Was ist das Hauptproblem?",
    optionen: ["Der Text überschreitet die Eingabelänge", "Vertrauliche Daten gelangen zu einem Dritten", "Die KI beherrscht keine Fachsprache", "Der Dienst verlangt eine Registrierung"], richtig: 1, abschnitt: "Risiken und rechtlicher Rahmen",
    erklaerung: "Keine vertraulichen Daten in öffentliche Dienste; nur geprüfte Anbieter mit **AVV**, EU-Standort, ohne Trainingsnutzung." },
  { id: "S9-05", modul: "S9", typ: "mc", niveau: 2, frage: "Was verlangt der **EU AI Act** bei Chatbots gegenüber Kunden?",
    optionen: ["Keine besonderen Pflichten für Chatbots", "Nutzer müssen erkennen, dass es eine KI ist", "Chatbots sind im Kundenkontakt verboten", "Jeder Chatbot braucht eine IHK-Zulassung"], richtig: 1, abschnitt: "Risiken und rechtlicher Rahmen",
    erklaerung: "**Transparenzpflicht**; strenge Pflichten gelten für Hochrisiko-KI (z. B. Personalauswahl)." },
  { id: "S9-06", modul: "S9", typ: "zahl", niveau: 2, frage: "Ein Chatbot kostet **49 €** Grundgebühr plus **0,03 €** je Gespräch. Wie hoch sind die Monatskosten bei **1 200** Gesprächen in €?", richtig: 85, toleranz: 0, einheit: "€", abschnitt: "Kosten eines KI-Dienstes",
    erklaerung: "49 + 1 200 × 0,03 = 49 + 36 = **85 €**." },
  { id: "S9-07", modul: "S9", typ: "zahl", niveau: 2, frage: "15 Mitarbeitende erhalten einen KI-Assistenten zu je **22 € netto** im Monat. Jahreskosten netto in €?", richtig: 3960, toleranz: 0, einheit: "€", abschnitt: "Kosten eines KI-Dienstes",
    erklaerung: "15 × 22 × 12 = **3 960 €**." },
  { id: "S9-08", modul: "S9", typ: "mc", niveau: 2, frage: "Mitarbeitende befürchten, durch KI ersetzt zu werden. Was ist die beste Reaktion?",
    optionen: ["Die Bedenken als unbegründet zurückweisen", "Offen informieren, Betriebsrat einbinden, schulen", "KI zunächst ohne Ankündigung testen", "Nur die Führungskräfte informieren"], richtig: 1, abschnitt: "Bedenken der Mitarbeitenden",
    erklaerung: "Transparenz, Beteiligung und Qualifizierung schaffen **Akzeptanz**." },
  { id: "S9-09", modul: "S9", typ: "mc", niveau: 1, frage: "Welches System steuert **alle Geschäftsprozesse** (Einkauf, Lager, Vertrieb, Finanzen) mit einer gemeinsamen Datenbank?",
    optionen: ["CRM", "ERP", "DMS", "CMS"], richtig: 1, abschnitt: "Unternehmenssoftware",
    erklaerung: "**ERP** = Enterprise Resource Planning." },
  { id: "S9-10", modul: "S9", typ: "mc", niveau: 1, frage: "Wofür wird ein **CRM**-System eingesetzt?",
    optionen: ["Planung der Lieferkette", "Verwaltung der Kundenbeziehungen", "Archivierung von Dokumenten", "Planung von Personal und Schichten"], richtig: 1, abschnitt: "Unternehmenssoftware",
    erklaerung: "Customer Relationship Management." },
  { id: "S9-11", modul: "S9", typ: "mc", niveau: 1, frage: "Welches System legt Dokumente revisionssicher und versioniert ab?",
    optionen: ["DMS", "SCM", "ERP", "LMS"], richtig: 0, abschnitt: "Unternehmenssoftware",
    erklaerung: "**Dokumentenmanagementsystem**." },
  { id: "S9-12", modul: "S9", typ: "mc", niveau: 2, frage: "Worum handelt es sich bei einem **LLM** (Large Language Model)?",
    optionen: ["ein großes, auf Texten trainiertes neuronales Sprachmodell", "ein Protokoll für Maschine-zu-Maschine-Kommunikation", "ein Lizenzmodell für Machine-Learning-Software", "eine relationale Datenbank für strukturierte Lerndaten"], richtig: 0, abschnitt: "Begriffe",
    erklaerung: "Large Language Model – Grundlage vieler Chatbots." },
  { id: "S9-13", modul: "S9", typ: "mc", niveau: 2, frage: "Eine KI zur Bewerbervorauswahl bevorzugt systematisch eine Gruppe. Wie nennt man das?",
    optionen: ["Halluzination", "Bias (Verzerrung)", "Overfitting", "Prompt Injection"], richtig: 1, abschnitt: "Begriffe",
    erklaerung: "**Bias** – Entscheidungen über Menschen nicht allein der KI überlassen." },
  { id: "S9-14", modul: "S9", typ: "mc", niveau: 1, frage: "Welcher Einsatz von KI passt zum **IT-Support**?",
    optionen: ["Tickets klassifizieren und Lösungen vorschlagen", "Serverräume automatisch klimatisieren", "Netzwerkkabel automatisch prüfen", "Lizenzschlüssel automatisch erzeugen"], richtig: 0, abschnitt: "Einsatzszenarien im Betrieb",
    erklaerung: "Klassifizierung und Vorschläge aus der **Wissensdatenbank** verkürzen die Bearbeitung." },
  { id: "S9-15", modul: "S9", typ: "mc", niveau: 2, frage: "Was bedeutet „Human in the Loop“?",
    optionen: ["Die KI lernt aus menschlichen Gesprächen", "Ein Mensch prüft und verantwortet die Ergebnisse", "Die KI entscheidet ohne menschliche Kontrolle", "Mehrere Menschen chatten mit derselben KI"], richtig: 1, abschnitt: "Risiken und rechtlicher Rahmen",
    erklaerung: "Menschliche **Kontrolle** vor wichtigen Entscheidungen." },
  { id: "S9-16", modul: "S9", typ: "mc", niveau: 2, frage: "Welcher Vorteil gilt für ein **integriertes ERP-System**?",
    optionen: ["Daten einmal erfasst, für alle aktuell", "Keine Lizenzkosten durch Open Source", "Keine Schulung der Anwender nötig", "Keine Anpassung an Prozesse nötig"], richtig: 0, abschnitt: "Unternehmenssoftware",
    erklaerung: "Keine doppelte Pflege, weniger Fehler – aber hohe Einführungskosten." },
  { id: "S9-17", modul: "S9", typ: "mc", niveau: 1, frage: "Was bezeichnet der Begriff **Prompt** bei der Interaktion mit generativer KI?",
    optionen: ["die Eingabeanweisung bzw. Fragestellung an das KI-System", "die generierte Antwortausgabe des KI-Systems", "den Datensatz, mit dem das Modell trainiert wurde", "den Lizenzvertrag für einen kommerziellen KI-Dienst"], richtig: 0, abschnitt: "Begriffe",
    erklaerung: "Je genauer der Prompt, desto brauchbarer das Ergebnis." },
  { id: "S9-18", modul: "S9", typ: "mc", niveau: 2, frage: "Welche Aussage zum aktuellen Entwicklungsstand künstlicher Intelligenz trifft zu?",
    optionen: ["Es existieren bereits praxistaugliche Systeme mit starker KI und eigenem Bewusstsein", "Aktuelle KI-Systeme (schwache KI) sind auf spezifische Aufgaben trainiert und spezialisiert", "Aktuelle generative KI-Modelle arbeiten grundsätzlich deterministisch und fehlerfrei", "Moderne KI-Modelle benötigen keinerlei Trainingsdaten vor dem Einsatz"], richtig: 1, abschnitt: "Begriffe",
    erklaerung: "**Schwache KI** – leistungsfähig, aber spezialisiert und fehlbar." },
  { id: "S9-19", modul: "S9", typ: "mc", niveau: 2, frage: "Welches System plant Lieferanten, Bestände und Transporte?",
    optionen: ["SCM", "CRM", "CMS", "DMS"], richtig: 0, abschnitt: "Unternehmenssoftware",
    erklaerung: "**Supply Chain Management**." },
  { id: "S9-20", modul: "S9", typ: "mc", niveau: 2, frage: "Welches IT-Sicherheitsrisiko ist typisch für KI-Anwendungen?",
    optionen: ["Prompt Injection und Datenabfluss", "Überhitzung der Grafikkarte", "Zu hohe Bildwiederholrate", "Fehlende Druckertreiber"], richtig: 0, abschnitt: "Risiken und rechtlicher Rahmen",
    erklaerung: "Manipulierte Eingaben können die KI zu unerwünschten Aktionen bringen; Eingaben können vertrauliche Daten enthalten." },

  // ---------------------------------------------------------------- W6
  { id: "W6-01", modul: "W6", typ: "mc", niveau: 1, frage: "Wann wird aus einem Bedürfnis ein **Bedarf**?",
    optionen: ["wenn Kaufkraft vorhanden ist", "wenn es am Markt gekauft wird", "wenn es in der Werbung vorkommt", "immer"], richtig: 0, abschnitt: "Markt und Bedarf",
    erklaerung: "Bedarf = Bedürfnis **mit Kaufkraft**; Nachfrage = Bedarf, der am Markt auftritt." },
  { id: "W6-02", modul: "W6", typ: "mc", niveau: 1, frage: "Viele Anbieter stehen vielen Nachfragern gegenüber. Welche Marktform ist das?",
    optionen: ["Monopol", "Oligopol", "Polypol", "Monopson"], richtig: 2, abschnitt: "Marktformen",
    erklaerung: "**Polypol** – starker Wettbewerb." },
  { id: "W6-03", modul: "W6", typ: "mc", niveau: 1, frage: "Zu welcher Methode der Marktforschung zählt eine eigens im Unternehmen durchgeführte Kundenbefragung?",
    optionen: ["Sekundärforschung", "Primärforschung", "Marktform", "ABC-Analyse"], richtig: 1, abschnitt: "Marktforschung",
    erklaerung: "Eigene Erhebung = **Primärforschung**; vorhandene Statistiken = Sekundärforschung." },
  { id: "W6-04", modul: "W6", typ: "text", niveau: 1, frage: "Wofür steht das **A** am Ende des AIDA-Modells (englischer Begriff)?", richtig: ["Action"], abschnitt: "Marketing",
    erklaerung: "Attention – Interest – Desire – **Action**." },
  { id: "W6-05", modul: "W6", typ: "mc", niveau: 2, frage: "Welche Klasse erhalten in der ABC-Analyse die Artikel mit dem **größten Wertanteil** bei kleiner Menge?",
    optionen: ["A", "B", "C", "D"], richtig: 0, abschnitt: "Marketing",
    erklaerung: "**A**-Güter: ca. 70–80 % des Werts, 10–20 % der Menge – intensiv betreuen." },
  { id: "W6-06", modul: "W6", typ: "zahl", niveau: 2, frage: "Preis **89 €**, variable Kosten **34 €** je Einheit. Wie hoch ist der **Deckungsbeitrag** je Einheit in €?", richtig: 55, toleranz: 0, einheit: "€", abschnitt: "Kosten, Deckungsbeitrag",
    erklaerung: "DB = Preis − variable Kosten = **55 €**." },
  { id: "W6-07", modul: "W6", typ: "zahl", niveau: 2, frage: "Fixkosten **2 200 €**, Deckungsbeitrag **55 €** je Kunde. Ab wie vielen Kunden ist die Gewinnschwelle erreicht?", richtig: 40, toleranz: 0, einheit: "Kunden", abschnitt: "Kosten, Deckungsbeitrag",
    erklaerung: "2 200 ÷ 55 = **40 Kunden**." },
  { id: "W6-08", modul: "W6", typ: "zahl", niveau: 3, frage: "Personalkosten **60 000 €**, Gemeinkosten **24 000 €** im Jahr, **1 200** verrechenbare Stunden, Gewinnzuschlag **10 %**. Stundensatz in €? (2 Nachkommastellen)", richtig: 77, toleranz: 0.01, einheit: "€", abschnitt: "Stundensatz kalkulieren",
    erklaerung: "84 000 ÷ 1 200 = 70 €/h × 1,1 = **77,00 €**." },
  { id: "W6-09", modul: "W6", typ: "mc", niveau: 2, frage: "Warum rechnet man den Stundensatz mit den **verrechenbaren** statt mit allen Arbeitsstunden?",
    optionen: ["Nur diese Stunden werden Kunden berechnet", "Sie ergeben einen niedrigeren Stundensatz", "Das Finanzamt verlangt diese Rechnung", "Urlaub und Krankheit zählen doppelt"], richtig: 0, abschnitt: "Stundensatz kalkulieren",
    erklaerung: "Fahrten, Schulungen und interne Aufgaben bezahlt kein Kunde direkt – ihre Kosten müssen über die verrechenbaren Stunden hereinkommen. Dadurch wird der Stundensatz **höher**, nicht niedriger." },
  { id: "W6-10", modul: "W6", typ: "mc", niveau: 1, frage: "Welche der folgenden Kostenarten zählt typischerweise zu den **Fixkosten**?",
    optionen: ["Miete der Büroräume", "Fertigungsmaterial je hergestelltem Stück", "Gebühren für verbrauchten Cloud-Speicherplatz beim Kunden", "Vergütung für projektbezogene Fremdleistungen je Stunde"], richtig: 0, abschnitt: "Kosten, Deckungsbeitrag",
    erklaerung: "Fixkosten fallen **unabhängig von der Menge** an." },
  { id: "W6-11", modul: "W6", typ: "zahl", niveau: 3, frage: "Ein Betrieb prüft Make-or-Buy: Bei Eigenfertigung entstehen jährliche Fixkosten von **6 000 €** plus variable Kosten von **36 €** je Stück. Der Fremdbezug kostet **144 €** je Stück. Ab welcher Stückzahl pro Jahr ist die Eigenfertigung wirtschaftlicher? (ganze Zahl, aufrunden)", richtig: 56, toleranz: 0, abschnitt: "Make-or-buy",
    erklaerung: "6 000 + 36x = 144x → x = 6 000 ÷ 108 = 55,6 → ab **56** Stück." },
  { id: "W6-12", modul: "W6", typ: "multi", niveau: 2, frage: "Welche **qualitativen** Gründe zählen bei Make-or-buy? (mehrere richtig)",
    optionen: ["Know-how im eigenen Haus", "Abhängigkeit vom Lieferanten", "Datenschutz und Geheimhaltung", "Stückkosten"], richtig: [0, 1, 2], abschnitt: "Make-or-buy",
    erklaerung: "Stückkosten sind **quantitativ**." },
  { id: "W6-13", modul: "W6", typ: "mc", niveau: 2, frage: "Wozu dient ein **Leistungsverzeichnis** bei einer Ausschreibung?",
    optionen: ["Liste der beteiligten Mitarbeitenden", "Genaue Beschreibung der geforderten Leistung", "Aufstellung der bisherigen Rechnungen", "Übersicht der möglichen Bieter"], richtig: 1, abschnitt: "Make-or-buy und Ausschreibung",
    erklaerung: "Alle Anbieter kalkulieren dieselben **Positionen** → vergleichbare Angebote." },
  { id: "W6-14", modul: "W6", typ: "mc", niveau: 1, frage: "Was bedeutet die betriebswirtschaftliche Kenngröße **Effizienz** (im Unterschied zur Effektivität)?",
    optionen: ["die richtigen Dinge tun, um ein Ziel überhaupt zu erreichen (Wirksamkeit)", "eine vorgegebene Zielvorgabe mit möglichst geringem Ressourceneinsatz erreichen (Wirtschaftlichkeit)", "möglichst viele verschiedene Ziele gleichzeitig verfolgen", "Ziele vollständig unabhängig vom anfallenden Aufwand erreichen"], richtig: 1, abschnitt: "Betriebswirtschaftliche Kennzahlen",
    erklaerung: "Effizient = **wirtschaftlich**; effektiv = **wirksam** (Ziel erreicht)." },
  { id: "W6-15", modul: "W6", typ: "zahl", niveau: 2, frage: "Gewinn **30 000 €**, Eigenkapital **200 000 €**. Eigenkapitalrentabilität in %?", richtig: 15, toleranz: 0, einheit: "%", abschnitt: "Betriebswirtschaftliche Kennzahlen",
    erklaerung: "30 000 ÷ 200 000 × 100 = **15 %**." },
  { id: "W6-16", modul: "W6", typ: "zahl", niveau: 2, frage: "Ertrag **480 000 €**, Aufwand **400 000 €**. Wie hoch ist die **Wirtschaftlichkeit**? (2 Nachkommastellen)", richtig: 1.2, toleranz: 0.01, abschnitt: "Betriebswirtschaftliche Kennzahlen",
    erklaerung: "480 000 ÷ 400 000 = **1,20** – größer 1, also wirtschaftlich." },
  { id: "W6-17", modul: "W6", typ: "mc", niveau: 2, frage: "In welcher Phase des **Produktlebenszyklus** steigt der Umsatz stark und es entsteht meist erstmals Gewinn?",
    optionen: ["Einführung", "Wachstum", "Sättigung", "Rückgang"], richtig: 1, abschnitt: "Marketing",
    erklaerung: "In der **Wachstumsphase**." },
  { id: "W6-18", modul: "W6", typ: "mc", niveau: 2, frage: "Ein Systemhaus lässt seinen Telefonsupport von einem Dienstleister im Ausland erbringen. Wie nennt man das?",
    optionen: ["Insourcing", "Offshoring", "Make", "Pre-Sales"], richtig: 1, abschnitt: "Marketing",
    erklaerung: "Outsourcing = extern vergeben; **Offshoring** = zusätzlich ins Ausland." },
  { id: "W6-19", modul: "W6", typ: "mc", niveau: 1, frage: "Zu welchem Wirtschaftssektor gehört ein IT-Dienstleister?",
    optionen: ["primär", "sekundär", "tertiär", "keinem"], richtig: 2, abschnitt: "Markt und Bedarf",
    erklaerung: "**Tertiärer Sektor** = Dienstleistungen." },
  { id: "W6-20", modul: "W6", typ: "mc", niveau: 2, frage: "Ein Unternehmen macht Gewinn, kann aber seine Rechnungen nicht pünktlich bezahlen. Was fehlt?",
    optionen: ["Rentabilität", "Liquidität", "Produktivität", "Marktanteil"], richtig: 1, abschnitt: "Betriebswirtschaftliche Kennzahlen",
    erklaerung: "**Liquidität** = Zahlungsfähigkeit – z. B. wegen offener Kundenrechnungen." },

  // ---------------------------------------------------------------- P6
  { id: "P6-01", modul: "P6", typ: "mc", niveau: 1, frage: "In welcher Reihenfolge laufen die Teamphasen nach **Tuckman** ab?",
    optionen: ["Forming – Storming – Norming – Performing", "Storming – Forming – Performing – Norming", "Norming – Forming – Storming – Performing", "Performing – Norming – Storming – Forming"], richtig: 0, abschnitt: "Teamentwicklung nach Tuckman",
    erklaerung: "Orientierung → Konflikt → Regeln → Leistung (später ergänzt: Adjourning)." },
  { id: "P6-02", modul: "P6", typ: "mc", niveau: 2, frage: "Im Team gibt es Machtkämpfe und Streit über Zuständigkeiten. In welcher Phase ist es?",
    optionen: ["Forming", "Storming", "Norming", "Performing"], richtig: 1, abschnitt: "Teamentwicklung nach Tuckman",
    erklaerung: "**Storming** – normal; Konflikte offen klären und moderieren." },
  { id: "P6-03", modul: "P6", typ: "multi", niveau: 2, frage: "Was gehört in ein **Kick-off-Meeting**? (mehrere richtig)",
    optionen: ["Projektziele und Nutzen", "Rollen und Verantwortlichkeiten", "Zeitplan mit Meilensteinen", "Abnahmeprotokoll unterschreiben"], richtig: [0, 1, 2], abschnitt: "Kick-off-Meeting",
    erklaerung: "Die Abnahme folgt am **Ende** des Projekts." },
  { id: "P6-04", modul: "P6", typ: "mc", niveau: 2, frage: "Welches Prinzip gehört zum **Harvard-Konzept**?",
    optionen: ["auf der eigenen Position beharren", "Interessen statt Positionen betrachten", "Druck ausüben, um schnell zu einigen", "Differenzen immer genau halbieren"], richtig: 1, abschnitt: "Harvard-Konzept",
    erklaerung: "Fragen, **warum** jemand etwas will – so entstehen Win-win-Lösungen." },
  { id: "P6-05", modul: "P6", typ: "mc", niveau: 2, frage: "Was versteht man unter dem Begriff **BATNA** im Harvard-Konzept?",
    optionen: ["die beste verfügbare Alternative, falls keine Verhandlungseinigung zustande kommt (Best Alternative to a Negotiated Agreement)", "eine vertragliche Klausel zur Preisanpassung bei IT-Dienstleistungen", "die Maximalforderung, mit der eine Partei in die Verhandlung einsteigt", "die abschließende Phase eines Teamentwicklungsprozesses nach Tuckman"], richtig: 0, abschnitt: "Harvard-Konzept",
    erklaerung: "Best Alternative to a Negotiated Agreement – wer sie kennt, weiß, wann er ablehnen kann." },
  { id: "P6-06", modul: "P6", typ: "mc", niveau: 1, frage: "Welche Phasen hat das Veränderungsmodell nach **Lewin**?",
    optionen: ["Plan – Do – Check – Act", "Unfreeze – Change – Refreeze", "Forming – Storming – Norming", "Attention – Interest – Desire"], richtig: 1, abschnitt: "Veränderungen gestalten",
    erklaerung: "Auftauen – Verändern – Stabilisieren." },
  { id: "P6-07", modul: "P6", typ: "mc", niveau: 2, frage: "Eine Mitarbeiterin lehnt die neue Software ab, weil sie Angst hat, damit nicht zurechtzukommen. Welche Ursache und Maßnahme passen?",
    optionen: ["Nicht-Wissen – Informations-Rundmail", "Nicht-Können – Schulung und Ansprechpartner", "Nicht-Dürfen – zusätzliche Rechte vergeben", "Nicht-Wollen – Anweisung der Leitung"], richtig: 1, abschnitt: "Widerstände verstehen",
    erklaerung: "Die Ursache bestimmt die Maßnahme: **Nicht-Können** → qualifizieren." },
  { id: "P6-08", modul: "P6", typ: "mc", niveau: 2, frage: "Wie setzt man **Promotoren** im Veränderungsprozess am besten ein?",
    optionen: ["gar nicht, sie sind ohnehin überzeugt", "als Multiplikatoren, z. B. als Key User", "als Kontrolleure der Kritiker", "nur als Redner im Kick-off"], richtig: 1, abschnitt: "Widerstände verstehen",
    erklaerung: "Befürworter überzeugen Kolleginnen und Kollegen oft besser als die Projektleitung." },
  { id: "P6-09", modul: "P6", typ: "mc", niveau: 2, frage: "Ein neues Ticketsystem wertet die Bearbeitungszeit je Mitarbeiter aus. Wer muss vor der Einführung beteiligt werden?",
    optionen: ["nur die Datenschutzbeauftragte", "der Betriebsrat (Mitbestimmung)", "nur die betroffenen Kunden", "die zuständige IHK"], richtig: 1, abschnitt: "Widerstände verstehen",
    erklaerung: "§ 87 BetrVG: Mitbestimmung bei technischen Einrichtungen, die Verhalten oder Leistung überwachen können." },
  { id: "P6-10", modul: "P6", typ: "mc", niveau: 1, frage: "Was beschreibt die Entwicklungsmethode **Pair Programming**?",
    optionen: ["zwei Programme laufen parallel auf unterschiedlichen Servern", "zwei Entwickler arbeiten gemeinsam an einem Rechner mit regelmäßigem Rollenwechsel", "ein Entwickler arbeitet gleichzeitig an zwei Monitoren", "zwei getrennte Teams entwickeln dieselbe Funktion im Wettbewerb"], richtig: 1, abschnitt: "Teamentwicklung nach Tuckman",
    erklaerung: "Weniger Fehler, Wissen wird geteilt." },
  { id: "P6-11", modul: "P6", typ: "mc", niveau: 2, frage: "Was kennzeichnet eine positive **Fehlerkultur**?",
    optionen: ["Schuldige finden und bestrafen", "Fehler offen ansprechen und daraus lernen", "Fehler verschweigen", "nur Führungskräfte dürfen Fehler machen"], richtig: 1, abschnitt: "Teamentwicklung nach Tuckman",
    erklaerung: "Offenheit verhindert, dass Fehler vertuscht und wiederholt werden." },
  { id: "P6-12", modul: "P6", typ: "mc", niveau: 2, frage: "Warum sinkt die Leistung nach Einführung eines neuen Systems oft zunächst?",
    optionen: ["Das neue System ist fehlerhaft", "Normales Leistungstal durch Umstellung", "Mitarbeitende sabotieren die Einführung", "Die Hardware ist zu langsam"], richtig: 1, abschnitt: "Veränderungen gestalten",
    erklaerung: "Einplanen, unterstützen, Erfolge sichtbar machen." },
  { id: "P6-13", modul: "P6", typ: "mc", niveau: 2, frage: "Was zielt eine **Win-win-Lösung** an?",
    optionen: ["eine Seite setzt sich vollständig durch", "beide erreichen ihre wichtigsten Interessen", "beide geben die Hälfte ihrer Forderung auf", "die Entscheidung wird vertagt"], richtig: 1, abschnitt: "Harvard-Konzept",
    erklaerung: "Ergebnis des sachbezogenen Verhandelns." },
  { id: "P6-14", modul: "P6", typ: "mc", niveau: 1, frage: "In welcher Lewin-Phase wird das Neue zur Routine gemacht?",
    optionen: ["Unfreeze", "Change", "Refreeze", "Forming"], richtig: 2, abschnitt: "Veränderungen gestalten",
    erklaerung: "**Refreeze** – stabilisieren, dokumentieren, alte Wege abschalten." },
  { id: "P6-15", modul: "P6", typ: "mc", niveau: 2, frage: "Welches Beispiel entspricht **objektiven Kriterien** im Harvard-Konzept?",
    optionen: ["„Weil ich es so entschieden habe.“", "Marktpreise oder SLA-Messwerte", "Dauer der Geschäftsbeziehung", "Lautstärke der Argumentation"], richtig: 1, abschnitt: "Harvard-Konzept",
    erklaerung: "Neutrale Maßstäbe statt Machtkampf." },
  { id: "P6-16", modul: "P6", typ: "mc", niveau: 2, frage: "Wie gehen Sie mit einem **Skeptiker** um, der berechtigte Einwände gegen das Projekt vorbringt?",
    optionen: ["Einwände übergehen", "Ernst nehmen und zur Verbesserung nutzen", "aus dem Projektteam nehmen", "an die Geschäftsleitung melden"], richtig: 1, abschnitt: "Widerstände verstehen",
    erklaerung: "Skeptiker finden oft echte Schwachstellen." },
  { id: "P6-17", modul: "P6", typ: "mc", niveau: 1, frage: "In welcher Tuckman-Phase arbeitet das Team selbstorganisiert und effektiv?",
    optionen: ["Forming", "Storming", "Norming", "Performing"], richtig: 3, abschnitt: "Teamentwicklung nach Tuckman",
    erklaerung: "**Performing** – Freiraum lassen, Erfolge sichtbar machen." },
  { id: "P6-18", modul: "P6", typ: "mc", niveau: 2, frage: "Ein Mitarbeiter wusste nicht, warum das Papierarchiv abgeschafft wird. Welche Widerstandsursache liegt vor?",
    optionen: ["Nicht-Wissen", "Nicht-Können", "Nicht-Dürfen", "Nicht-Wollen"], richtig: 0, abschnitt: "Widerstände verstehen",
    erklaerung: "**Nicht-Wissen** → Gründe und Nutzen erklären." },
  { id: "P6-19", modul: "P6", typ: "mc", niveau: 2, frage: "Was sollte am Ende des Kick-off-Meetings vorliegen?",
    optionen: ["eine Liste der Teilnehmenden", "Protokoll mit Aufgaben und Terminen", "die Schlussrechnung", "das Abnahmeprotokoll"], richtig: 1, abschnitt: "Kick-off-Meeting",
    erklaerung: "Verbindlichkeit durch **dokumentierte Vereinbarungen**." },
  { id: "P6-20", modul: "P6", typ: "mc", niveau: 2, frage: "Was bedeutet „Menschen und Probleme getrennt behandeln“?",
    optionen: ["Probleme nur per E-Mail klären", "Sachlich bleiben, Person nicht angreifen", "Konfliktparteien räumlich trennen", "Nur noch schriftlich verhandeln"], richtig: 1, abschnitt: "Harvard-Konzept",
    erklaerung: "Kritik an der **Sache**, Respekt vor der **Person**." },

  // ---------------------------------------------------------------- Ergänzungen bestehender Module
  { id: "H1-21", modul: "H1", typ: "mc", niveau: 1, frage: "Was prüft der **POST** beim Einschalten eines PCs?",
    optionen: ["den Start des Betriebssystems", "CPU, RAM und Grafik (Grundhardware)", "die Internetverbindung", "die Benutzerrechte"], richtig: 1, abschnitt: "Bootvorgang",
    erklaerung: "Power-On Self-Test – Fehler als Pieptöne oder LED-Codes." },
  { id: "H1-22", modul: "H1", typ: "mc", niveau: 2, frage: "Welche Speicherart wird als **CPU-Cache** verwendet?",
    optionen: ["DRAM", "SRAM", "Flash", "ROM"], richtig: 1, abschnitt: "SRAM und DRAM",
    erklaerung: "**SRAM**: sehr schnell, kein Refresh, aber teuer." },
  { id: "H2-21", modul: "H2", typ: "mc", niveau: 1, frage: "Welcher Stecker verbindet typischerweise ein PC-Netzteil mit der Steckdose?",
    optionen: ["RJ45-Stecker", "Kaltgerätestecker (C13/C14)", "USB-C mit Power Delivery", "12VHPWR-Stecker"], richtig: 1, abschnitt: "Stromversorgung und Symbole",
    erklaerung: "Das Netzkabel mit **Kaltgerätestecker** geht in die Kaltgerätebuchse des Netzteils." },
  { id: "H2-22", modul: "H2", typ: "zahl", niveau: 2, frage: "Ein Ladegerät liefert **2,4 A** bei **5 V**. Wie viel **Watt** sind das?", richtig: 12, toleranz: 0, einheit: "W", abschnitt: "Stromversorgung und Symbole",
    erklaerung: "P = U · I = 5 × 2,4 = **12 W**." },
  { id: "H2-23", modul: "H2", typ: "mc", niveau: 2, frage: "Wozu dient **S.M.A.R.T.** bei Festplatten und SSDs?",
    optionen: ["Verschlüsselung des Datenträgers", "Selbstüberwachung mit Frühwarnung", "Beschleunigung des Bootvorgangs", "Aufteilung in Partitionen"], richtig: 1, abschnitt: "S.M.A.R.T.",
    erklaerung: "Werte wie defekte Sektoren, Temperatur und Verschleiß – ersetzt kein Backup." },
  { id: "H3-21", modul: "H3", typ: "mc", niveau: 1, frage: "Welches Bildformat ist **verlustfrei** und unterstützt **Transparenz**?",
    optionen: ["JPEG", "PNG", "MP3", "BMP"], richtig: 1, abschnitt: "Bildformate und Kompression",
    erklaerung: "**PNG** – ideal für Screenshots und Logos." },
  { id: "H3-22", modul: "H3", typ: "mc", niveau: 1, frage: "Welche Grafikart lässt sich **ohne Qualitätsverlust** beliebig vergrößern?",
    optionen: ["Rastergrafik", "Vektorgrafik", "JPEG-Foto", "GIF"], richtig: 1, abschnitt: "Raster- und Vektorgrafik",
    erklaerung: "**Vektorgrafik** (z. B. SVG) beschreibt Formen mathematisch." },
  { id: "H3-23", modul: "H3", typ: "zahl", niveau: 3, frage: "Berechnen Sie die Prüfziffer (13. Ziffer) eines EAN-13-Codes, dessen ersten 12 Ziffern `4 0 0 6 3 8 1 3 3 3 9 3` lauten (Gewichte abwechselnd 1 und 3, beginnend mit 1).", richtig: 1, toleranz: 0, abschnitt: "Prüfziffern",
    erklaerung: "Gewichtete Summe 89 → Ergänzung zur nächsten Zehnerzahl: **1**." },
  { id: "H3-24", modul: "H3", typ: "mc", niveau: 2, frage: "Welche Technik liest Etiketten **ohne Sichtkontakt** und mehrere gleichzeitig?",
    optionen: ["Barcode", "QR-Code", "RFID", "OCR"], richtig: 2, abschnitt: "Prüfziffern, Barcodes und RFID",
    erklaerung: "**RFID** funkt – ideal für Inventur und Logistik." },
  { id: "S4-21", modul: "S4", typ: "mc", niveau: 1, frage: "Mit welchem Linux-Befehl suchen Sie in einer Logdatei nach Zeilen mit „error“?",
    optionen: ["ls", "grep", "chmod", "cd"], richtig: 1, abschnitt: "Linux auf der Kommandozeile",
    erklaerung: "`grep error /var/log/syslog`." },
  { id: "S4-22", modul: "S4", typ: "mc", niveau: 1, frage: "Welcher Linux-Befehl zeigt die laufenden **Prozesse**?",
    optionen: ["ps aux", "pwd", "mkdir", "man"], richtig: 0, abschnitt: "Linux auf der Kommandozeile",
    erklaerung: "`ps aux` (live: `top`)." },
  { id: "S4-23", modul: "S4", typ: "mc", niveau: 2, frage: "Was unterscheidet einen **Thread** von einem Prozess?",
    optionen: ["Threads haben immer eigenen Speicher", "Threads teilen den Speicher ihres Prozesses", "Threads sind ausführbare Dateien", "Threads laufen nur auf einem Kern"], richtig: 1, abschnitt: "Prozesse, Threads",
    erklaerung: "Prozess = eigener Speicherbereich; Threads teilen ihn – leichtgewichtiger." },
  { id: "S4-24", modul: "S4", typ: "mc", niveau: 2, frage: "Ein PC findet die Domäne beim Beitritt nicht, obwohl er im Netz ist. Was prüfen Sie zuerst?",
    optionen: ["das Netzwerkkabel am Switch", "ob der Client-DNS auf den DC zeigt", "die Druckerwarteschlange", "die Windows-Firewall am Client"], richtig: 1, abschnitt: "PC in eine Domäne aufnehmen",
    erklaerung: "Die Domäne wird per **DNS** gefunden." },
  { id: "S4-25", modul: "S4", typ: "multi", niveau: 2, frage: "Welche Maßnahmen gehören zur **Härtung** eines Betriebssystems? (mehrere richtig)",
    optionen: ["nicht benötigte Dienste deaktivieren", "Standardpasswörter ändern", "Updates einspielen", "alle Ports öffnen"], richtig: [0, 1, 2], abschnitt: "Betriebssystem härten",
    erklaerung: "Härtung verkleinert die **Angriffsfläche**." },
  { id: "S8-21", modul: "S8", typ: "mc", niveau: 2, frage: "Welches BPMN-Symbol bedeutet, dass **alle** folgenden Wege parallel ausgeführt werden?",
    optionen: ["Raute mit X", "Raute mit +", "Kreis mit dickem Rand", "gestrichelter Pfeil"], richtig: 1, abschnitt: "Geschäftsprozesse mit BPMN",
    erklaerung: "**Paralleles Gateway (+)**; X = exklusiv (genau ein Weg)." },
  { id: "S8-22", modul: "S8", typ: "mc", niveau: 2, frage: "Wie wird in BPMN die Kommunikation **zwischen zwei Pools** dargestellt?",
    optionen: ["Sequenzfluss (durchgezogen)", "Nachrichtenfluss (gestrichelt)", "Assoziation (gepunktet)", "Gemeinsame Lane im selben Pool"], richtig: 1, abschnitt: "Geschäftsprozesse mit BPMN",
    erklaerung: "Sequenzfluss nur **innerhalb** eines Pools, Nachrichtenfluss zwischen Pools." },
  { id: "I5-22", modul: "I5", typ: "mc", niveau: 2, frage: "Ein Angreifer speichert JavaScript in einem Gästebucheintrag, das im Browser anderer Besucher ausgeführt wird. Welcher Angriff?",
    optionen: ["SQL-Injection", "Cross-Site Scripting (XSS)", "Cross-Site Request Forgery", "Phishing"], richtig: 1, abschnitt: "Weitere Angriffe",
    erklaerung: "**XSS** – Schutz: Ausgaben maskieren, Content Security Policy." },
  { id: "I5-23", modul: "I5", typ: "mc", niveau: 2, frage: "Was bedeutet **Security by Default**?",
    optionen: ["Sicherheit wird später per Update ergänzt", "Auslieferung mit sicheren Voreinstellungen", "Sicherheitsfunktionen sind optional", "Alle Dienste sind ab Werk aktiviert"], richtig: 1, abschnitt: "Weitere Angriffe",
    erklaerung: "Sichere Voreinstellungen – nur nötige Dienste, kein Standardpasswort." },
  { id: "I5-24", modul: "I5", typ: "mc", niveau: 2, frage: "Welche Maßnahme schützt Formulare gegen **CSRF**?",
    optionen: ["CSRF-Token im Formular", "längere Passwörter", "RAID", "größere Festplatte"], richtig: 0, abschnitt: "Weitere Angriffe",
    erklaerung: "Ein geheimes **Token** je Sitzung verhindert untergeschobene Anfragen (zusätzlich SameSite-Cookies)." },
  { id: "N4-24", modul: "N4", typ: "mc", niveau: 2, frage: "Ein neuer Switch hat noch keine IP-Adresse. Wie konfigurieren Sie ihn erstmals?",
    optionen: ["per SSH über das LAN", "über die serielle Konsole", "per Telnet über das LAN", "per HTTPS-Weboberfläche"], richtig: 1, abschnitt: "Fernzugriff und VPN",
    erklaerung: "Die **Konsole** braucht kein Netzwerk – ideal für die Erstkonfiguration." },
  { id: "N4-25", modul: "N4", typ: "mc", niveau: 1, frage: "Warum soll ein Server über **SSH** statt Telnet administriert werden?",
    optionen: ["SSH ist schneller als Telnet", "SSH verschlüsselt, Telnet nicht", "Telnet ist lizenzpflichtig", "SSH benötigt kein Netzwerk"], richtig: 1, abschnitt: "Fernzugriff und VPN",
    erklaerung: "Telnet (Port 23) ist unverschlüsselt – nicht mehr verwenden." },
  { id: "N4-26", modul: "N4", typ: "mc", niveau: 2, frage: "Welche VPN-Art verbindet zwei Firmenstandorte dauerhaft miteinander?",
    optionen: ["Client-to-Site", "Site-to-Site", "Peer-to-Peer", "Telnet"], richtig: 1, abschnitt: "Fernzugriff und VPN",
    erklaerung: "**Site-to-Site**, oft mit IPsec zwischen den Firewalls." },
  { id: "N1-22", modul: "N1", typ: "mc", niveau: 2, frage: "Welches Zugriffsverfahren kommt typischerweise in einem **WLAN nach IEEE 802.11** zum Einsatz?",
    optionen: ["CSMA/CD (Collision Detection)", "CSMA/CA (Collision Avoidance)", "Token Ring (Token-Passing)", "reines TDMA ohne Kollisionskontrolle"], richtig: 1, abschnitt: "Zugriffsverfahren",
    erklaerung: "**CSMA/CA** – Kollisionen vermeiden, weil Funkgeräte sie nicht sicher erkennen." },
  { id: "N1-23", modul: "N1", typ: "mc", niveau: 1, frage: "Welcher Nachteil gilt für ein **Peer-to-Peer-Netz** im Vergleich zu Client-Server?",
    optionen: ["Es sind teure Server nötig", "Rechte an jedem Rechner einzeln", "Dateifreigaben sind nicht möglich", "Es funktioniert nur per WLAN"], richtig: 1, abschnitt: "Zugriffsverfahren",
    erklaerung: "P2P nur für sehr kleine Netze; Client-Server verwaltet zentral." },
  { id: "I3-21", modul: "I3", typ: "mc", niveau: 2, frage: "Was versteht man unter einem **Cold Backup** (Offline-Backup)?",
    optionen: ["Eine Datensicherung im laufenden Betrieb der Datenbank", "Eine Datensicherung bei vollständig angehaltenen Diensten und Anwendungen", "Eine Sicherung auf Magnetbändern, die im Kühlraum gelagert werden", "Eine Archivierung in einer extrem kostengünstigen Cloud-Cold-Storage-Klasse"], richtig: 1, abschnitt: "Hot und Cold Backup",
    erklaerung: "Cold = offline, Hot = online im Betrieb." },
  { id: "S3-22", modul: "S3", typ: "mc", niveau: 2, frage: "Welcher Test prüft, wie sich eine Webanwendung mit **200 gleichzeitigen Nutzern** verhält?",
    optionen: ["Unit-Test", "Lasttest", "Black-Box-Test eines Formulars", "Schreibtischtest"], richtig: 1, abschnitt: "Weitere Testarten",
    erklaerung: "**Lasttest** unter erwarteter Last; Stresstest darüber hinaus." },
  { id: "S5-21", modul: "S5", typ: "mc", niveau: 2, frage: "Wofür steht das Cloud-Servicemodell **FaaS** (auch als Serverless Computing bezeichnet)?",
    optionen: ["Firewall as a Service", "Function as a Service", "File as a Service", "Framework as a Service"], richtig: 1, abschnitt: "Servicemodelle",
    erklaerung: "„Serverless“ – der Kunde sieht keine Server." },
]
