// Fragenpool Netzwerk (N1–N6)
// Typen: mc (richtig = Index), multi (richtig = [Indizes]), zahl (richtig = Zahl, toleranz optional), text (richtig = [Varianten])
[
  // ---------------------------------------------------------------- N1
  { id: "N1-01", modul: "N1", typ: "mc", niveau: 1, frage: "Auf welcher OSI-Schicht arbeitet ein klassischer **Switch**?",
    optionen: ["Schicht 1 – Bitübertragung", "Schicht 2 – Sicherung", "Schicht 3 – Vermittlung", "Schicht 4 – Transport"], richtig: 1,
    erklaerung: "Ein Switch leitet **Frames** anhand von **MAC-Adressen** weiter → Schicht 2. Layer-3-Switches können zusätzlich routen." },
  { id: "N1-02", modul: "N1", typ: "mc", niveau: 1, frage: "Wie heißt die Dateneinheit (PDU) auf **Schicht 3**?",
    optionen: ["Frame", "Segment", "Paket", "Bit"], richtig: 2,
    erklaerung: "Schicht 1 Bit · Schicht 2 Frame · **Schicht 3 Paket** · Schicht 4 Segment (TCP) bzw. Datagramm (UDP)." },
  { id: "N1-03", modul: "N1", typ: "multi", niveau: 2, frage: "Welche Dienste nutzen typischerweise **UDP**?",
    optionen: ["DNS-Abfragen", "VoIP-Sprachdaten", "HTTPS", "DHCP", "SSH"], richtig: [0, 1, 3],
    erklaerung: "UDP ist verbindungslos und schnell: **DNS**, **DHCP**, **VoIP**, Streaming, NTP. HTTPS und SSH brauchen die Zuverlässigkeit von TCP." },
  { id: "N1-04", modul: "N1", typ: "text", niveau: 2, frage: "Rechnen Sie die Hex-Bytes `c0 a8 01 fe` aus einem IP-Header in eine IP-Adresse um.",
    richtig: ["192.168.1.254"], erklaerung: "c0 = 12·16 = **192**, a8 = 10·16+8 = **168**, 01 = **1**, fe = 15·16+14 = **254**." },
  { id: "N1-05", modul: "N1", typ: "zahl", niveau: 2, frage: "Im TCP-Header steht der Zielport als `00 50`. Welcher Port ist das (dezimal)?",
    richtig: 80, toleranz: 0, erklaerung: "0x0050 = 5·16 = **80** → HTTP." },
  { id: "N1-06", modul: "N1", typ: "mc", niveau: 2, frage: "Ein Paket läuft von einem PC über zwei Router zu einem Webserver. Was ändert sich an jedem Router?",
    optionen: ["Die Quell- und Ziel-IP-Adresse", "Die Quell- und Ziel-MAC-Adresse", "Der Zielport", "Nichts, alle Adressen bleiben gleich"], richtig: 1,
    erklaerung: "MAC-Adressen gelten nur im jeweiligen Abschnitt und werden an jedem Router neu gesetzt. Die IP-Adressen bleiben Ende-zu-Ende gleich (Ausnahme: NAT)." },
  { id: "N1-07", modul: "N1", typ: "mc", niveau: 1, frage: "Welche Topologie ist in heutigen Ethernet-LANs üblich?",
    optionen: ["Bus (gemeinsames Kabel)", "Ring (Token Passing)", "Stern bzw. erweiterter Stern", "Vollvermascht (alle mit allen)"], richtig: 2,
    erklaerung: "Endgeräte hängen sternförmig an Switches, die Switches bilden eine Baumstruktur (Etagen-/Gebäudeverteiler)." },
  { id: "N1-08", modul: "N1", typ: "mc", niveau: 2, frage: "`ping 8.8.8.8` funktioniert, `ping www.beispiel.de` nicht. Wo liegt das Problem am wahrscheinlichsten?",
    optionen: ["Netzwerkkabel defekt", "Falsches Standardgateway", "Namensauflösung (DNS)", "Switchport deaktiviert"], richtig: 2,
    erklaerung: "Die IP-Verbindung ins Internet klappt – also sind Kabel, Gateway und Routing in Ordnung. Nur der Name wird nicht aufgelöst → **DNS**." },
  { id: "N1-09", modul: "N1", typ: "multi", niveau: 2, frage: "Welche Eigenschaften und Funktionen kennzeichnen das Transportprotokoll **TCP**?",
    optionen: ["baut eine Verbindung per 3-Way-Handshake auf", "garantiert die richtige Reihenfolge der Daten", "hat weniger Overhead als UDP", "bestätigt empfangene Daten (ACK)"], richtig: [0, 1, 3],
    erklaerung: "TCP ist verbindungsorientiert und zuverlässig – dafür hat es **mehr** Overhead als UDP." },
  { id: "N1-10", modul: "N1", typ: "mc", niveau: 1, frage: "Welchem OSI-Schichtbereich entspricht die **Anwendungsschicht des TCP/IP-Modells**?",
    optionen: ["nur Schicht 7", "Schichten 5 bis 7", "Schichten 4 bis 7", "Schichten 6 und 7"], richtig: 1,
    erklaerung: "TCP/IP fasst Sitzung, Darstellung und Anwendung (OSI 5–7) zur Anwendungsschicht zusammen." },
  { id: "N1-11", modul: "N1", typ: "zahl", niveau: 3, frage: "Das Feld **IHL** im IPv4-Header hat den Wert 5. Wie viele **Byte** ist der IP-Header lang?",
    richtig: 20, toleranz: 0, einheit: "Byte", erklaerung: "IHL zählt 32-Bit-Worte: 5 × 32 Bit = 160 Bit = **20 Byte**." },

  // ---------------------------------------------------------------- N2
  { id: "N2-01", modul: "N2", typ: "text", niveau: 1, frage: "Wie lautet die Subnetzmaske zum Präfix **/27**?",
    richtig: ["255.255.255.224"], erklaerung: "27 Einsen: 3 volle Oktette (24) + 3 Bit im 4. Oktett = 128+64+32 = **224**." },
  { id: "N2-02", modul: "N2", typ: "zahl", niveau: 1, frage: "Wie viele **nutzbare Hosts** hat ein /26-Netz?",
    richtig: 62, toleranz: 0, erklaerung: "32 − 26 = 6 Hostbits → 2⁶ − 2 = **62** (Netz- und Broadcastadresse abziehen)." },
  { id: "N2-03", modul: "N2", typ: "text", niveau: 2, frage: "Wie lautet die **Netzadresse** von `10.20.30.200/25`?",
    richtig: ["10.20.30.128"], erklaerung: "/25 → Blockgröße 128 → Netze .0 und .128. 200 ≥ 128 → **10.20.30.128**." },
  { id: "N2-04", modul: "N2", typ: "text", niveau: 2, frage: "Wie lautet die **Broadcastadresse** von `172.16.45.10/20`?",
    richtig: ["172.16.47.255"], erklaerung: "/20 → 255.255.240.0, Blockgröße im 3. Oktett 16 → Netz 172.16.32.0, nächstes 172.16.48.0 → Broadcast **172.16.47.255**." },
  { id: "N2-05", modul: "N2", typ: "mc", niveau: 1, frage: "Welche Adresse ist **keine** private IPv4-Adresse?",
    optionen: ["10.1.2.3", "172.20.0.1", "172.32.0.1", "192.168.100.1"], richtig: 2,
    erklaerung: "Der private Bereich 172.16.0.0/12 reicht nur bis **172.31.255.255**. 172.32.0.1 ist öffentlich." },
  { id: "N2-06", modul: "N2", typ: "mc", niveau: 1, frage: "Ein Windows-PC zeigt die Adresse `169.254.33.7`. Was bedeutet das?",
    optionen: ["Öffentliche IP vom Provider", "Keine DHCP-Antwort erhalten (APIPA)", "Verbindung über ein VPN", "Doppelt vergebene IP-Adresse"], richtig: 1,
    erklaerung: "169.254.0.0/16 = **APIPA/Link-Local** – selbst vergeben, weil kein DHCP-Server erreichbar war." },
  { id: "N2-07", modul: "N2", typ: "zahl", niveau: 2, frage: "Ein /24-Netz soll in **mindestens 5** gleich große Subnetze geteilt werden. Welches **Präfix** haben die Subnetze (so groß wie möglich)?",
    richtig: 27, toleranz: 0, erklaerung: "2² = 4 reicht nicht, 2³ = 8 ≥ 5 → 3 Subnetzbits → /24 + 3 = **/27**." },
  { id: "N2-08", modul: "N2", typ: "zahl", niveau: 2, frage: "Ein Netz soll **60 Hosts** aufnehmen und dabei möglichst wenige Adressen verschwenden. Welche **Präfixlänge** (z. B. /24 → 24) hat das kleinste dafür geeignete Netz?",
    richtig: 26, toleranz: 0, erklaerung: "2⁶ − 2 = 62 ≥ 60, 2⁵ − 2 = 30 reicht nicht → 6 Hostbits → **/26**." },
  { id: "N2-09", modul: "N2", typ: "mc", niveau: 2, frage: "PC A hat die IPv4-Adresse `192.168.5.70/26`, PC B hat `192.168.5.130/26`. In welchem logischen Verhältnis stehen die beiden Geräte zueinander?",
    optionen: ["Beide liegen im selben Netz", "Verschiedene Netze, Router nötig", "B ist eine Broadcastadresse", "A ist eine Netzadresse"], richtig: 1,
    erklaerung: "/26 → Blöcke 0, 64, 128, 192. A → Netz .64, B → Netz .128 → **verschiedene Netze**." },
  { id: "N2-10", modul: "N2", typ: "mc", niveau: 2, frage: "Warum sortiert man die Anforderungen bei der **VLSM-Planung** absteigend nach Größe?",
    optionen: ["Kleine Netze haben sonst keinen Broadcast", "Netze liegen so auf gültigen Blockgrenzen", "Router lernen große Netze zuerst", "Reine Konvention ohne technischen Grund"], richtig: 1,
    erklaerung: "Ein Netz muss auf einem Vielfachen seiner Blockgröße beginnen. Vergibt man zuerst die großen Blöcke, passen die kleinen lückenlos dahinter." },
  { id: "N2-11", modul: "N2", typ: "mc", niveau: 1, frage: "Welche Angabe braucht ein Client, um Geräte in **anderen** Netzen zu erreichen?",
    optionen: ["DNS-Server", "Standardgateway", "MAC-Adresse des Ziels", "Broadcastadresse"], richtig: 1,
    erklaerung: "Pakete an fremde Netze schickt der Client an das **Standardgateway** (Router). Der DNS-Server löst nur Namen auf." },
  { id: "N2-12", modul: "N2", typ: "zahl", niveau: 3, frage: "Wie viele /27-Subnetze passen in ein /22-Netz?",
    richtig: 32, toleranz: 0, erklaerung: "27 − 22 = 5 zusätzliche Bits → 2⁵ = **32** Subnetze." },
  { id: "N2-13", modul: "N2", typ: "multi", niveau: 3, frage: "Ein PC hat die Netzwerkkonfiguration `192.168.10.25/24` mit dem Standardgateway `192.168.1.1`. Welche der folgenden Aussagen zur Erreichbarkeit und Konfiguration treffen zu?",
    optionen: ["Der PC erreicht andere Geräte im Netz 192.168.10.0/24", "Der PC erreicht das Internet", "Das Gateway liegt nicht im eigenen Subnetz", "Die Subnetzmaske ist ungültig"], richtig: [0, 2],
    erklaerung: "Lokal klappt die Kommunikation. Das Gateway 192.168.1.1 liegt aber **nicht** in 192.168.10.0/24 → unerreichbar, kein Internet." },

  // ---------------------------------------------------------------- N3
  { id: "N3-01", modul: "N3", typ: "zahl", niveau: 1, frage: "Wie viele **Bit** hat eine IPv6-Adresse?",
    richtig: 128, toleranz: 0, erklaerung: "IPv6: **128 Bit** = 8 Blöcke à 16 Bit (IPv4: 32 Bit)." },
  { id: "N3-02", modul: "N3", typ: "text", niveau: 2, frage: "Kürzen Sie die folgende IPv6-Adresse regelkonform nach RFC 5952: `2001:0db8:0000:0000:0000:ff00:0042:8329`",
    richtig: ["2001:db8::ff00:42:8329"], erklaerung: "Führende Nullen weg → `2001:db8:0:0:0:ff00:42:8329`, dann die Null-Folge durch `::` → **2001:db8::ff00:42:8329**." },
  { id: "N3-03", modul: "N3", typ: "mc", niveau: 2, frage: "Welche Kurzform der IPv6-Adresse `fe80:0000:0000:0000:0a00:0000:0000:0001` ist nach **RFC 5952** korrekt gebildet?",
    optionen: ["fe80::a00:0:0:1", "fe80:0:0:0:a00::1", "fe80::a::1", "fe80::a00::1"], richtig: 0,
    erklaerung: "Die **längste** Null-Folge (3 Blöcke) wird gekürzt. `::` darf nur einmal vorkommen, und `0a00` wird zu `a00`, nicht zu `a`." },
  { id: "N3-04", modul: "N3", typ: "mc", niveau: 1, frage: "Welcher Adresstyp beginnt mit `fe80::/10`?",
    optionen: ["Global Unicast", "Link-Local", "Unique Local", "Multicast"], richtig: 1,
    erklaerung: "**Link-Local** – hat jede IPv6-Schnittstelle automatisch, wird nicht geroutet." },
  { id: "N3-05", modul: "N3", typ: "mc", niveau: 2, frage: "Welcher IPv6-Bereich entspricht am ehesten den privaten IPv4-Netzen (z. B. 192.168.0.0/16)?",
    optionen: ["2000::/3 (Global Unicast)", "fd00::/8 (Unique Local)", "ff00::/8 (Multicast)", "fe80::/10 (Link-Local)"], richtig: 1,
    erklaerung: "**ULA** (fc00::/7, praktisch fd00::/8) sind private, nicht im Internet geroutete Adressen." },
  { id: "N3-06", modul: "N3", typ: "mc", niveau: 1, frage: "Welche Aussage zu IPv6 ist **falsch**?",
    optionen: ["IPv6 kennt keinen Broadcast", "Ein LAN-Segment hat üblicherweise ein /64-Präfix", "IPv6 benötigt zwingend NAT", "Geräte können sich per SLAAC selbst konfigurieren"], richtig: 2,
    erklaerung: "Wegen des riesigen Adressraums ist **kein NAT nötig** – jedes Gerät kann eine globale Adresse haben (Firewall trotzdem Pflicht)." },
  { id: "N3-07", modul: "N3", typ: "zahl", niveau: 2, frage: "Ein Unternehmen erhält ein **/48**. Wie viele **/64**-Netze kann es daraus bilden?",
    richtig: 65536, toleranz: 0, erklaerung: "64 − 48 = 16 Bit → 2¹⁶ = **65 536** Subnetze." },
  { id: "N3-08", modul: "N3", typ: "text", niveau: 3, frage: "Bilden Sie die 64-Bit-Interface-ID nach dem EUI-64-Verfahren aus der MAC-Adresse `00:1a:2b:3c:4d:5e` (Format: `xxxx:xxxx:xxxx:xxxx`).",
    richtig: ["021a:2bff:fe3c:4d5e", "21a:2bff:fe3c:4d5e"], erklaerung: "MAC teilen, **ff:fe** einfügen, 7. Bit des ersten Bytes kippen: 00 → **02** → `021a:2bff:fe3c:4d5e`." },
  { id: "N3-09", modul: "N3", typ: "mc", niveau: 2, frage: "Wie erhält ein Host bei **SLAAC** sein Präfix?",
    optionen: ["Vom DHCPv6-Server", "Aus dem Router Advertisement", "Aus seiner MAC-Adresse", "Vom DNS-Server"], richtig: 1,
    erklaerung: "Der Router verkündet per **Router Advertisement** das Präfix; die Interface-ID bildet der Host selbst (EUI-64 oder zufällig)." },
  { id: "N3-10", modul: "N3", typ: "zahl", niveau: 1, frage: "Wie viele Bit stellt **eine Hex-Ziffer** dar?",
    richtig: 4, toleranz: 0, erklaerung: "Eine Hex-Ziffer = 0–15 = **4 Bit** (Nibble). Ein IPv6-Block mit 4 Ziffern = 16 Bit." },

  // ---------------------------------------------------------------- N4
  { id: "N4-01", modul: "N4", typ: "text", niveau: 1, frage: "Nennen Sie die vier Schritte des DHCP-Ablaufs in der richtigen Reihenfolge (Anfangsbuchstaben genügen).",
    richtig: ["DORA", "Discover Offer Request Acknowledge", "D O R A", "Discover, Offer, Request, Acknowledge"], erklaerung: "**D**iscover → **O**ffer → **R**equest → **A**cknowledge." },
  { id: "N4-02", modul: "N4", typ: "zahl", niveau: 1, frage: "Welchen Port nutzt **HTTPS** standardmäßig?", richtig: 443, toleranz: 0, erklaerung: "HTTPS = HTTP über TLS auf Port **443** (HTTP: 80)." },
  { id: "N4-03", modul: "N4", typ: "zahl", niveau: 1, frage: "Welchen TCP-Port nutzt der Dienst **SSH** (Secure Shell) standardmäßig?", richtig: 22, toleranz: 0, erklaerung: "SSH (und damit SFTP/SCP): Port **22**." },
  { id: "N4-04", modul: "N4", typ: "zahl", niveau: 2, frage: "Welchen Port nutzt **IMAPS** (IMAP über TLS)?", richtig: 993, toleranz: 0, erklaerung: "IMAP 143, **IMAPS 993**; POP3 110, POP3S 995." },
  { id: "N4-05", modul: "N4", typ: "text", niveau: 1, frage: "Welches Protokoll nutzt standardmäßig **Port 3389**?", richtig: ["RDP", "Remote Desktop", "Remotedesktop"], erklaerung: "**RDP** (Remote Desktop Protocol). Nie ungeschützt ins Internet freigeben – VPN davor!" },
  { id: "N4-06", modul: "N4", typ: "mc", niveau: 1, frage: "Welcher DNS-Record verweist auf den **Mailserver** einer Domain?", optionen: ["A", "CNAME", "MX", "PTR"], richtig: 2,
    erklaerung: "**MX** (Mail Exchanger) mit Priorität. A = IPv4, CNAME = Alias, PTR = Reverse Lookup." },
  { id: "N4-07", modul: "N4", typ: "mc", niveau: 2, frage: "Was unterscheidet **IMAP** von **POP3**?", optionen: ["IMAP versendet Mails, POP3 empfängt sie", "IMAP synchronisiert Mails mit dem Server, sie bleiben dort gespeichert", "POP3 ist immer verschlüsselt", "IMAP funktioniert nur im LAN"], richtig: 1,
    erklaerung: "IMAP synchronisiert (ideal für mehrere Geräte), POP3 lädt herunter. Versendet wird mit **SMTP**." },
  { id: "N4-08", modul: "N4", typ: "mc", niveau: 2, frage: "Welche primäre Aufgabe erfüllt das **ARP** (Address Resolution Protocol) im lokalen Netzwerk?", optionen: ["Domain-Namen in IP-Adressen auflösen", "Die zu einer IP-Adresse gehörende MAC-Adresse ermitteln", "IP-Adressen automatisch an Clients verteilen", "Private in öffentliche IP-Adressen übersetzen"], richtig: 1,
    erklaerung: "ARP: „Wer hat IP x?“ per Broadcast, Antwort mit der MAC. Namen → DNS, Vergabe → DHCP, Übersetzung → NAT." },
  { id: "N4-09", modul: "N4", typ: "mc", niveau: 2, frage: "Mehrere PCs mit privaten Adressen surfen über **eine** öffentliche IP. Wie unterscheidet der Router die Verbindungen?",
    optionen: ["Über die MAC-Adressen", "Über unterschiedliche Quellports (PAT)", "Über die TTL", "Gar nicht – nur ein PC kann gleichzeitig surfen"], richtig: 1,
    erklaerung: "**PAT/NAT-Overload**: Der Router ersetzt die Quell-IP und vergibt eindeutige Quellports, die er in einer Tabelle zuordnet." },
  { id: "N4-10", modul: "N4", typ: "multi", niveau: 2, frage: "Welche Informationen liefert ein DHCP-Server typischerweise?",
    optionen: ["IP-Adresse", "Subnetzmaske", "Standardgateway", "DNS-Server", "MAC-Adresse des Clients"], richtig: [0, 1, 2, 3],
    erklaerung: "Die MAC-Adresse hat der Client selbst – sie steht fest in der Netzwerkkarte." },
  { id: "N4-11", modul: "N4", typ: "mc", niveau: 2, frage: "Welches Protokoll wird zum **Senden** von E-Mails vom Mailprogramm an den eigenen Mailserver genutzt?",
    optionen: ["IMAP auf Port 143", "POP3 auf Port 110", "SMTP-Submission auf Port 587", "SNMP auf Port 161"], richtig: 2,
    erklaerung: "Clients liefern Mails per **SMTP Submission (587, STARTTLS)** oder SMTPS (465) ein. Server untereinander nutzen SMTP auf Port 25." },
  { id: "N4-12", modul: "N4", typ: "mc", niveau: 1, frage: "Welcher Befehl zeigt unter Windows IP-Adresse, Gateway, DNS-Server und MAC-Adresse an?",
    optionen: ["ping", "tracert", "ipconfig /all", "nslookup"], richtig: 2, erklaerung: "**ipconfig /all** zeigt die vollständige Konfiguration aller Adapter." },
  { id: "N4-13", modul: "N4", typ: "mc", niveau: 3, frage: "Ein Webserver im LAN (192.168.1.50) soll aus dem Internet erreichbar sein. Was muss am Internetrouter eingerichtet werden?",
    optionen: ["Eine DHCP-Reservierung für den Server", "Portweiterleitung 443 → 192.168.1.50", "Ein PTR-Eintrag im öffentlichen DNS", "Ein zusätzliches VLAN für den Server"], richtig: 1,
    erklaerung: "Wegen NAT sind interne Geräte von außen nicht direkt erreichbar – eine **Portweiterleitung** (besser: Server in eine DMZ) ist nötig." },

  // ---------------------------------------------------------------- N5
  { id: "N5-01", modul: "N5", typ: "zahl", niveau: 1, frage: "Wie viele Meter darf ein Kupfer-Ethernet-**Kanal** maximal lang sein?", richtig: 100, toleranz: 0, einheit: "m",
    erklaerung: "**100 m** = max. 90 m Verlegekabel (Permanent Link) + max. 10 m Patchkabel." },
  { id: "N5-02", modul: "N5", typ: "mc", niveau: 1, frage: "Welche Kabelkategorie ist Standard für eine Neuverkabelung, die **10 Gbit/s auf 100 m** schaffen soll?",
    optionen: ["Cat 5e", "Cat 6", "Cat 6A", "Cat 3"], richtig: 2, erklaerung: "**Cat 6A** (Klasse EA, 500 MHz). Cat 6 schafft 10 Gbit/s nur bis etwa 55 m." },
  { id: "N5-03", modul: "N5", typ: "mc", niveau: 2, frage: "Welcher Bereich der strukturierten Verkabelung verbindet **Gebäude** miteinander?",
    optionen: ["Primärbereich", "Sekundärbereich", "Tertiärbereich", "Arbeitsplatzbereich"], richtig: 0,
    erklaerung: "**Primär** = Campus (Gebäude ↔ Gebäude, meist Singlemode-LWL) · Sekundär = Steigbereich/Etagen · Tertiär = Etagenverteiler bis Dose." },
  { id: "N5-04", modul: "N5", typ: "zahl", niveau: 2, frage: "Am Kabelanfang liegen **10 V**, am Ende **5 V** an. Wie groß ist die Dämpfung in dB? (auf 2 Nachkommastellen)",
    richtig: 6.02, toleranz: 0.02, einheit: "dB", erklaerung: "Spannung → Faktor 20: a = 20 · log(10/5) = 20 · 0,301 = **6,02 dB**." },
  { id: "N5-05", modul: "N5", typ: "zahl", niveau: 2, frage: "Ein Sender hat **100 mW**. Wie groß ist der Pegel in **dBm**?", richtig: 20, toleranz: 0.01, einheit: "dBm",
    erklaerung: "dBm = 10 · log(100 mW / 1 mW) = 10 · 2 = **20 dBm**." },
  { id: "N5-06", modul: "N5", typ: "zahl", niveau: 2, frage: "An einer Netzwerkstrecke wird ein Nahnebensprechen von NEXT = **45 dB** und eine Dämpfung von **18 dB** gemessen. Wie hoch ist der **ACR** (Attenuation-to-Crosstalk Ratio) in **dB**?", richtig: 27, toleranz: 0.01, einheit: "dB",
    erklaerung: "ACR = NEXT − Dämpfung = 45 − 18 = **27 dB**. Je größer, desto besser." },
  { id: "N5-07", modul: "N5", typ: "mc", niveau: 1, frage: "Welches Gerät verbindet **verschiedene IP-Netze** und trennt Broadcast-Domänen?",
    optionen: ["Hub", "Switch", "Router", "Repeater"], richtig: 2, erklaerung: "Der **Router** (Schicht 3) leitet Pakete anhand von IP-Adressen zwischen Netzen weiter und reicht keine Broadcasts weiter." },
  { id: "N5-08", modul: "N5", typ: "mc", niveau: 2, frage: "Welcher Switchport transportiert **mehrere VLANs** mit 802.1Q-Tags?",
    optionen: ["Access-Port", "Trunk-Port", "Uplink ohne Konfiguration", "PoE-Port"], richtig: 1,
    erklaerung: "**Trunk-Ports** (z. B. zwischen Switches oder zu Access Points mit mehreren SSIDs) tragen getaggte Frames mehrerer VLANs." },
  { id: "N5-09", modul: "N5", typ: "zahl", niveau: 2, frage: "Welche Leistung stellt ein Switchport nach **IEEE 802.3at (PoE+)** maximal bereit?", richtig: 30, toleranz: 0, einheit: "W",
    erklaerung: "af: 15,4 W · **at: 30 W** · bt Typ 3: 60 W · bt Typ 4: 90 W (jeweils am Switchport)." },
  { id: "N5-10", modul: "N5", typ: "multi", niveau: 2, frage: "Welche Vorteile hat Glasfaser gegenüber Kupfer?",
    optionen: ["unempfindlich gegen elektromagnetische Störungen", "größere Reichweite", "günstiger zu konfektionieren", "keine Potenzialprobleme zwischen Gebäuden", "beliebig knickbar"], richtig: [0, 1, 3],
    erklaerung: "LWL ist störfest, reicht weit und trennt galvanisch. Es ist aber teurer in Verlegung/Spleißen und empfindlich gegen Knicken." },
  { id: "N5-11", modul: "N5", typ: "zahl", niveau: 3, frage: "Welche **Switching Capacity** (in Gbit/s) braucht ein nicht blockierender Switch mit 48 Ports à 1 Gbit/s (Vollduplex)?",
    richtig: 96, toleranz: 0, einheit: "Gbit/s", erklaerung: "48 × 1 Gbit/s × 2 (Vollduplex) = **96 Gbit/s**." },
  { id: "N5-12", modul: "N5", typ: "mc", niveau: 2, frage: "Was ist ein wesentlicher Vorteil von **VLANs**?",
    optionen: ["Mehr Bandbreite pro Kabel", "Logische Trennung ohne Extra-Hardware", "Ersatz für eine Firewall", "Kein Router mehr für die Netze nötig"], richtig: 1,
    erklaerung: "VLANs trennen logisch auf derselben Hardware. Zwischen VLANs braucht man weiterhin einen Router/Layer-3-Switch – dort filtert die Firewall." },

  // ---------------------------------------------------------------- N6
  { id: "N6-01", modul: "N6", typ: "mc", niveau: 1, frage: "Welche Wi-Fi-Generation entspricht **IEEE 802.11ax**?", optionen: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6 / 6E", "Wi-Fi 7"], richtig: 2,
    erklaerung: "n = Wi-Fi 4 · ac = Wi-Fi 5 · **ax = Wi-Fi 6 (6E mit 6 GHz)** · be = Wi-Fi 7." },
  { id: "N6-02", modul: "N6", typ: "mc", niveau: 2, frage: "In welchem Frequenzband arbeitet **802.11ac (Wi-Fi 5)**?", optionen: ["nur 2,4 GHz", "nur 5 GHz", "2,4 und 5 GHz", "2,4, 5 und 6 GHz"], richtig: 1,
    erklaerung: "802.11ac nutzt ausschließlich **5 GHz** (2,4-GHz-Geräte fallen auf 802.11n zurück)." },
  { id: "N6-03", modul: "N6", typ: "text", niveau: 2, frage: "Welche drei **überlappungsfreien** Kanäle nutzt man im 2,4-GHz-Band (20 MHz)? (z. B. 1, 2, 3)",
    richtig: ["1, 6, 11", "1 6 11", "1,6,11", "1/6/11"], erklaerung: "**1, 6 und 11** – benachbarte Access Points im Wechsel darauf legen." },
  { id: "N6-04", modul: "N6", typ: "multi", niveau: 2, frage: "Welche Aussagen zum 2,4-GHz-Band im Vergleich zu 5 GHz stimmen?",
    optionen: ["bessere Wanddurchdringung und Reichweite", "mehr überlappungsfreie Kanäle", "störanfälliger (Bluetooth, Mikrowelle, Nachbarnetze)", "höhere maximale Datenraten"], richtig: [0, 2],
    erklaerung: "2,4 GHz: weiter, aber nur 3 freie Kanäle und viele Störer. 5 GHz: mehr Kanäle und Tempo, geringere Reichweite." },
  { id: "N6-05", modul: "N6", typ: "mc", niveau: 1, frage: "Welches WLAN-Sicherheitsverfahren entspricht dem aktuellen Stand der Technik?", optionen: ["WEP", "WPA-TKIP", "WPA3", "offenes WLAN mit versteckter SSID"], richtig: 2,
    erklaerung: "**WPA3** (SAE) schützt u. a. gegen Offline-Wörterbuchangriffe. WEP und WPA gelten als gebrochen." },
  { id: "N6-06", modul: "N6", typ: "mc", niveau: 2, frage: "Welche Komponente prüft bei **WPA2/3-Enterprise (802.1X)** die Anmeldedaten?",
    optionen: ["Der Access Point selbst", "Ein RADIUS-Server", "Der DHCP-Server", "Der DNS-Server"], richtig: 1,
    erklaerung: "Supplicant (Client) → Authenticator (AP) → **RADIUS-Server** (oft mit Active Directory verbunden)." },
  { id: "N6-07", modul: "N6", typ: "multi", niveau: 2, frage: "Welche Maßnahmen gehören zu einem sicheren **Gäste-WLAN**?",
    optionen: ["eigenes VLAN mit Firewall-Regel „nur Internet“", "Client-Isolation", "gleiches Passwort wie das Firmen-WLAN", "Captive Portal/Voucher mit Nutzungsbedingungen", "SSID verstecken statt Verschlüsselung"], richtig: [0, 1, 3],
    erklaerung: "Netztrennung (VLAN + Firewall), Client-Isolation und Zugangssteuerung. Gemeinsame Passwörter und versteckte SSIDs sind keine Sicherheit." },
  { id: "N6-08", modul: "N6", typ: "zahl", niveau: 2, frage: "Ein AP sendet mit 14 dBm, die Antenne hat 5 dBi Gewinn, Kabelverlust 1 dB. Wie groß ist die **EIRP** in dBm?", richtig: 18, toleranz: 0.01, einheit: "dBm",
    erklaerung: "EIRP = 14 + 5 − 1 = **18 dBm** (≈ 63 mW, zulässig im 2,4-GHz-Band ≤ 20 dBm)." },
  { id: "N6-09", modul: "N6", typ: "mc", niveau: 2, frage: "Das WLAN hat vollen Empfang, ist aber sehr langsam. Nachbarfirmen haben viele WLANs. Welche Maßnahme ist am sinnvollsten?",
    optionen: ["Sendeleistung maximal erhöhen", "Freien Kanal oder 5-/6-GHz-Band wählen", "SSID verstecken", "WPA3 abschalten"], richtig: 1,
    erklaerung: "Das Problem ist Kanalüberlappung/Auslastung, nicht die Signalstärke. Freie Kanäle im 5-/6-GHz-Band helfen." },
  { id: "N6-10", modul: "N6", typ: "mc", niveau: 1, frage: "Wofür steht das IT-Sicherheits- und Organisationskonzept **BYOD**?",
    optionen: ["Backup Your Own Data", "Bring Your Own Device (Nutzung privater Geräte im Unternehmen)", "Build Your Own Domain", "Block Your Open Doors"], richtig: 1,
    erklaerung: "**Bring Your Own Device**: private Geräte dienstlich nutzen – braucht Nutzungsordnung, getrenntes Netz und ggf. MDM." },
]
