// Fragenpool Projekt & Service (P1–P5)
[
  // ---------------------------------------------------------------- P1
  { id: "P1-01", modul: "P1", typ: "mc", niveau: 1, frage: "Wer erstellt im klassischen Projektmanagement typischerweise das **Lastenheft**?", optionen: ["der Auftragnehmer", "der Auftraggeber", "der Projektleiter des Dienstleisters", "die zuständige Industrie- und Handelskammer"], richtig: 1,
    erklaerung: "Lastenheft = **Auftraggeber**, beschreibt WAS und WOFÜR. Pflichtenheft = Auftragnehmer, beschreibt WIE." },
  { id: "P1-02", modul: "P1", typ: "multi", niveau: 1, frage: "Welche Merkmale kennzeichnen ein **Projekt**?", optionen: ["Einmaligkeit", "zeitliche Begrenzung", "Routinetätigkeit", "klares Ziel", "begrenzte Ressourcen"], richtig: [0, 1, 3, 4],
    erklaerung: "Routinearbeit ist gerade **kein** Projekt." },
  { id: "P1-03", modul: "P1", typ: "mc", niveau: 1, frage: "Welche drei Größen bilden das **magische Dreieck** des Projektmanagements?", optionen: ["Zeit, Kosten, Leistung/Qualität", "Personal, Material, Maschinen", "Planung, Steuerung, Kontrolle", "Ziel, Weg, Ergebnis"], richtig: 0,
    erklaerung: "Ändert sich eine Größe, sind die anderen betroffen." },
  { id: "P1-04", modul: "P1", typ: "mc", niveau: 2, frage: "Welches Ziel ist **SMART** formuliert?", optionen: ["Das Netzwerk soll bis Ende des Jahres spürbar schneller werden.", "Bis 30.04. sind 25 Verwaltungs-PCs auf Windows 11 umgestellt.", "Wir verbessern die IT-Sicherheit im nächsten Quartal deutlich.", "Die Mitarbeitenden sollen mit der IT zufriedener werden."], richtig: 1,
    erklaerung: "Spezifisch, messbar, terminiert und realistisch." },
  { id: "P1-05", modul: "P1", typ: "mc", niveau: 2, frage: "Wer **priorisiert** in Scrum das Product Backlog?", optionen: ["Scrum Master", "Product Owner", "Developers", "Geschäftsführung"], richtig: 1,
    erklaerung: "Der **Product Owner** vertritt die Kundensicht. Der Scrum Master kümmert sich um den Prozess." },
  { id: "P1-06", modul: "P1", typ: "mc", niveau: 1, frage: "Wie lange dauert ein **Daily Scrum** höchstens?", optionen: ["5 Minuten", "15 Minuten", "1 Stunde", "einen halben Tag"], richtig: 1,
    erklaerung: "Tägliches kurzes Abstimmungstreffen von maximal **15 Minuten**." },
  { id: "P1-07", modul: "P1", typ: "mc", niveau: 2, frage: "Wann ist das **Wasserfallmodell** besonders geeignet?", optionen: ["bei unklaren, sich ändernden Anforderungen", "bei klaren, stabilen Anforderungen", "bei sehr kleinen Teams ohne Planung", "bei häufigem Kundenfeedback je Iteration"], richtig: 1,
    erklaerung: "Sequenzielle Phasen funktionieren gut, wenn früh feststeht, was gebaut werden soll." },
  { id: "P1-08", modul: "P1", typ: "mc", niveau: 1, frage: "Was kennzeichnet einen **Meilenstein** in der Ablauf- und Terminplanung eines Projekts?", optionen: ["Das zeitintensivste Arbeitspaket des gesamten Projekts", "Ein wichtiges Zwischenereignis ohne eigene Zeitdauer (Dauer = 0) zur Fortschrittskontrolle", "Die Pufferzeit am Ende einer Projektphase zur Risikominimierung", "Die formelle Freigabe des gesamten Projektbudgets durch das Management"], richtig: 1,
    erklaerung: "Meilensteine sind Prüfpunkte ohne eigene Dauer." },
  { id: "P1-09", modul: "P1", typ: "mc", niveau: 2, frage: "Wozu dient ein **Projektstrukturplan (PSP)**?", optionen: ["Zeitliche Abfolge der Vorgänge darstellen", "Projekt hierarchisch in Arbeitspakete zerlegen", "Projektkosten je Monat abrechnen", "Stakeholder nach Einfluss bewerten"], richtig: 1,
    erklaerung: "Der PSP zeigt **was** zu tun ist – die zeitliche Planung folgt im Gantt-Diagramm/Netzplan." },
  { id: "P1-10", modul: "P1", typ: "mc", niveau: 2, frage: "Was ist das wichtigste Dokument beim **Projektabschluss** gegenüber dem Kunden?", optionen: ["Lastenheft", "Abnahmeprotokoll", "Risikoanalyse", "Stakeholderliste"], richtig: 1,
    erklaerung: "Die **Abnahme** bestätigt die vertragsgemäße Leistung (wichtig beim Werkvertrag)." },
  { id: "P1-11", modul: "P1", typ: "multi", niveau: 2, frage: "Welche Aussagen zu **Scrum** stimmen?", optionen: ["Arbeit in kurzen Iterationen (Sprints)", "Nach jedem Sprint entsteht ein nutzbares Inkrement", "Der Scrum Master verteilt Aufgaben an die Entwickler", "Im Sprint Review wird das Ergebnis mit Stakeholdern besprochen"], richtig: [0, 1, 3],
    erklaerung: "Das Team organisiert sich selbst; der Scrum Master ist kein klassischer Chef." },

  // ---------------------------------------------------------------- P2
  { id: "P2-01", modul: "P2", typ: "mc", niveau: 1, frage: "Wie berechnet man in der Netzplantechnik (Vorwärtsrechnung) den **frühesten Endzeitpunkt (FEZ)** eines Vorgangs mit Dauer D?", optionen: ["FEZ = FAZ − D", "FEZ = FAZ + D", "FEZ = SEZ − D", "FEZ = SAZ + GP"], richtig: 1, erklaerung: "Frühestes Ende = frühester Anfang + Dauer." },
  { id: "P2-02", modul: "P2", typ: "mc", niveau: 2, frage: "Ein Vorgang hat die Vorgänger mit FEZ 5, 8 und 6. Wie groß ist sein **FAZ**?", optionen: ["5", "6", "8", "19"], richtig: 2,
    erklaerung: "Vorwärtsrechnung: **Maximum** der Vorgänger-FEZ – man muss auf den letzten warten." },
  { id: "P2-03", modul: "P2", typ: "mc", niveau: 2, frage: "Ein Vorgang hat Nachfolger mit SAZ 12, 10 und 15. Wie groß ist sein **SEZ**?", optionen: ["10", "12", "15", "37"], richtig: 0,
    erklaerung: "Rückwärtsrechnung: **Minimum** der Nachfolger-SAZ." },
  { id: "P2-04", modul: "P2", typ: "zahl", niveau: 1, frage: "Ein Vorgang im Netzplan hat einen frühesten Anfangszeitpunkt (FAZ) von 4 und einen spätesten Anfangszeitpunkt (SAZ) von 7. Wie groß ist sein **Gesamtpuffer (GP)**?", richtig: 3, toleranz: 0, erklaerung: "GP = SAZ − FAZ = 7 − 4 = **3**." },
  { id: "P2-05", modul: "P2", typ: "mc", niveau: 1, frage: "Was kennzeichnet den **kritischen Pfad**?", optionen: ["die Vorgänge mit der längsten Einzeldauer", "die Kette von Vorgängen mit Gesamtpuffer 0", "die teuersten Vorgänge", "alle Vorgänge ohne Vorgänger"], richtig: 1,
    erklaerung: "Jede Verzögerung auf dem kritischen Pfad verschiebt das Projektende." },
  { id: "P2-06", modul: "P2", typ: "mc", niveau: 2, frage: "Was gibt der **freie Puffer (FP)** eines Vorgangs in der Netzplantechnik an?", optionen: ["Die Zeitspanne, um die ein Vorgang maximal verschoben werden darf, ohne das Projektende zu gefährden", "Die Zeitspanne, um die ein Vorgang verschoben werden darf, ohne den frühesten Anfangszeitpunkt (FAZ) eines Nachfolgers zu verschieben", "Die reine Ausführungsdauer des betreffenden Vorgangs", "Die Wartezeit vom Projektstart bis zum Eintreffen der ersten Ressourcen"], richtig: 1,
    erklaerung: "FP = kleinster FAZ der Nachfolger − eigener FEZ. Der Gesamtpuffer bezieht sich auf das Projektende." },
  { id: "P2-07", modul: "P2", typ: "zahl", niveau: 2, frage: "Ein Projekt besteht aus vier Vorgängen: A (Dauer 3 Tage) ist Vorgänger von B (4 Tage) und C (6 Tage). Beide Vorgänge (B und C) müssen abgeschlossen sein, bevor D (2 Tage) starten kann. Wie viele Tage beträgt die Projektdauer?", richtig: 11, toleranz: 0, einheit: "Tage",
    erklaerung: "A 0–3, B 3–7, C 3–9, D beginnt bei max(7, 9) = 9 und endet bei **11**." },
  { id: "P2-08", modul: "P2", typ: "zahl", niveau: 2, frage: "In einem Netzplan verzweigt Vorgang A (3 Tage) auf B (4 Tage) und C (6 Tage); B und C münden beide in D (2 Tage). Wie groß ist der **Gesamtpuffer von B** in Tagen?", richtig: 2, toleranz: 0,
    erklaerung: "B: FAZ 3, SEZ = SAZ(D) = 9 → SAZ = 5 → GP = 5 − 3 = **2**." },
  { id: "P2-09", modul: "P2", typ: "mc", niveau: 2, frage: "Ein Vorgang auf dem kritischen Pfad verzögert sich um 2 Tage. Was passiert (ohne Gegenmaßnahmen)?", optionen: ["Der Puffer eines Nachbarvorgangs fängt es auf", "Das Projektende verschiebt sich um 2 Tage", "Nur der Nachfolger verschiebt sich", "Der Puffer wird negativ, das Ende bleibt"], richtig: 1,
    erklaerung: "Kritische Vorgänge haben keinen Puffer." },
  { id: "P2-10", modul: "P2", typ: "mc", niveau: 1, frage: "Welcher Vorteil hat ein **Gantt-Diagramm** gegenüber dem Netzplan?", optionen: ["zeigt Pufferzeiten und Abhängigkeiten exakter als der Netzplan", "anschauliche Darstellung der Termine auf einer Zeitachse", "zeigt den kritischen Pfad ohne jede Berechnung", "zeigt die Projektkosten je Vorgang"], richtig: 1,
    erklaerung: "Gantt = Balkenplan mit Zeitachse, gut für Kommunikation und Fortschrittskontrolle." },

  // ---------------------------------------------------------------- P3
  { id: "P3-01", modul: "P3", typ: "mc", niveau: 1, frage: "Was versteht man nach ITIL unter einem **Incident** im operativen IT-Service-Management?", optionen: ["eine geplante und autorisierte Änderung an der IT-Infrastruktur", "eine ungeplante Störung oder Qualitätsminderung eines IT-Services", "die zugrundeliegende Ursache mehrerer Störungen", "eine reguläre Standardanfrage wie die Neubestellung einer Tastatur"], richtig: 1,
    erklaerung: "Incident = Störung → Service möglichst schnell wiederherstellen (Workaround erlaubt)." },
  { id: "P3-02", modul: "P3", typ: "mc", niveau: 2, frage: "Mehrere Nutzer melden wöchentlich Abstürze derselben Anwendung. Worum sollte sich das Problem-Management kümmern?", optionen: ["jeden Absturz einzeln neu starten", "gemeinsame Ursache finden und beseitigen", "die Tickets gesammelt schließen", "ungeplant ein Update einspielen"], richtig: 1,
    erklaerung: "**Problem** = Ursache hinter wiederkehrenden Incidents." },
  { id: "P3-03", modul: "P3", typ: "mc", niveau: 1, frage: "Welcher Support-Level nimmt Anfragen an und löst Standardfälle?", optionen: ["1st Level", "2nd Level", "3rd Level", "Management"], richtig: 0,
    erklaerung: "Der **1st Level** (Service Desk) ist der Single Point of Contact." },
  { id: "P3-04", modul: "P3", typ: "mc", niveau: 2, frage: "Was ist eine **hierarchische Eskalation**?", optionen: ["Weitergabe an einen Spezialisten", "Einbeziehung von Vorgesetzten", "Weitergabe an den Hersteller", "Schließen des Tickets"], richtig: 1,
    erklaerung: "Funktional = mehr Fachwissen, hierarchisch = mehr Entscheidungsbefugnis." },
  { id: "P3-05", modul: "P3", typ: "zahl", niveau: 2, frage: "Ein SLA garantiert **99,9 %** Verfügbarkeit (24/7). Wie viele **Stunden** Ausfall sind pro Jahr maximal erlaubt?", richtig: 8.76, toleranz: 0.01, einheit: "h",
    erklaerung: "8 760 h × 0,001 = **8,76 h**." },
  { id: "P3-06", modul: "P3", typ: "mc", niveau: 1, frage: "Wie ergibt sich die **Priorität** eines Tickets typischerweise?", optionen: ["aus der Reihenfolge des Eingangs", "aus Auswirkung und Dringlichkeit", "aus der Position des Melders", "aus der geschätzten Bearbeitungsdauer"], richtig: 1,
    erklaerung: "Impact × Urgency – z. B. viele Nutzer betroffen und dringend → Prio 1." },
  { id: "P3-07", modul: "P3", typ: "mc", niveau: 2, frage: "Eisenhower-Matrix: Eine Aufgabe ist **wichtig, aber nicht dringend**. Was tun?", optionen: ["sofort selbst erledigen", "terminieren und selbst erledigen", "an andere delegieren", "nicht bearbeiten (Papierkorb)"], richtig: 1,
    erklaerung: "A = wichtig+dringend sofort, **B = wichtig, nicht dringend: terminieren**, C = dringend, nicht wichtig: delegieren, D = weglassen." },
  { id: "P3-08", modul: "P3", typ: "mc", niveau: 2, frage: "Welche Phase folgt im **PDCA-Zyklus** auf „Check“?", optionen: ["Plan", "Do", "Act", "Control"], richtig: 2,
    erklaerung: "Plan → Do → Check → **Act** (Standard einführen bzw. anpassen) → neuer Zyklus." },
  { id: "P3-09", modul: "P3", typ: "multi", niveau: 2, frage: "Was gehört typischerweise in ein **SLA**?", optionen: ["Servicezeiten", "Reaktions- und Wiederherstellungszeiten", "zugesicherte Verfügbarkeit", "Gehälter der Supportmitarbeitenden", "Vertragsstrafen bzw. Gutschriften bei Nichteinhaltung"], richtig: [0, 1, 2, 4],
    erklaerung: "Interne Gehälter sind kein Vertragsinhalt gegenüber dem Kunden." },
  { id: "P3-10", modul: "P3", typ: "zahl", niveau: 3, frage: "Ein System war in einem Monat (30 Tage, 24/7) insgesamt **6 Stunden** nicht verfügbar. Wie hoch war die Verfügbarkeit in % (2 Nachkommastellen)?", richtig: 99.17, toleranz: 0.01, einheit: "%",
    erklaerung: "(720 − 6) / 720 × 100 = **99,17 %**." },
  { id: "P3-11", modul: "P3", typ: "mc", niveau: 2, frage: "Welche Norm beschreibt **Qualitätsmanagementsysteme**?", optionen: ["ISO/IEC 27001", "ISO 9001", "DIN 66001", "IEEE 802.3"], richtig: 1,
    erklaerung: "**ISO 9001** – ISO 27001 ist Informationssicherheit, DIN 66001 PAP, 802.3 Ethernet." },

  // ---------------------------------------------------------------- P4
  { id: "P4-01", modul: "P4", typ: "multi", niveau: 1, frage: "Welche **vier Seiten** einer Nachricht unterscheidet Schulz von Thun?", optionen: ["Sachinhalt", "Selbstoffenbarung", "Beziehung", "Appell", "Lautstärke"], richtig: [0, 1, 2, 3],
    erklaerung: "Sachinhalt, Selbstoffenbarung, Beziehung, Appell." },
  { id: "P4-02", modul: "P4", typ: "mc", niveau: 2, frage: "Ein Supportkunde sagt verärgert: „Das habe ich Ihnen doch schon dreimal erklärt!“ Der Supporter fühlt sich persönlich angegriffen („Er hält mich wohl für inkompetent“). Auf welcher Seite der Nachricht nach Schulz von Thun hat der Supporter dies primär wahrgenommen?", optionen: ["Sachinhalt (Sachohr)", "Beziehungsseite (Beziehungsohr)", "Appellseite (Appellohr)", "Selbstoffenbarung (Selbstoffenbarungsohr)"], richtig: 1,
    erklaerung: "Der Supporter hört mit dem **Beziehungsohr** („Er hält mich für inkompetent“). Professionell: sachlich bleiben, Verständnis zeigen." },
  { id: "P4-03", modul: "P4", typ: "mc", niveau: 1, frage: "Welche der folgenden Formulierungen ist eine **offene Frage**?", optionen: ["Ist der PC eingeschaltet?", "Welche Programme nutzen Sie täglich bei Ihrer Arbeit?", "Möchten Sie Modell A oder lieber Modell B?", "Sie möchten doch sicher eine Garantieverlängerung, oder?"], richtig: 1,
    erklaerung: "W-Fragen lassen viele Antworten zu – ideal zur Bedarfsermittlung." },
  { id: "P4-04", modul: "P4", typ: "mc", niveau: 2, frage: "Welche Frageform sollte man im Beratungsgespräch **vermeiden**?", optionen: ["Kontrollfrage", "offene Frage", "Suggestivfrage", "Alternativfrage"], richtig: 2,
    erklaerung: "Suggestivfragen legen dem Kunden die Antwort in den Mund und wirken manipulativ." },
  { id: "P4-05", modul: "P4", typ: "mc", niveau: 2, frage: "Was beschreibt der **Fragetrichter**?", optionen: ["erst geschlossene, dann offene Fragen", "erst offene, dann geschlossene Fragen", "ausschließlich Alternativfragen", "Fragen nach Hierarchie ordnen"], richtig: 1,
    erklaerung: "Vom Weiten ins Konkrete." },
  { id: "P4-06", modul: "P4", typ: "mc", niveau: 1, frage: "Welche Formulierung ist eine **Ich-Botschaft**?", optionen: ["Sie haben das falsch installiert.", "Ich sehe eine Einstellung, die stören könnte.", "Das weiß doch eigentlich jeder.", "Warum haben Sie nicht gleich angerufen?"], richtig: 1,
    erklaerung: "Ich-Botschaften beschreiben die eigene Wahrnehmung, ohne Vorwurf." },
  { id: "P4-07", modul: "P4", typ: "mc", niveau: 2, frage: "In welcher Phase des Kundengesprächs stellt man vor allem **offene Fragen**?", optionen: ["Kontaktphase", "Bedarfsermittlung", "Abschlussphase", "Verabschiedung"], richtig: 1,
    erklaerung: "In der Erkundungsphase soll der Kunde möglichst viel erzählen." },
  { id: "P4-08", modul: "P4", typ: "mc", niveau: 2, frage: "Eine Mail soll an 40 externe Kunden gehen, die sich gegenseitig nicht kennen. Wohin gehören die Adressen?", optionen: ["An", "CC", "BCC", "Betreff"], richtig: 2,
    erklaerung: "**BCC** – sonst sieht jeder alle Adressen (Datenschutzverstoß)." },
  { id: "P4-09", modul: "P4", typ: "mc", niveau: 2, frage: "Wie reagiert man auf einen **verärgerten Kunden** am besten?", optionen: ["den Fehler beim Kunden suchen", "zuhören, Verständnis zeigen, Lösung anbieten", "das Gespräch höflich beenden", "mit Fachbegriffen Kompetenz zeigen"], richtig: 1,
    erklaerung: "Nicht persönlich nehmen, auf die Sachebene lenken, nachfassen." },
  { id: "P4-10", modul: "P4", typ: "mc", niveau: 2, frage: "Was ist eine **Nutzenargumentation**?", optionen: ["„Das Notebook hat 32 GB RAM.“", "„Mit 32 GB laufen Ihre VMs ohne Bremse.“", "„Das ist unser teuerstes Modell.“", "„Das empfehle ich eigentlich immer.“"], richtig: 1,
    erklaerung: "Merkmal + **Nutzen für den Kunden** („Sie können …“)." },

  // ---------------------------------------------------------------- P5
  { id: "P5-01", modul: "P5", typ: "mc", niveau: 1, frage: "Wie sollte ein Bildschirmarbeitsplatz in Bezug auf ein Fenster im Raum idealerweise ausgerichtet sein?", optionen: ["direkt mit dem Bildschirm zum Fenster", "mit dem Rücken zum Fenster (Lichteinfall von hinten)", "seitlich zum Fenster, sodass die Blickrichtung parallel zur Fensterfront verläuft", "schräg mit direktem Blick auf die Fensterscheibe"], richtig: 2,
    erklaerung: "So entstehen weder Blendung noch Spiegelungen." },
  { id: "P5-02", modul: "P5", typ: "zahl", niveau: 1, frage: "Welche Beleuchtungsstärke (Lux) sollte an einem Büroarbeitsplatz mindestens erreicht werden?", richtig: 500, toleranz: 0, einheit: "lx",
    erklaerung: "Richtwert **500 Lux** für Bildschirm- und Büroarbeit." },
  { id: "P5-03", modul: "P5", typ: "mc", niveau: 1, frage: "Welche Verordnung regelt die Anforderungen an **Bildschirmarbeitsplätze**?", optionen: ["Datenschutz-Grundverordnung", "Arbeitsstättenverordnung", "Elektro- und Elektronikgerätegesetz", "Berufsbildungsgesetz"], richtig: 1,
    erklaerung: "ArbStättV, **Anhang 6** (Bildschirmarbeit)." },
  { id: "P5-04", modul: "P5", typ: "mc", niveau: 2, frage: "Wo sollte sich die **Oberkante des Monitors** bei aufrechter Sitzhaltung ergonomisch befinden?", optionen: ["deutlich über Augenhöhe", "auf oder leicht unter Augenhöhe", "auf Tischhöhe", "egal, solange der Abstand stimmt"], richtig: 1,
    erklaerung: "Blick leicht nach unten entlastet Nacken und Augen." },
  { id: "P5-05", modul: "P5", typ: "mc", niveau: 2, frage: "Welcher Grundsatz der **Software-Ergonomie** ist verletzt, wenn eine Eingabe ohne Rückfrage unwiderruflich gelöscht wird?", optionen: ["Selbstbeschreibungsfähigkeit", "Robustheit gegen Benutzungsfehler", "Aufgabenangemessenheit", "Erlernbarkeit"], richtig: 1,
    erklaerung: "Fehlertolerante Software fragt nach bzw. bietet „Rückgängig“." },
  { id: "P5-06", modul: "P5", typ: "multi", niveau: 2, frage: "Wofür steht **POUR** in den WCAG?", optionen: ["Perceivable (wahrnehmbar)", "Operable (bedienbar)", "Understandable (verständlich)", "Robust", "Profitable"], richtig: [0, 1, 2, 3],
    erklaerung: "Wahrnehmbar, bedienbar, verständlich, robust." },
  { id: "P5-07", modul: "P5", typ: "mc", niveau: 2, frage: "Seit wann gilt das **Barrierefreiheitsstärkungsgesetz** für viele Produkte und Dienstleistungen?", optionen: ["25.05.2018", "01.01.2022", "28.06.2025", "es ist noch nicht in Kraft"], richtig: 2,
    erklaerung: "Das BFSG gilt seit dem **28.06.2025**." },
  { id: "P5-08", modul: "P5", typ: "mc", niveau: 1, frage: "Wie werden alte PCs richtig entsorgt?", optionen: ["im Hausmüll", "Rücknahme nach ElektroG, Daten vorher löschen", "im Altpapier", "mit Festplatte an Privatpersonen verschenken"], richtig: 1,
    erklaerung: "Elektroaltgeräte gehören nicht in den Hausmüll; Datenschutz verlangt sichere Löschung (DIN 66399)." },
  { id: "P5-09", modul: "P5", typ: "mc", niveau: 2, frage: "Was ist beim Tausch einer Grafikkarte im Desktop-PC aus Sicherheitsgründen zuerst zu tun?", optionen: ["PC im laufenden Betrieb öffnen", "Herunterfahren, Netzstecker ziehen und sich gegen elektrostatische Entladung (ESD) erden", "nur den Monitor ausschalten", "zuerst das BIOS zurücksetzen"], richtig: 1,
    erklaerung: "Elektrische Sicherheit und Schutz der Bauteile vor elektrostatischer Entladung." },
  { id: "P5-10", modul: "P5", typ: "mc", niveau: 2, frage: "Was regelt die **DGUV Vorschrift 3**?", optionen: ["Datenschutz im Betrieb", "Prüfung elektrischer Betriebsmittel", "Inhalte von Ausbildungsverträgen", "Nutzung von Softwarelizenzen"], richtig: 1,
    erklaerung: "Ortsveränderliche elektrische Geräte werden regelmäßig geprüft (Prüfplakette)." },
]
