// Fragenpool Software (S1–S8)
[
  // ---------------------------------------------------------------- S1
  { id: "S1-01", modul: "S1", typ: "text", niveau: 1, frage: "Wandeln Sie **173** (dezimal) in eine Binärzahl um (8 Bit).", richtig: ["10101101", "1010 1101"],
    erklaerung: "173 = 128 + 32 + 8 + 4 + 1 → **1010 1101**." },
  { id: "S1-02", modul: "S1", typ: "zahl", niveau: 1, frage: "Welchen Dezimalwert hat **0x7F**?", richtig: 127, toleranz: 0, erklaerung: "7·16 + 15 = **127**." },
  { id: "S1-03", modul: "S1", typ: "text", niveau: 2, frage: "Wandeln Sie **1110 0101₂** in eine Hexadezimalzahl um.", richtig: ["E5", "0xE5"], erklaerung: "1110 = E, 0101 = 5 → **E5**." },
  { id: "S1-04", modul: "S1", typ: "zahl", niveau: 2, frage: "Welche Linux-Rechte-Zahl (oktal) entspricht `rw-r-----`?", richtig: 640, toleranz: 0,
    erklaerung: "rw- = 4+2 = 6, r-- = 4, --- = 0 → **640**." },
  { id: "S1-05", modul: "S1", typ: "text", niveau: 2, frage: "Stellen Sie **−20** als 8-Bit-Zweierkomplement dar.", richtig: ["11101100", "1110 1100"],
    erklaerung: "20 = 0001 0100 → invertiert 1110 1011 → +1 = **1110 1100**." },
  { id: "S1-06", modul: "S1", typ: "mc", niveau: 1, frage: "Welcher Wertebereich gilt für eine **8-Bit-Ganzzahl mit Vorzeichen** (Zweierkomplement)?",
    optionen: ["0 bis 255", "−127 bis 127", "−128 bis 127", "−256 bis 255"], richtig: 2, erklaerung: "−2⁷ … 2⁷ − 1 = **−128 … 127**." },
  { id: "S1-07", modul: "S1", typ: "mc", niveau: 2, frage: "Welche Aussage zur Zeichenkodierung **UTF-8** ist zutreffend?",
    optionen: ["Jedes Zeichen belegt grundsätzlich genau 2 Byte", "Sie ist abwärtskompatibel zu 7-Bit-ASCII und kodiert Zeichen variabel mit 1 bis 4 Byte", "Deutsche Umlaute können in UTF-8 nicht dargestellt werden", "UTF-8 ist auf einen reinen 7-Bit-Zeichensatz begrenzt"], richtig: 1,
    erklaerung: "ASCII-Zeichen belegen 1 Byte, andere 2–4 Byte. UTF-8 kann den gesamten Unicode-Zeichensatz darstellen." },
  { id: "S1-08", modul: "S1", typ: "mc", niveau: 2, frage: "Eine Datei ohne Endung beginnt mit den Bytes `25 50 44 46`. Um welchen Dateityp handelt es sich?",
    optionen: ["ZIP", "PDF", "PNG", "EXE"], richtig: 1, erklaerung: "0x25 0x50 0x44 0x46 = ASCII **%PDF** – die Magic Number von PDF-Dateien." },
  { id: "S1-09", modul: "S1", typ: "zahl", niveau: 1, frage: "Wie viele Byte werden durch **zwei Hex-Ziffern** dargestellt?", richtig: 1, toleranz: 0,
    erklaerung: "Eine Hex-Ziffer = 4 Bit, zwei = 8 Bit = **1 Byte** (00–FF)." },
  { id: "S1-10", modul: "S1", typ: "text", niveau: 2, frage: "Berechnen Sie `1011 0110 XOR 0110 1100` (Ergebnis binär).", richtig: ["11011010", "1101 1010"],
    erklaerung: "XOR = 1, wenn die Bits verschieden sind → **1101 1010**." },
  { id: "S1-11", modul: "S1", typ: "zahl", niveau: 3, frage: "Welchen Dezimalwert hat das 8-Bit-Zweierkomplement **1000 0101**?", richtig: -123, toleranz: 0,
    erklaerung: "1000 0101 = 133 vorzeichenlos → 133 − 256 = **−123**." },

  // ---------------------------------------------------------------- S2
  { id: "S2-01", modul: "S2", typ: "mc", niveau: 1, frage: "Welcher Datentyp eignet sich für eine **Postleitzahl**?",
    optionen: ["Integer", "Float", "String", "Boolean"], richtig: 2, erklaerung: "**String** – führende Nullen (01067) müssen erhalten bleiben, und mit PLZ wird nicht gerechnet." },
  { id: "S2-02", modul: "S2", typ: "zahl", niveau: 1, frage: "Welches ganzzahlige Ergebnis liefert die Modulo-Operation `17 MOD 5` (Rest der Ganzzahldivision)?", richtig: 2, toleranz: 0, erklaerung: "17 = 3 · 5 + **2** → Rest 2." },
  { id: "S2-03", modul: "S2", typ: "zahl", niveau: 1, frage: "Welches ganzzahlige Ergebnis liefert die Ganzzahldivision `17 DIV 5` (ohne Rest)?", richtig: 3, toleranz: 0, erklaerung: "Ganzzahldivision: 17 / 5 = 3,4 → **3**." },
  { id: "S2-04", modul: "S2", typ: "mc", niveau: 2, frage: "Welche Schleife wird **mindestens einmal** durchlaufen?",
    optionen: ["Zählschleife (FÜR)", "kopfgesteuerte Schleife (SOLANGE)", "fußgesteuerte Schleife (WIEDERHOLE … BIS)", "jede Schleife mit Abbruchbedingung"], richtig: 2,
    erklaerung: "Bei der **fußgesteuerten** Schleife wird die Bedingung erst nach dem Rumpf geprüft." },
  { id: "S2-05", modul: "S2", typ: "zahl", niveau: 2, frage: "Welcher ganzzahlige Wert wird durch den folgenden Pseudocode-Ablauf ausgegeben?", code: "x ← 1\nFÜR i ← 1 BIS 4\n    x ← x * 2\nENDE FÜR\nausgabe(x)", richtig: 16, toleranz: 0,
    erklaerung: "Vier Verdopplungen: 1 → 2 → 4 → 8 → **16**." },
  { id: "S2-06", modul: "S2", typ: "mc", niveau: 2, frage: "Warum sollte man das Maximum einer Liste mit dem **ersten Element** und nicht mit 0 initialisieren?",
    optionen: ["Weil 0 kein gültiger Listenwert ist", "Bei nur negativen Werten käme 0 heraus", "Weil die Schleife sonst nicht startet", "Weil der Vergleich mit 0 langsamer ist"], richtig: 1,
    erklaerung: "Liste [−5, −2, −9]: Mit 0 initialisiert wäre das „Maximum“ 0, obwohl 0 gar nicht vorkommt." },
  { id: "S2-07", modul: "S2", typ: "mc", niveau: 2, frage: "Eine Liste hat 10 Elemente (Index ab 0). Welche Schleife durchläuft **alle** Elemente korrekt?",
    optionen: ["FÜR i ← 1 BIS 10", "FÜR i ← 0 BIS 10", "FÜR i ← 0 BIS 9", "FÜR i ← 1 BIS 9"], richtig: 2, erklaerung: "Indizes **0 bis n − 1** = 0 bis 9." },
  { id: "S2-08", modul: "S2", typ: "mc", niveau: 1, frage: "Welche Operation wird in gängigen Pseudocode-Notationen durch den Linkspfeil `←` dargestellt?",
    optionen: ["Logischer Wertevergleich", "Wertzuweisung an eine Variable", "Rückgabe aus einer Funktion", "Direkte Konsolenausgabe"], richtig: 1,
    erklaerung: "`x ← 5` weist x den Wert 5 zu. `=` ist im Pseudocode der Vergleich." },
  { id: "S2-09", modul: "S2", typ: "mc", niveau: 2, frage: "Welchen Wert hat `preis` bei `wert = 500`?", code: "WENN wert ≥ 100 DANN\n    preis ← wert * 0.95\nSONST WENN wert ≥ 500 DANN\n    preis ← wert * 0.90\nSONST\n    preis ← wert\nENDE WENN",
    optionen: ["450", "475", "500", "Fehler"], richtig: 1, erklaerung: "500 ≥ 100 ist wahr → erster Zweig: 500 × 0,95 = **475**. Der 10-%-Zweig wird nie erreicht (Logikfehler!)." },
  { id: "S2-10", modul: "S2", typ: "multi", niveau: 2, frage: "Welche Vorteile haben **Funktionen**?",
    optionen: ["Wiederverwendbarkeit", "bessere Übersicht durch Zerlegung (Dekomposition)", "einzeln testbar (Unit-Tests)", "Programme werden immer schneller"], richtig: [0, 1, 2],
    erklaerung: "Funktionen strukturieren Code; schneller wird er dadurch nicht automatisch." },
  { id: "S2-11", modul: "S2", typ: "mc", niveau: 2, frage: "Was ist ein **Objekt** in der Objektorientierung?",
    optionen: ["Ein Bauplan für Klassen", "Eine konkrete Instanz einer Klasse", "Eine Funktion ohne Rückgabewert", "Ein Datentyp für Zahlen"], richtig: 1,
    erklaerung: "Die **Klasse** ist der Bauplan, das **Objekt** eine konkrete Ausprägung davon." },

  // ---------------------------------------------------------------- S3
  { id: "S3-03", modul: "S3", typ: "mc", niveau: 1, frage: "Ein Programm läuft ohne Absturz, berechnet aber falsche Ergebnisse. Welche Fehlerart liegt vor?", optionen: ["Syntaxfehler", "Laufzeitfehler", "Logikfehler", "Compilerfehler"], richtig: 2,
    erklaerung: "**Logikfehler** – am schwersten zu finden, weil keine Fehlermeldung erscheint." },
  { id: "S3-04", modul: "S3", typ: "multi", niveau: 2, frage: "Rabatt gilt **ab 100 €**. Welche Testwerte sind für eine **Grenzwertanalyse** besonders wichtig?", optionen: ["99,99 €", "100,00 €", "50,00 €", "100,01 €", "1 000 000 €"], richtig: [0, 1, 3],
    erklaerung: "Genau auf der Grenze und direkt daneben – dort entstehen `<`/`≤`-Fehler." },
  { id: "S3-05", modul: "S3", typ: "mc", niveau: 2, frage: "Warum ist `a ← b` gefolgt von `b ← a` **kein** korrekter Tausch?", optionen: ["Weil b danach leer ist", "Weil danach beide Variablen den ursprünglichen Wert von b haben", "Weil Zuweisungen nicht hintereinander stehen dürfen", "Es ist korrekt"], richtig: 1,
    erklaerung: "Der alte Wert von a ist nach der ersten Zuweisung verloren → Hilfsvariable: `tmp ← a; a ← b; b ← tmp`." },
  { id: "S3-06", modul: "S3", typ: "mc", niveau: 2, frage: "Welche Voraussetzung hat die **binäre Suche**?", optionen: ["Die Daten müssen sortiert sein", "Die Liste muss eine Zweierpotenz lang sein", "Die Werte müssen ganze Zahlen sein", "Die Liste darf keine Duplikate enthalten"], richtig: 0,
    erklaerung: "Nur bei **sortierten** Daten kann man entscheiden, in welcher Hälfte weitergesucht wird." },
  { id: "S3-07", modul: "S3", typ: "zahl", niveau: 2, frage: "Wie viele Vergleiche braucht die binäre Suche höchstens (ungefähr) bei **1 024** sortierten Elementen?", richtig: 10, toleranz: 1,
    erklaerung: "log₂(1 024) = **10** (+1 je nach Zählweise)." },
  { id: "S3-08", modul: "S3", typ: "mc", niveau: 1, frage: "Welche Teststufe prüft **einzelne Funktionen** isoliert?", optionen: ["Abnahmetest", "Systemtest", "Unit-Test", "Integrationstest"], richtig: 2,
    erklaerung: "**Unit-Tests** (Modultests) bilden die breite Basis der Testpyramide." },
  { id: "S3-09", modul: "S3", typ: "mc", niveau: 2, frage: "Was versteht man in der Software-Qualitätssicherung unter einem **Regressionstest**?",
    optionen: ["Einen Testlauf mit rückwärts sortierten Eingabedaten", "Die wiederholte Durchführung bestehender Tests nach Codeänderungen zur Vermeidung von Seiteneffekten", "Einen reinen Last- und Performancetest unter Extrembedingungen", "Den allerersten Funktionstest eines neu geschriebenen Programmmoduls"], richtig: 1,
    erklaerung: "Regressionstests sichern ab, dass Änderungen nichts kaputtmachen – automatisiert besonders effektiv." },
  { id: "S3-10", modul: "S3", typ: "zahl", niveau: 3, frage: "Welchen ganzzahligen Wert gibt der folgende Algorithmus am Ende aus?", code: "liste ← [3, 9, 4, 12, 7]\nz ← 0\nFÜR i ← 0 BIS 4\n    WENN liste[i] MOD 3 = 0 DANN\n        z ← z + liste[i]\n    ENDE WENN\nENDE FÜR\nausgabe(z)", richtig: 24, toleranz: 0,
    erklaerung: "Durch 3 teilbar: 3, 9, 12 → 3 + 9 + 12 = **24**." },
  { id: "S3-11", modul: "S3", typ: "mc", niveau: 2, frage: "Womit werden im **UML-Aktivitätsdiagramm** Bedingungen an Verzweigungen notiert?", optionen: ["In runden Klammern am Knoten", "In eckigen Klammern, z. B. [alter < 14]", "Als Kommentar am Startknoten", "In geschweiften Klammern an der Aktion"], richtig: 1,
    erklaerung: "**Guards** in eckigen Klammern an den ausgehenden Kanten der Raute." },

  // ---------------------------------------------------------------- S4
  { id: "S4-01", modul: "S4", typ: "zahl", niveau: 1, frage: "Wie groß darf eine einzelne Datei auf **FAT32** höchstens sein (in GiB)?", richtig: 4, toleranz: 0, einheit: "GiB",
    erklaerung: "FAT32: max. **4 GiB** pro Datei. Für große Dateien exFAT oder NTFS." },
  { id: "S4-02", modul: "S4", typ: "mc", niveau: 1, frage: "Welches Partitionsschema ist für Laufwerke **größer als 2 TiB** nötig?", optionen: ["MBR", "GPT", "FAT", "NTFS"], richtig: 1,
    erklaerung: "**GPT** (mit UEFI). MBR ist auf 2 TiB und 4 primäre Partitionen begrenzt." },
  { id: "S4-03", modul: "S4", typ: "mc", niveau: 2, frage: "Freigaberecht „Lesen“, NTFS-Recht „Ändern“. Was darf der Benutzer **über das Netzwerk**?", optionen: ["Ändern", "Lesen", "Vollzugriff", "Lesen und Ausführen, aber nicht Auflisten"], richtig: 1,
    erklaerung: "Freigabe- und NTFS-Recht werden kombiniert – das **restriktivere** gilt → Lesen." },
  { id: "S4-04", modul: "S4", typ: "text", niveau: 2, frage: "Welche Rechte (als `rwx`-Schreibweise, 9 Zeichen) entsprechen `chmod 754`?", richtig: ["rwxr-xr--"],
    erklaerung: "7 = rwx, 5 = r-x, 4 = r-- → **rwxr-xr--**." },
  { id: "S4-05", modul: "S4", typ: "mc", niveau: 1, frage: "Was bedeutet das **Prinzip der minimalen Rechte** (Least Privilege)?", optionen: ["Administratoren erhalten keine Rechte", "Nur die für die Aufgabe nötigen Rechte", "Rechte werden jährlich reduziert", "Rechte werden nur an Gruppen vergeben"], richtig: 1,
    erklaerung: "Minimiert Schaden durch Fehler, Missbrauch und Schadsoftware." },
  { id: "S4-06", modul: "S4", typ: "mc", niveau: 2, frage: "Welche Windows-Edition kann **keiner Domäne** beitreten?", optionen: ["Home", "Pro", "Enterprise", "Education"], richtig: 0,
    erklaerung: "**Windows Home** fehlen Domänenbeitritt, Gruppenrichtlinien und BitLocker – im Unternehmen ungeeignet." },
  { id: "S4-07", modul: "S4", typ: "mc", niveau: 2, frage: "Vor welcher Art von Bedrohung schützt der UEFI-Sicherheitsmechanismus **Secure Boot** primär?",
    optionen: ["Vor thermischer Überhitzung beim Hochfahren", "Vor der Ausführung nicht signierter oder manipulierter Bootloader und Treiber", "Vor Datenverlust bei plötzlichem Stromausfall", "Vor Phishing-Angriffen beim Windows-Benutzerlogin"], richtig: 1,
    erklaerung: "UEFI prüft Signaturen der Bootkomponenten." },
  { id: "S4-08", modul: "S4", typ: "mc", niveau: 2, frage: "Welches Dateisystem ist für einen **USB-Stick** zum Austausch großer Videodateien zwischen Windows und macOS am besten geeignet?", optionen: ["FAT32", "exFAT", "ext4", "NTFS"], richtig: 1,
    erklaerung: "**exFAT**: keine 4-GiB-Grenze und von Windows und macOS lesbar/schreibbar." },
  { id: "S4-09", modul: "S4", typ: "multi", niveau: 2, frage: "Welche Schritte gehören zum Rollout eines neuen Arbeitsplatzes?", optionen: ["Treiber und Updates installieren", "Festplattenverschlüsselung aktivieren", "Übergabeprotokoll unterschreiben lassen", "Lokalen Administratorzugang für den Nutzer einrichten", "Inventarisierung"], richtig: [0, 1, 2, 4],
    erklaerung: "Nutzer arbeiten **ohne** Adminrechte (Least Privilege)." },
  { id: "S4-10", modul: "S4", typ: "mc", niveau: 1, frage: "Was bewirkt **Journaling** in einem Dateisystem?", optionen: ["Verschlüsselung der Dateien", "Konsistenz nach einem Absturz", "Komprimierung der Dateien", "Automatische Datensicherung"], richtig: 1,
    erklaerung: "Änderungen werden erst ins Journal geschrieben – nach einem Absturz kann das Dateisystem schnell konsistent gemacht werden." },

  // ---------------------------------------------------------------- S5
  { id: "S5-01", modul: "S5", typ: "mc", niveau: 1, frage: "Welcher Hypervisor ist ein **Typ-1-Hypervisor**?", optionen: ["VirtualBox", "VMware Workstation", "VMware ESXi", "Parallels Desktop"], richtig: 2,
    erklaerung: "**ESXi** läuft direkt auf der Hardware (bare metal). Die anderen laufen auf einem Wirtsbetriebssystem (Typ 2)." },
  { id: "S5-02", modul: "S5", typ: "mc", niveau: 1, frage: "Ein Unternehmen nutzt Webmail und Online-Office im Browser. Welches Cloudmodell ist das?", optionen: ["IaaS", "PaaS", "SaaS", "On-Premises"], richtig: 2,
    erklaerung: "**Software as a Service** – der Anbieter betreibt alles, der Kunde nutzt die Anwendung." },
  { id: "S5-03", modul: "S5", typ: "mc", niveau: 2, frage: "Ein Unternehmen mietet virtuelle Server und installiert Betriebssystem und Software selbst. Welches Modell?", optionen: ["IaaS", "PaaS", "SaaS", "Private Cloud"], richtig: 0,
    erklaerung: "**IaaS**: Der Anbieter stellt Infrastruktur, der Kunde verwaltet ab dem Betriebssystem." },
  { id: "S5-04", modul: "S5", typ: "multi", niveau: 2, frage: "Welche Aussagen zur **Servervirtualisierung** stimmen?", optionen: ["bessere Hardwareauslastung", "Snapshots ersetzen das Backup", "ohne Cluster ist der Host ein Single Point of Failure", "VMs lassen sich schnell aus Vorlagen bereitstellen"], richtig: [0, 2, 3],
    erklaerung: "Snapshots liegen auf demselben Speicher und ersetzen **kein** Backup." },
  { id: "S5-05", modul: "S5", typ: "mc", niveau: 2, frage: "Was unterscheidet **Container** von VMs?", optionen: ["Container haben ein eigenes Betriebssystem", "Container teilen sich den Kernel des Hosts", "Container brauchen einen Typ-1-Hypervisor", "Container sind stets stärker isoliert"], richtig: 1,
    erklaerung: "Container virtualisieren auf Betriebssystemebene – schneller Start, wenig Overhead, aber schwächere Isolation." },
  { id: "S5-06", modul: "S5", typ: "multi", niveau: 2, frage: "Was sollte bei der Auswahl eines Cloud-Anbieters aus **Datenschutzsicht** geprüft werden?", optionen: ["Serverstandort", "Auftragsverarbeitungsvertrag (AVV)", "Anzahl der Rechenzentren weltweit", "Verschlüsselung und Zertifizierungen (ISO 27001, C5)", "Exit-Strategie"], richtig: [0, 1, 3, 4],
    erklaerung: "Standort, AVV nach Art. 28 DSGVO, Verschlüsselung/Zertifikate und die Möglichkeit, Daten zurückzubekommen." },
  { id: "S5-07", modul: "S5", typ: "mc", niveau: 2, frage: "Was bezeichnet man als **VDI** (Virtual Desktop Infrastructure)?",
    optionen: ["Einen Virenscanner für virtuelle Maschinen", "Die zentrale Bereitstellung virtueller Arbeitsplatz-Desktops auf Servern im Rechenzentrum", "Ein proprietäres Dateisystem für virtuelle Datenträger", "Einen verschlüsselten Cloud-Speicher für Anwenderdokumente"], richtig: 1,
    erklaerung: "**Virtual Desktop Infrastructure**: jeder Nutzer erhält eine eigene Desktop-VM." },
  { id: "S5-08", modul: "S5", typ: "mc", niveau: 1, frage: "Welcher Vorteil ist typisch für die **Public Cloud**?", optionen: ["volle Kontrolle über die Hardware", "schnell skalierbar ohne hohe Investition", "keine Internetverbindung erforderlich", "keine Datenschutzfragen zu klären"], richtig: 1,
    erklaerung: "Ressourcen werden bedarfsgerecht gemietet (Pay per Use)." },
  { id: "S5-09", modul: "S5", typ: "mc", niveau: 2, frage: "Welches Bereitstellungsmodell kombiniert eigene Infrastruktur mit Diensten aus der Public Cloud?", optionen: ["Community Cloud", "Private Cloud", "Hybrid Cloud", "Edge"], richtig: 2,
    erklaerung: "**Hybrid Cloud** – z. B. sensible Daten intern, skalierende Dienste in der Public Cloud." },
  { id: "S5-10", modul: "S5", typ: "mc", niveau: 3, frage: "Was ermöglicht die Virtualisierungsfunktion **Live-Migration** (z. B. vMotion)?",
    optionen: ["Das Verschieben laufender VMs unterbrechungsfrei zwischen physischen Hosts", "Das automatische Virtualisieren physischer Server im Betrieb", "Die direkte Umwandlung von Containern in vollwertige VMs", "Das automatische Löschen veralteter VM-Snapshots"], richtig: 0,
    erklaerung: "Wartung eines Hosts ohne Ausfall der VMs (gemeinsamer Speicher im Cluster nötig)." },

  // ---------------------------------------------------------------- S6
  { id: "S6-01", modul: "S6", typ: "mc", niveau: 1, frage: "Welche Vertragsart liegt der Entwicklung von **Individualsoftware** meist zugrunde?", optionen: ["Kaufvertrag", "Mietvertrag", "Werkvertrag", "Dienstvertrag"], richtig: 2,
    erklaerung: "Geschuldet wird ein **Erfolg** (funktionierende Software) → Werkvertrag, Grundlage Pflichtenheft." },
  { id: "S6-02", modul: "S6", typ: "mc", niveau: 2, frage: "30 Mitarbeitende im Schichtbetrieb, höchstens 8 nutzen eine Software gleichzeitig. Welches Lizenzmodell ist meist am günstigsten?", optionen: ["Named User", "Concurrent User (Floating)", "OEM", "Device-Lizenz je PC"], richtig: 1,
    erklaerung: "**Concurrent** zählt gleichzeitige Nutzer – 8 (plus Reserve) statt 30 Lizenzen." },
  { id: "S6-03", modul: "S6", typ: "mc", niveau: 1, frage: "Was versteht man unter einer **OEM-Lizenz**?",
    optionen: ["Eine freie Lizenz für Open-Source-Software", "Eine vergünstigte Softwarelizenz, die an bestimmte Hardware gekoppelt verkauft wird", "Eine unbegrenzte Volumenlizenz für Großkonzerne", "Eine zeitlich befristete Testlizenz für Entwicklungsumgebungen"], richtig: 1,
    erklaerung: "OEM = Original Equipment Manufacturer – günstig, aber gerätegebunden." },
  { id: "S6-04", modul: "S6", typ: "mc", niveau: 2, frage: "Was bedeutet **Copyleft** (z. B. GPL)?", optionen: ["Die Software darf nicht verändert werden", "Veränderte Versionen unter gleicher Lizenz", "Die Software ist nur privat nutzbar", "Der Quellcode bleibt geheim"], richtig: 1,
    erklaerung: "Die Freiheiten der Lizenz werden an alle Weiterentwicklungen „vererbt“." },
  { id: "S6-05", modul: "S6", typ: "mc", niveau: 2, frage: "Ein Mitarbeiter installiert eine „Freeware“ im Büro. Was ist zu prüfen?", optionen: ["Nichts, Freeware ist immer frei nutzbar", "Ob die Lizenz auch die gewerbliche Nutzung erlaubt", "Ob sie Open Source ist", "Ob sie mehr als 100 MB hat"], richtig: 1,
    erklaerung: "Viele Freeware-Lizenzen erlauben nur **private** Nutzung – gewerblicher Einsatz wäre ein Lizenzverstoß." },
  { id: "S6-06", modul: "S6", typ: "multi", niveau: 2, frage: "Welche Risiken entstehen durch **Unterlizenzierung**?", optionen: ["Nachzahlungen und Schadensersatz nach einem Audit", "Imageschaden", "Rechtsverstoß gegen das Urheberrecht", "Die Software läuft schneller"], richtig: [0, 1, 2],
    erklaerung: "Ohne ausreichende Lizenzen nutzt man Software unberechtigt." },
  { id: "S6-07", modul: "S6", typ: "mc", niveau: 1, frage: "Welcher Vorteil gilt für **Standardsoftware**?", optionen: ["exakt an eigene Prozesse angepasst", "sofort verfügbar und erprobt", "keine Lizenzkosten", "keine Updates nötig"], richtig: 1,
    erklaerung: "Standardsoftware ist sofort einsetzbar, günstiger und von vielen Nutzern erprobt." },
  { id: "S6-08", modul: "S6", typ: "mc", niveau: 2, frage: "Worum handelt es sich bei einer **CAL** (Client Access License)?",
    optionen: ["Eine Lizenz, die Clients den Zugriff auf Serverdienste gestattet", "Eine zeitbasierte Mietlizenz für einen Cloud-Dienst", "Den Lizenzschlüssel zur Aktivierung eines Office-Pakets", "Ein Zertifikat zur Verlängerung der Herstellerhardwaregarantie"], richtig: 0,
    erklaerung: "**Client Access License**, z. B. für Windows Server oder Exchange." },
  { id: "S6-09", modul: "S6", typ: "mc", niveau: 2, frage: "Welche Open-Source-Lizenz ist **permissiv** (darf in proprietäre Software eingebaut werden)?", optionen: ["GPL v3", "MIT", "AGPL", "LGPL mit statischer Einbindung"], richtig: 1,
    erklaerung: "MIT, Apache 2.0 und BSD verlangen nur den Lizenzhinweis." },
  { id: "S6-10", modul: "S6", typ: "zahl", niveau: 2, frage: "Eine Named-User-Lizenz kostet 1 200 €/Jahr, eine Concurrent-Lizenz 3 000 €/Jahr. Es gibt 25 Nutzer, höchstens 9 arbeiten gleichzeitig. Wie viel € spart das günstigere Modell pro Jahr?", richtig: 3000, toleranz: 0, einheit: "€",
    erklaerung: "Named: 25 × 1 200 = 30 000 € · Concurrent: 9 × 3 000 = 27 000 € → Ersparnis **3 000 €**." },
  // ---------------------------------------------------------------- S7
  { id: "S7-01", modul: "S7", typ: "mc", niveau: 1, frage: "Welches Symbol steht im ER-Modell (Chen) für einen **Beziehungstyp**?",
    optionen: ["Rechteck", "Ellipse", "Raute", "Kreis"], richtig: 2, abschnitt: "Das ER-Modell",
    erklaerung: "Rechteck = Entitätstyp, Ellipse = Attribut, **Raute = Beziehung**." },
  { id: "S7-02", modul: "S7", typ: "mc", niveau: 2, frage: "Ein Kunde kann mehrere Verträge haben, jeder Vertrag gehört zu genau einem Kunden. Welche Kardinalität liegt vor?",
    optionen: ["1:1", "1:n", "n:m", "0:1"], richtig: 1, abschnitt: "Kardinalitäten",
    erklaerung: "Beide Richtungen lesen: ein Kunde → n Verträge, ein Vertrag → 1 Kunde → **1:n**." },
  { id: "S7-03", modul: "S7", typ: "mc", niveau: 2, frage: "Mitarbeiter besuchen Schulungen; eine Schulung hat viele Teilnehmer. Wie setzen Sie das in Tabellen um?",
    optionen: ["Fremdschlüssel schulung_id in die Tabelle mitarbeiter", "Fremdschlüssel mitarbeiter_id in die Tabelle schulung", "eigene Zwischentabelle mit beiden Fremdschlüsseln", "beide Tabellen zusammenlegen"], richtig: 2, abschnitt: "Vom ER-Modell zu Tabellen",
    erklaerung: "n:m-Beziehungen brauchen eine **Zwischentabelle** (z. B. teilnahme) mit mitarbeiter_id und schulung_id." },
  { id: "S7-04", modul: "S7", typ: "mc", niveau: 2, frage: "In welche Tabelle gehört bei einer **1:n**-Beziehung Kunde – Auftrag der Fremdschlüssel?",
    optionen: ["in kunde", "in auftrag", "in beide", "in eine Zwischentabelle"], richtig: 1, abschnitt: "Vom ER-Modell zu Tabellen",
    erklaerung: "Der Fremdschlüssel kommt auf die **n-Seite**: auftrag.kunden_nr verweist auf kunde.kunden_nr." },
  { id: "S7-05", modul: "S7", typ: "mc", niveau: 1, frage: "Was zeichnet einen **Primärschlüssel** aus?",
    optionen: ["Er verweist auf eine andere Tabelle", "Eindeutig je Zeile und nicht leer", "Er ist immer der Name des Datensatzes", "Er darf mehrfach vorkommen"], richtig: 1, abschnitt: "Vom ER-Modell zu Tabellen",
    erklaerung: "Der PK ist **eindeutig und nicht leer**. Der Verweis auf eine andere Tabelle ist ein Fremdschlüssel." },
  { id: "S7-06", modul: "S7", typ: "mc", niveau: 2, frage: "Ein Kunde zieht um, seine Adresse steht in 40 Auftragszeilen. Eine Zeile wird vergessen. Wie heißt dieses Problem?",
    optionen: ["Einfügeanomalie", "Löschanomalie", "Änderungsanomalie", "Deadlock"], richtig: 2, abschnitt: "Redundanz, Anomalien und Normalisierung",
    erklaerung: "Redundante Daten führen zur **Änderungsanomalie** – die Daten widersprechen sich." },
  { id: "S7-07", modul: "S7", typ: "mc", niveau: 2, frage: "Wohin gehört das Attribut **Menge** bei der n:m-Beziehung Auftrag – Artikel?",
    optionen: ["zum Auftrag", "zum Artikel", "in die Zwischentabelle", "in eine eigene Tabelle Menge"], richtig: 2, abschnitt: "Kardinalitäten",
    erklaerung: "Die Menge beschreibt „dieser Artikel in diesem Auftrag“ – ein **Beziehungsattribut**." },
  { id: "S7-10", modul: "S7", typ: "multi", niveau: 2, frage: "Welche Aufgaben übernimmt ein **DBMS**? (mehrere richtig)",
    optionen: ["Mehrbenutzerbetrieb mit Transaktionen", "Zugriffsrechte verwalten", "Datenintegrität sichern", "das Betriebssystem booten"], richtig: [0, 1, 2], abschnitt: "Datenbank und DBMS",
    erklaerung: "DBMS: Integrität, Mehrbenutzerbetrieb, Zugriffsschutz, Sicherung, Abfragesprache – nicht das Booten." },
  { id: "S7-11", modul: "S7", typ: "mc", niveau: 3, frage: "Die Spalte **telefon** enthält „0351 123 · 0171 456“. Gegen welche Normalform wird verstoßen?",
    optionen: ["1. NF", "2. NF", "3. NF", "gegen keine"], richtig: 0, abschnitt: "Redundanz, Anomalien und Normalisierung",
    erklaerung: "Mehrere Werte in einer Zelle sind nicht atomar → Verstoß gegen die **1. Normalform**." },

  // ---------------------------------------------------------------- S8
  { id: "S8-01", modul: "S8", typ: "mc", niveau: 1, frage: "Was zeigt ein **Anwendungsfalldiagramm**?",
    optionen: ["die Reihenfolge der Programmschritte", "welche Akteure welche Funktionen nutzen", "die Tabellen der Datenbank", "die Klassen mit ihren Methoden"], richtig: 1, abschnitt: "Anwendungsfalldiagramm",
    erklaerung: "Use-Case-Diagramme zeigen **wer was** darf – ohne Reihenfolge und ohne Technik." },
  { id: "S8-02", modul: "S8", typ: "mc", niveau: 2, frage: "„Bestellung aufgeben“ schließt **immer** „Anmelden“ ein. Welche Beziehung zeichnen Sie?",
    optionen: ["«extend» von Anmelden zu Bestellung aufgeben", "«include» von Bestellung aufgeben zu Anmelden", "Generalisierung", "einfache Assoziation"], richtig: 1, abschnitt: "Anwendungsfalldiagramm",
    erklaerung: "**«include»**: immer enthalten, Pfeil vom Basisfall zum eingebundenen Fall." },
  { id: "S8-03", modul: "S8", typ: "mc", niveau: 2, frage: "Im Aktivitätsdiagramm sollen „Rechnung erstellen“ und „Ware verpacken“ **gleichzeitig** ablaufen. Welches Element nutzen Sie?",
    optionen: ["Raute (Entscheidung)", "Gabelung und Vereinigung", "zwei Endknoten", "Aktivitätsbereich (Swimlane)"], richtig: 1, abschnitt: "Aktivitätsdiagramm",
    erklaerung: "Parallelität = **Balken** (Fork/Join). Die Raute bedeutet entweder – oder." },
  { id: "S8-04", modul: "S8", typ: "mc", niveau: 2, frage: "Welche Bedingungen an einer Entscheidung sind korrekt?",
    optionen: ["[alter < 18] und [alter > 18]", "[alter < 18] und [alter ≥ 18]", "[alter ≤ 18] und [alter ≥ 18]", "[jung] und [alt]"], richtig: 1, abschnitt: "Aktivitätsdiagramm",
    erklaerung: "Bedingungen müssen **vollständig und überschneidungsfrei** sein – sonst fehlt die 18 oder gehört zu beiden Zweigen." },
  { id: "S8-05", modul: "S8", typ: "mc", niveau: 1, frage: "Welches Zeichen steht im Klassendiagramm für **private**?",
    optionen: ["+", "−", "#", "~"], richtig: 1, abschnitt: "Klassendiagramm",
    erklaerung: "+ public, **− private**, # protected, ~ package." },
  { id: "S8-06", modul: "S8", typ: "mc", niveau: 2, frage: "Ein Raum besteht aus Wänden, die ohne den Raum nicht existieren. Welche Beziehung ist das?",
    optionen: ["Aggregation", "Komposition", "Vererbung", "Assoziation"], richtig: 1, abschnitt: "Klassendiagramm",
    erklaerung: "Teil stirbt mit dem Ganzen → **Komposition** (gefüllte Raute)." },
  { id: "S8-07", modul: "S8", typ: "mc", niveau: 2, frage: "Was bedeutet die Multiplizität `1..*` an einem Linienende?",
    optionen: ["keins oder eins", "genau eins", "mindestens eins", "beliebig viele, auch keins"], richtig: 2, abschnitt: "Klassendiagramm",
    erklaerung: "`1..*` = **mindestens eins**, nach oben offen." },
  { id: "S8-08", modul: "S8", typ: "mc", niveau: 2, frage: "Worin unterscheidet sich ein **Compiler** grundlegend von einem **Interpreter**?",
    optionen: ["Compiler übersetzt vorab, Interpreter zur Laufzeit", "Compiler übersetzt zur Laufzeit, Interpreter vorab", "Interpreter erzeugt eine ausführbare .exe-Datei", "Compiler eignet sich nur für Skriptsprachen"], richtig: 0, abschnitt: "Vom Quelltext zum Programm",
    erklaerung: "Im vereinfachten Vergleich: Vorabübersetzung gegenüber Ausführung durch einen Interpreter. In der Praxis existieren Bytecode und JIT-Kompilierung; nicht jede Implementierung passt ausschließlich in eine Kategorie." },
  { id: "S8-09", modul: "S8", typ: "mc", niveau: 1, frage: "Was ist eine **API**?",
    optionen: ["ein Editor mit integriertem Debugger", "eine festgelegte Programmierschnittstelle", "ein Werkzeug zur Versionsverwaltung", "eine Abfragesprache für Datenbanken"], richtig: 1, abschnitt: "Vom Quelltext zum Programm",
    erklaerung: "API = Application Programming Interface, z. B. eine Web-API, die Daten als JSON liefert." },
  { id: "S8-10", modul: "S8", typ: "mc", niveau: 1, frage: "Welche Entwurfsstufe zeigt nur ein grobes Layout mit Platzhaltern, ohne Farben?",
    optionen: ["Mockup", "Wireframe", "Prototyp", "Styleguide"], richtig: 1, abschnitt: "Bildschirmmasken entwerfen",
    erklaerung: "**Wireframe** = Gerüst, Mockup = gestaltet, Prototyp = klickbar." },
  { id: "S8-11", modul: "S8", typ: "mc", niveau: 2, frage: "Warum werden Attribute einer Klasse meist **private** deklariert?",
    optionen: ["damit das Programm schneller läuft", "Kapselung: Zugriff nur über Methoden", "weil public-Attribute nicht erlaubt sind", "damit Unterklassen sie nicht erben"], richtig: 1, abschnitt: "Klassendiagramm",
    erklaerung: "**Kapselung** schützt die Daten – ungültige Werte werden von Setter-Methoden abgewiesen." },
  // Ergänzungen S3 und S7 nach Streichung von PAP/Struktogramm und SQL aus dem AP1-Katalog
  { id: "S3-23", modul: "S3", typ: "mc", niveau: 1, abschnitt: "UML-Aktivitätsdiagramm", frage: "Was bedeutet ein **Gabelungsbalken** (Fork) im UML-Aktivitätsdiagramm?", optionen: ["Ab hier laufen mehrere Aktionen parallel", "Hier wird eine Bedingung geprüft", "Hier endet die gesamte Aktivität", "Hier wird eine Schleife wiederholt"], richtig: 0, erklaerung: "Ein zweiter Balken (Join) führt die parallelen Abläufe wieder zusammen; Bedingungen stehen an Rauten." },
  { id: "S3-24", modul: "S3", typ: "zahl", niveau: 2, abschnitt: "Bubble Sort", frage: "Wie viele **Vertauschungen** finden im **ersten Durchlauf** von Bubble Sort auf der Liste [5, 1, 4, 2] statt (aufsteigend sortieren)?", richtig: 3, toleranz: 0, erklaerung: "5 und 1 tauschen → [1, 5, 4, 2] · 5 und 4 tauschen → [1, 4, 5, 2] · 5 und 2 tauschen → [1, 4, 2, 5]: drei Vertauschungen." },
  { id: "S7-21", modul: "S7", typ: "mc", niveau: 1, abschnitt: "Das ER-Modell", frage: "Wie wird ein **Attribut** im ER-Modell in Chen-Notation dargestellt?", optionen: ["als Ellipse", "als Rechteck", "als Raute", "als Pfeil"], richtig: 0, erklaerung: "Rechteck = Entitätstyp, Raute = Beziehungstyp; Schlüsselattribute werden unterstrichen." },
  { id: "S7-22", modul: "S7", typ: "mc", niveau: 1, abschnitt: "Das ER-Modell", frage: "Woran erkennen Sie im ER-Modell ein **Schlüsselattribut**?", optionen: ["Der Attributname ist unterstrichen", "Es steht in einer Raute", "Es ist kursiv gesetzt", "Es steht außerhalb des Modells"], richtig: 0, erklaerung: "Im Tabellenmodell wird der Primärschlüssel ebenfalls unterstrichen." },
  { id: "S7-23", modul: "S7", typ: "mc", niveau: 2, abschnitt: "Vom ER-Modell zu Tabellen", frage: "Welchen Primärschlüssel erhält die Zwischentabelle `Position(AuftragNr, ArtNr, Menge)` einer n:m-Beziehung typischerweise?", optionen: ["die Kombination aus AuftragNr und ArtNr", "nur die Spalte Menge", "nur die Spalte AuftragNr", "gar keinen Primärschlüssel"], richtig: 0, erklaerung: "Zusammengesetzter Schlüssel aus beiden Fremdschlüsseln; alternativ eine eigene laufende Nummer." },
  { id: "S7-24", modul: "S7", typ: "mc", niveau: 3, abschnitt: "Redundanz, Anomalien und Normalisierung", frage: "In `Kunde(KundenNr, Name, PLZ, Ort)` hängt der Ort von der PLZ ab. Gegen welche Normalform wird verstoßen?", optionen: ["3. Normalform (transitive Abhängigkeit)", "1. Normalform", "2. Normalform", "gegen keine Normalform"], richtig: 0, erklaerung: "Ein Nicht-Schlüsselattribut (Ort) hängt von einem anderen Nicht-Schlüsselattribut (PLZ) ab; in der Praxis wird das oft bewusst toleriert." },
  { id: "S7-25", modul: "S7", typ: "mc", niveau: 2, abschnitt: "Redundanz, Anomalien und Normalisierung", frage: "In einer Tabelle „Auftrag mit Kundendaten“ wird der einzige Auftrag eines Kunden gelöscht – damit sind auch Name und Adresse des Kunden weg. Wie heißt das?", optionen: ["Löschanomalie", "Einfügeanomalie", "Änderungsanomalie", "referenzielle Integrität"], richtig: 0, erklaerung: "Abhilfe: Kunden in einer eigenen Tabelle speichern (Normalisierung)." },
]
