// Fragenpool Wirtschaft & Recht (W1–W5)
[
  // ---------------------------------------------------------------- W1
  { id: "W1-01", modul: "W1", typ: "mc", niveau: 1, frage: "Welche Reihenfolge gilt in der **Bezugskalkulation**?", optionen: ["erst Skonto, dann Rabatt", "erst Rabatt, dann Skonto, dann Bezugskosten", "erst Bezugskosten, dann Rabatt", "Rabatt und Skonto werden addiert und vom Listenpreis abgezogen"], richtig: 1,
    erklaerung: "LEP − Rabatt = ZEP − Skonto = BEP + Bezugskosten = Bezugspreis." },
  { id: "W1-02", modul: "W1", typ: "zahl", niveau: 1, frage: "Ein Hardware-Lieferant bietet Server-Komponenten zu folgenden Konditionen an: Listeneinkaufspreis 2 000 €, Lieferantenrabatt 10 %, Lieferantenskonto 2 %, Bezugskosten (Fracht/Versand) 30 €. Wie hoch ist der Bezugspreis (Einstandspreis) in Euro?", richtig: 1794, toleranz: 0.02, einheit: "€",
    erklaerung: "2 000 − 200 = 1 800 − 36 = 1 764 + 30 = **1 794 €**." },
  { id: "W1-03", modul: "W1", typ: "zahl", niveau: 1, frage: "Eine Rechnung lautet über **595 € brutto** (inklusive 19 % Umsatzsteuer). Wie hoch ist der reine Nettobetrag in Euro?", richtig: 500, toleranz: 0.01, einheit: "€",
    erklaerung: "595 / 1,19 = **500 €** (USt 95 €)." },
  { id: "W1-04", modul: "W1", typ: "mc", niveau: 1, frage: "Welche Aussage ist rechtlich **unverbindlich**?", optionen: ["Ein schriftliches Angebot an einen bestimmten Kunden", "Eine Anzeige im Onlineshop", "Eine Bestellung auf ein Angebot hin", "Eine Auftragsbestätigung"], richtig: 1,
    erklaerung: "Werbung/Webshop-Artikel sind **Anpreisungen** an die Allgemeinheit – eine Aufforderung, selbst ein Angebot abzugeben." },
  { id: "W1-05", modul: "W1", typ: "mc", niveau: 2, frage: "Was bewirkt die Klausel „**freibleibend**“ in einem Angebot?", optionen: ["Die Lieferung ist kostenlos", "Das Angebot ist ganz oder teilweise unverbindlich", "Der Käufer darf ohne Grund zurücktreten", "Es gibt keinen Skonto"], richtig: 1,
    erklaerung: "**Freizeichnungsklausel** – der Anbieter bindet sich nicht." },
  { id: "W1-06", modul: "W1", typ: "zahl", niveau: 2, frage: "Bezugspreis 800 €, Handlungskostenzuschlag 25 %, Gewinnzuschlag 10 %. Wie hoch ist der **Nettoverkaufspreis** (ohne Kundenrabatt/-skonto)?", richtig: 1100, toleranz: 0.02, einheit: "€",
    erklaerung: "800 + 200 = 1 000 (Selbstkosten) + 100 Gewinn = **1 100 €**." },
  { id: "W1-07", modul: "W1", typ: "mc", niveau: 2, frage: "Warum wird der **Kundenskonto** in der Verkaufskalkulation „im Hundert“ gerechnet?", optionen: ["Kunde zieht ihn vom Zielverkaufspreis ab", "Skonto beträgt immer genau 100 €", "Das Finanzamt schreibt es so vor", "Er wird vom Bezugspreis berechnet"], richtig: 0,
    erklaerung: "Der Barverkaufspreis entspricht z. B. 98 % des Zielverkaufspreises → ZVP = BVP / 0,98." },
  { id: "W1-08", modul: "W1", typ: "zahl", niveau: 2, frage: "Handlungskosten 120 000 €, Wareneinsatz 480 000 €. Wie hoch ist der **Handlungskostenzuschlagssatz** in %?", richtig: 25, toleranz: 0.01, einheit: "%",
    erklaerung: "120 000 / 480 000 × 100 = **25 %**." },
  { id: "W1-09", modul: "W1", typ: "mc", niveau: 2, frage: "Angebot A ist nur dank 3 % Skonto günstiger als B. Was muss man bei der Empfehlung erwähnen?", optionen: ["Dass der Rabatt verhandelbar ist", "Dass die Skontofrist eingehalten werden muss", "Dass Skonto nur Privatkunden zusteht", "Dass B dann automatisch teurer wird"], richtig: 1,
    erklaerung: "Skonto gibt es nur bei Zahlung innerhalb der Frist – sonst kann B günstiger sein." },
  { id: "W1-10", modul: "W1", typ: "multi", niveau: 2, frage: "Was gehört zu den **Pflichtangaben** einer Rechnung?", optionen: ["fortlaufende Rechnungsnummer", "Steuernummer oder USt-IdNr. des Leistenden", "Steuersatz und Steuerbetrag", "Geburtsdatum des Kunden", "Menge und Art der Leistung"], richtig: [0, 1, 2, 4],
    erklaerung: "Das Geburtsdatum gehört nicht auf eine Rechnung." },
  { id: "W1-11", modul: "W1", typ: "zahl", niveau: 3, frage: "Ein Monitor darf netto höchstens **345 €** kosten. HKZ 20 %, Gewinn 15 %. Wie hoch darf der **Bezugspreis** höchstens sein?", richtig: 250, toleranz: 0.02, einheit: "€",
    erklaerung: "Rückwärts: 345 / 1,15 = 300 (Selbstkosten) / 1,20 = **250 €**." },

  // ---------------------------------------------------------------- W2
  { id: "W2-01", modul: "W2", typ: "mc", niveau: 1, frage: "Wozu dient eine **Nutzwertanalyse**?", optionen: ["nur zum Preisvergleich", "qualitative Kriterien vergleichbar machen", "zur Berechnung der Umsatzsteuer", "zur Ermittlung der Abschreibung"], richtig: 1,
    erklaerung: "Sie macht nicht in Euro messbare Kriterien (Service, Bedienbarkeit) vergleichbar." },
  { id: "W2-02", modul: "W2", typ: "zahl", niveau: 2, frage: "In einer Nutzwertanalyse wird ein System anhand dreier gewichteter Kriterien bewertet: Anschaffungspreis (Gewichtung 50 %, Bewertung 8 Punkte), Servicequalität (Gewichtung 30 %, Bewertung 6 Punkte) und Energieeffizienz (Gewichtung 20 %, Bewertung 9 Punkte). Wie hoch ist der Gesamtnutzwert?", richtig: 7.6, toleranz: 0.01,
    erklaerung: "0,5 × 8 + 0,3 × 6 + 0,2 × 9 = 4 + 1,8 + 1,8 = **7,6**." },
  { id: "W2-03", modul: "W2", typ: "mc", niveau: 1, frage: "Welche Summe müssen die Gewichtungen einer NWA ergeben?", optionen: ["10", "100 % (bzw. 1,0)", "beliebig", "Anzahl der Kriterien"], richtig: 1, erklaerung: "Die Gewichte verteilen **100 %** auf die Kriterien." },
  { id: "W2-04", modul: "W2", typ: "mc", niveau: 2, frage: "Was ist ein Hauptkritikpunkt an der Nutzwertanalyse?", optionen: ["Sie ist zu teuer", "Gewichtung und Punktvergabe sind subjektiv", "Sie berücksichtigt nur Preise", "Sie funktioniert nur mit zwei Alternativen"], richtig: 1,
    erklaerung: "Subjektivität und Scheingenauigkeit – deshalb Sensitivitätsanalyse und Begründung." },
  { id: "W2-05", modul: "W2", typ: "mc", niveau: 2, frage: "Ein Drucker unterstützt die zwingend nötige Netzwerkanmeldung per Karte nicht. Wie behandelt man das in der NWA?", optionen: ["mit 0 Punkten bewerten", "als K.-o.-Kriterium ausschließen", "nicht berücksichtigen", "Gewichtung verdoppeln"], richtig: 1,
    erklaerung: "Muss-Anforderungen werden **vor** der Bewertung geprüft – sonst könnte ein Ausschlussgrund durch andere Kriterien ausgeglichen werden." },
  { id: "W2-06", modul: "W2", typ: "multi", niveau: 1, frage: "Welche Kriterien sind **qualitativ**?", optionen: ["Kundenservice", "Anschaffungspreis", "Bedienbarkeit", "Stromverbrauch in kWh", "Zuverlässigkeit des Lieferanten"], richtig: [0, 2, 4],
    erklaerung: "Preis und kWh sind direkt messbar (quantitativ)." },
  { id: "W2-07", modul: "W2", typ: "mc", niveau: 3, frage: "Zwei Alternativen erreichen 7,05 und 7,00 Punkte. Was ist die beste Schlussfolgerung?", optionen: ["Klar die erste Alternative nehmen", "Nicht eindeutig – Sensitivität prüfen", "Die Nutzwertanalyse war fehlerhaft", "Beide Alternativen beschaffen"], richtig: 1,
    erklaerung: "Kleine Unterschiede liegen im Bereich der Bewertungsunschärfe (Scheingenauigkeit)." },
  { id: "W2-08", modul: "W2", typ: "zahl", niveau: 2, frage: "Ein Kriterium ist mit **35 %** gewichtet, die Alternative erhält **6 Punkte**. Wie groß ist der Teilnutzen?", richtig: 2.1, toleranz: 0.001,
    erklaerung: "0,35 × 6 = **2,1**." },

  // ---------------------------------------------------------------- W3
  { id: "W3-01", modul: "W3", typ: "mc", niveau: 1, frage: "Wem gehört ein **geleastes** Notebook?", optionen: ["dem Leasingnehmer", "dem Leasinggeber", "dem Hersteller", "der Bank des Leasingnehmers"], richtig: 1,
    erklaerung: "Der **Leasinggeber** bleibt Eigentümer; der Leasingnehmer ist Besitzer." },
  { id: "W3-02", modul: "W3", typ: "multi", niveau: 2, frage: "Welche Vorteile hat **Leasing** gegenüber dem Kauf?", optionen: ["schont die Liquidität (kein hoher Anfangsbetrag)", "planbare monatliche Kosten", "meist geringere Gesamtkosten", "regelmäßige Erneuerung der Technik"], richtig: [0, 1, 3],
    erklaerung: "Über die Laufzeit ist Leasing meist **teurer** als der Kauf." },
  { id: "W3-03", modul: "W3", typ: "zahl", niveau: 2, frage: "Für eine Hardware-Ausstattung stehen zwei Optionen zur Wahl: Kauf für einmalig 3 000 € zuzüglich monatlicher Wartungskosten von 25 €, oder Miete für 100 € pro Monat inklusive Wartung. Nach wie vielen Monaten sind die kumulierten Kosten beider Optionen gleich hoch (Break-even-Point)?", richtig: 40, toleranz: 0,
    erklaerung: "3 000 + 25m = 100m → 3 000 = 75m → **m = 40**." },
  { id: "W3-04", modul: "W3", typ: "zahl", niveau: 1, frage: "Ein Server kostet 15 000 € und wird linear über 5 Jahre abgeschrieben. Jährliche AfA?", richtig: 3000, toleranz: 0.01, einheit: "€",
    erklaerung: "15 000 / 5 = **3 000 €** pro Jahr." },
  { id: "W3-05", modul: "W3", typ: "zahl", niveau: 2, frage: "Investition 12 000 €, jährliche Einsparung 4 000 €. **Amortisationszeit** in Jahren?", richtig: 3, toleranz: 0.001,
    erklaerung: "12 000 / 4 000 = **3 Jahre**." },
  { id: "W3-06", modul: "W3", typ: "mc", niveau: 2, frage: "Bei welchem Darlehen bleibt die **Rate** über die Laufzeit gleich?", optionen: ["Fälligkeitsdarlehen", "Abzahlungsdarlehen", "Annuitätendarlehen", "Kontokorrentkredit"], richtig: 2,
    erklaerung: "**Annuität** = konstante Rate; Zinsanteil sinkt, Tilgungsanteil steigt." },
  { id: "W3-07", modul: "W3", typ: "zahl", niveau: 2, frage: "Ein Unternehmen nimmt ein Abzahlungsdarlehen über 20 000 € mit linearer Tilgung über 4 Jahre auf. Der Zinssatz beträgt 6 % p. a. auf die Restschuld. Wie hoch ist die gesamte Jahresrate (Tilgung + Zinsen) im **2. Jahr** in Euro?", richtig: 5900, toleranz: 0.01, einheit: "€",
    erklaerung: "Tilgung 5 000 €; Restschuld Beginn Jahr 2: 15 000 € × 6 % = 900 € Zinsen → Rate **5 900 €**." },
  { id: "W3-08", modul: "W3", typ: "mc", niveau: 1, frage: "Bis zu welchem Nettobetrag darf ein geringwertiges Wirtschaftsgut sofort voll abgeschrieben werden?", optionen: ["250 €", "800 €", "1 000 €", "5 000 €"], richtig: 1,
    erklaerung: "GWG bis **800 € netto** (selbstständig nutzbar)." },
  { id: "W3-09", modul: "W3", typ: "mc", niveau: 2, frage: "Ein Unternehmen finanziert einen Server über einbehaltene Gewinne. Welche Finanzierungsart ist das?", optionen: ["Außen- und Fremdfinanzierung", "Innenfinanzierung (Selbstfinanzierung)", "Leasing", "Kreditfinanzierung"], richtig: 1,
    erklaerung: "Mittel aus dem Unternehmen selbst → **Innenfinanzierung**, hier Selbstfinanzierung aus Gewinnen." },
  { id: "W3-10", modul: "W3", typ: "mc", niveau: 1, frage: "Wann ist **Miete** gegenüber Kauf und Leasing besonders sinnvoll?", optionen: ["bei langer Nutzungsdauer", "bei kurzfristigem Bedarf (z. B. Messe)", "wenn viel Kapital vorhanden ist", "wenn Eigentum erworben werden soll"], richtig: 1,
    erklaerung: "Miete ist flexibel und kurzfristig kündbar – über lange Zeit aber teuer." },

  // ---------------------------------------------------------------- W4
  { id: "W4-01", modul: "W4", typ: "mc", niveau: 1, frage: "Wie kommt ein Kaufvertrag zustande?", optionen: ["durch Anfrage und Angebot", "durch Antrag und Annahme", "erst durch Bezahlung", "erst durch Lieferung"], richtig: 1,
    erklaerung: "**Antrag + Annahme**. Eine Anfrage ist unverbindlich." },
  { id: "W4-02", modul: "W4", typ: "mc", niveau: 1, frage: "Welches Recht hat der Käufer bei einem Sachmangel **vorrangig**?", optionen: ["Rücktritt", "Minderung", "Nacherfüllung", "Schadensersatz"], richtig: 2,
    erklaerung: "Zuerst **Nacherfüllung** (Nachbesserung oder Ersatzlieferung, der Käufer wählt), erst danach Rücktritt/Minderung." },
  { id: "W4-03", modul: "W4", typ: "mc", niveau: 2, frage: "Wer wählt bei der Nacherfüllung zwischen Nachbesserung und Ersatzlieferung?", optionen: ["der Verkäufer", "der Käufer", "der Hersteller", "ein Gericht"], richtig: 1,
    erklaerung: "Der **Käufer** (§ 439 BGB); der Verkäufer kann nur bei unverhältnismäßigen Kosten verweigern." },
  { id: "W4-04", modul: "W4", typ: "mc", niveau: 1, frage: "Welcher Vertrag liegt vor, wenn ein Dienstleister die **Einrichtung eines funktionierenden Netzwerks** schuldet?", optionen: ["Dienstvertrag", "Werkvertrag", "Mietvertrag", "Kaufvertrag"], richtig: 1,
    erklaerung: "Geschuldet ist ein **Erfolg** → Werkvertrag (mit Abnahme)." },
  { id: "W4-05", modul: "W4", typ: "mc", niveau: 2, frage: "Welchem Vertragstyp nach BGB ist ein **Service Level Agreement (SLA)** über laufende IT-Support-Leistungen rechtlich meist zuzuordnen?", optionen: ["Werkvertrag", "Dienstvertrag", "Kaufvertrag", "Leasingvertrag"], richtig: 1,
    erklaerung: "Geschuldet wird die **Tätigkeit** nach vereinbarten Zeiten, kein Erfolg → Dienstvertrag." },
  { id: "W4-06", modul: "W4", typ: "zahl", niveau: 1, frage: "Wie viele Jahre beträgt die gesetzliche **Gewährleistungsfrist** bei neuen Sachen?", richtig: 2, toleranz: 0,
    erklaerung: "**2 Jahre** ab Übergabe." },
  { id: "W4-07", modul: "W4", typ: "mc", niveau: 2, frage: "Welche Rügepflicht gilt gemäß § 377 HGB beim **zweiseitigen Handelskauf** für offene, bei ordnungsgemäßer Untersuchung erkennbare Mängel?", optionen: ["Rüge innerhalb von 2 Jahren", "Rüge unverzüglich", "Rüge innerhalb von 14 Tagen", "keine Rügepflicht"], richtig: 1,
    erklaerung: "§ 377 HGB: Ware **unverzüglich prüfen und rügen**." },
  { id: "W4-08", modul: "W4", typ: "mc", niveau: 2, frage: "Was unterscheidet **Garantie** von **Gewährleistung**?", optionen: ["Garantie gesetzlich, Gewährleistung freiwillig", "Gewährleistung gesetzlich, Garantie freiwillig", "Beide sind gesetzlich vorgeschrieben", "Garantie gilt nur für Software"], richtig: 1,
    erklaerung: "Die Garantie kommt **zusätzlich** und schränkt gesetzliche Rechte nicht ein." },
  { id: "W4-09", modul: "W4", typ: "mc", niveau: 2, frage: "Ein Kunde kauft im **Laden** einen funktionierenden Router und möchte ihn am nächsten Tag zurückgeben. Welcher Anspruch besteht?", optionen: ["14 Tage Widerrufsrecht", "Gewährleistungsanspruch", "kein Anspruch, nur Kulanz", "Rücktritt vom Vertrag"], richtig: 2,
    erklaerung: "Das **Widerrufsrecht** gilt nur für Fernabsatz/außerhalb von Geschäftsräumen; die Ware ist mangelfrei." },
  { id: "W4-10", modul: "W4", typ: "mc", niveau: 1, frage: "Ein 15-jähriger Auszubildender schließt ohne Zustimmung der Eltern einen Ratenkaufvertrag über ein Notebook für 900 € ab. Welcher rechtliche Status kommt dem Vertrag zu?", optionen: ["wirksam", "nichtig", "schwebend unwirksam", "anfechtbar"], richtig: 2,
    erklaerung: "Beschränkt geschäftsfähig (7–17); der Taschengeldparagraf greift bei Ratenkäufen nicht." },
  { id: "W4-11", modul: "W4", typ: "multi", niveau: 2, frage: "In welchen der folgenden Fälle liegt nach § 434 BGB ein gesetzlicher **Sachmangel** beim Kauf vor?", optionen: ["Notebook mit 8 statt vereinbarter 16 GB RAM", "Falsches Produkt geliefert (Falschlieferung)", "Verkäufer war gar nicht Eigentümer der Ware", "Zu geringe Menge geliefert (Minderlieferung)", "Fehlerhafte Montageanleitung oder Montage durch den Verkäufer"], richtig: [0, 1, 3, 4],
    erklaerung: "Fehlendes Eigentum des Verkäufers ist ein **Rechtsmangel**." },
  { id: "W4-12", modul: "W4", typ: "mc", niveau: 2, frage: "Ein Käufer nimmt ordnungsgemäß gelieferte Ware nicht an. Welche Störung liegt vor?", optionen: ["Lieferungsverzug", "Schlechtleistung", "Annahmeverzug", "Zahlungsverzug"], richtig: 2,
    erklaerung: "**Annahmeverzug** – Verschulden ist dafür nicht nötig." },
  { id: "W4-13", modul: "W4", typ: "zahl", niveau: 2, frage: "Wie viele **Monate** gilt beim Verbrauchsgüterkauf seit 2022 die Beweislastumkehr?", richtig: 12, toleranz: 0,
    erklaerung: "Zeigt sich ein Mangel in den ersten **12 Monaten**, wird vermutet, dass er schon bei Übergabe vorlag." },

  // ---------------------------------------------------------------- W5
  { id: "W5-01", modul: "W5", typ: "zahl", niveau: 1, frage: "Wie hoch ist das **Mindeststammkapital** einer GmbH in €?", richtig: 25000, toleranz: 0, einheit: "€",
    erklaerung: "GmbH: **25 000 €** · AG: 50 000 € Grundkapital · UG ab 1 €." },
  { id: "W5-02", modul: "W5", typ: "mc", niveau: 1, frage: "Wie haften die Gesellschafter einer **OHG**?", optionen: ["nur mit ihrer Einlage", "unbeschränkt, auch privat", "nur bis 25 000 € je Gesellschafter", "nur mit dem Gesellschaftsvermögen"], richtig: 1,
    erklaerung: "OHG-Gesellschafter haften persönlich und gesamtschuldnerisch." },
  { id: "W5-03", modul: "W5", typ: "mc", niveau: 2, frage: "In welcher Abteilung des Handelsregisters steht eine **GmbH**?", optionen: ["HRA", "HRB", "Vereinsregister", "Gewerberegister"], richtig: 1,
    erklaerung: "**HRB** = Kapitalgesellschaften (GmbH, UG, AG); HRA = Einzelkaufleute und Personengesellschaften." },
  { id: "W5-04", modul: "W5", typ: "mc", niveau: 2, frage: "Was bezeichnet der Rechtsbegriff **Firma** nach § 17 HGB?", optionen: ["das Betriebsgebäude", "der Name, unter dem ein Kaufmann seine Geschäfte betreibt", "das Unternehmen als Ganzes", "die Geschäftsführung"], richtig: 1,
    erklaerung: "Firma = **Name** des Kaufmanns (§ 17 HGB)." },
  { id: "W5-05", modul: "W5", typ: "mc", niveau: 2, frage: "Welches Leitungssystem hat Stellen mit **Beratungs-, aber ohne Weisungsbefugnis**?", optionen: ["Einliniensystem", "Mehrliniensystem", "Stabliniensystem", "Matrixorganisation"], richtig: 2,
    erklaerung: "**Stabsstellen** (z. B. Datenschutzbeauftragter) beraten die Leitung." },
  { id: "W5-06", modul: "W5", typ: "mc", niveau: 2, frage: "Was ist ein typischer Nachteil der **Matrixorganisation**?", optionen: ["zu lange Dienstwege", "Konflikte durch zwei Vorgesetzte", "keine Spezialisierung", "keine Flexibilität"], richtig: 1,
    erklaerung: "Doppelte Unterstellung erzeugt Abstimmungsaufwand und Kompetenzkonflikte." },
  { id: "W5-07", modul: "W5", typ: "mc", niveau: 1, frage: "Wie lange darf die **Probezeit** in einer Ausbildung dauern?", optionen: ["2 Wochen bis 1 Monat", "1 bis 4 Monate", "6 Monate", "1 Jahr"], richtig: 1,
    erklaerung: "BBiG: mindestens **1**, höchstens **4 Monate**." },
  { id: "W5-08", modul: "W5", typ: "multi", niveau: 2, frage: "Welche Pflichten hat der **Ausbildende**?", optionen: ["Ausbildungsmittel kostenlos bereitstellen", "Freistellung für die Berufsschule", "Ausbildungsnachweis führen", "Zeugnis ausstellen", "Vergütung zahlen"], richtig: [0, 1, 3, 4],
    erklaerung: "Den Ausbildungsnachweis (Berichtsheft) führen die **Auszubildenden**." },
  { id: "W5-09", modul: "W5", typ: "mc", niveau: 2, frage: "Energieeffiziente Server senken Stromkosten **und** CO₂-Ausstoß. Welche Zielbeziehung liegt vor?", optionen: ["Zielkonflikt", "Zielharmonie", "Zielneutralität", "Zielverfehlung"], richtig: 1,
    erklaerung: "Ein ökonomisches und ein ökologisches Ziel fördern sich gegenseitig → **Zielharmonie**." },
]
