// Fragen FISI – Ergänzungen aus dem Abgleich mit dem Prüfungskatalog und den Themen früherer Prüfungen
[
  { id: "FISI-3-23", modul: "FISI-3", typ: "mc", niveau: 2, abschnitt: "3. RAID-Level im Vergleich", frage: "Ein Datenbankserver soll **fehlertolerant** sein und beim **Schreiben** möglichst schnell bleiben. Die Kapazität ist zweitrangig. Welcher RAID-Level passt am besten?",
    optionen: ["RAID 10", "RAID 5", "RAID 6", "RAID 0"], richtig: 0,
    erklaerung: "RAID 10 spiegelt und verteilt (Striping) ohne Paritätsberechnung → schnelles Schreiben. RAID 5/6 müssen Parität berechnen (langsamer), RAID 0 hat keine Redundanz." },
  { id: "FISI-3-24", modul: "FISI-3", typ: "mc", niveau: 2, abschnitt: "3. RAID-Level im Vergleich", frage: "Aus **vier gleich großen Platten** soll ein **fehlertoleranter** Verbund mit möglichst großer Nettokapazität entstehen. Welcher Level liefert sie?",
    optionen: ["RAID 5 (Kapazität von 3 Platten)", "RAID 6 (Kapazität von 2 Platten)", "RAID 10 (Kapazität von 2 Platten)", "RAID 1 über alle vier Platten (Kapazität von 1 Platte)"], richtig: 0,
    erklaerung: "RAID 5 opfert eine Platte für Parität → n − 1 = 3. RAID 6 und RAID 10 ergeben hier nur 2 Platten, die Vierfach-Spiegelung nur 1." },
  { id: "FISI-4-21", modul: "FISI-4", typ: "mc", niveau: 2, abschnitt: "Magnetband (LTO)", frage: "Warum dauert die Wiederherstellung **einzelner Dateien** von einem LTO-Band länger als von einer Festplatte, selbst wenn LTFS genutzt wird?",
    optionen: ["Das Band wird sequenziell gelesen und muss erst an die richtige Stelle gespult werden", "Bänder können nur komplett gelesen werden", "LTFS speichert Dateien ausschließlich komprimiert in einer Archivdatei", "Bänder haben keine Dateisystem-Informationen"], richtig: 0,
    erklaerung: "LTFS macht den Bandinhalt wie ein Laufwerk sichtbar, ändert aber nichts am sequenziellen Zugriff. Stärke des Bandes: günstig, langlebig, offline (Air Gap)." },
  { id: "FISI-5-21", modul: "FISI-5", typ: "mc", niveau: 2, abschnitt: "Penetrationstest", frage: "Worin unterscheidet sich ein **Schwachstellenscan** (z. B. mit OpenVAS) von einem **Penetrationstest**?",
    optionen: ["Der Scan sucht automatisiert nach bekannten Schwachstellen, der Pentest nutzt Lücken gezielt aus, um den tatsächlichen Schaden zu zeigen", "Der Scan nutzt Lücken aus, der Pentest nur nicht", "Beide sind identisch, nur die Preise unterscheiden sich", "Der Scan prüft nur die Verkabelung, der Pentest nur Webseiten"], richtig: 0,
    erklaerung: "Der Scan liefert eine Liste möglicher Lücken (mit Fehlalarmen), der Pentest bewertet sie im Zusammenspiel. Beides nur mit schriftlichem Auftrag." },
  { id: "FISI-5-22", modul: "FISI-5", typ: "mc", niveau: 3, abschnitt: "2. Schadsoftware und Angriffe", frage: "Für eine neu entdeckte **Zero-Day-Lücke** gibt es noch keinen Patch. Welche Maßnahme begrenzt den Schaden am ehesten?",
    optionen: ["Netzsegmentierung, Least Privilege und Überwachung auffälligen Verhaltens", "Das System bis zur Veröffentlichung des Patches ausschalten und nie wieder starten", "Den Virenscanner täglich neu installieren", "Passwörter alle drei Tage ändern lassen"], richtig: 0,
    erklaerung: "Wo kein Patch existiert, hilft Schadensbegrenzung: weniger Rechte, getrennte Netze, Monitoring. Danach den Patch zeitnah einspielen." },
  { id: "FISI-7-22", modul: "FISI-7", typ: "mc", niveau: 2, abschnitt: "5. Befehle für Admins", frage: "Was bewirkt das folgende Bash-Skript?", code: "#!/bin/bash\nfor f in *.log; do\n    gzip \"$f\"\ndone",
    optionen: ["Es komprimiert jede .log-Datei im aktuellen Verzeichnis einzeln", "Es fasst alle .log-Dateien in einer einzigen Archivdatei zusammen", "Es löscht alle .log-Dateien im Verzeichnis", "Es zeigt den Inhalt aller .log-Dateien an"], richtig: 0,
    erklaerung: "Die Schleife läuft über alle Treffer von `*.log`, `gzip` ersetzt jede Datei durch eine `.gz`-Version. Die erste Zeile (**Shebang**) legt den Interpreter fest." },
  { id: "FISI-7-23", modul: "FISI-7", typ: "mc", niveau: 2, abschnitt: "5. Befehle für Admins", frage: "Was liefert dieser PowerShell-Befehl?", code: "Get-Service | Where-Object { $_.Status -eq \"Stopped\" }",
    optionen: ["Alle Windows-Dienste, die gerade gestoppt sind", "Alle laufenden Prozesse mit hoher CPU-Last", "Alle Dienste, die automatisch starten", "Eine Liste der installierten Programme"], richtig: 0,
    erklaerung: "`Get-Service` liefert die Dienste, die Pipeline `|` reicht sie an `Where-Object` weiter, das nach dem Status filtert (`$_` = aktuelles Objekt)." },
  { id: "FISI-7-24", modul: "FISI-7", typ: "mc", niveau: 2, abschnitt: "5. Befehle für Admins", frage: "Wann läuft der folgende Cron-Eintrag?", code: "30 2 * * 1 /usr/local/bin/backup.sh",
    optionen: ["Jeden Montag um 02:30 Uhr", "Jeden Tag um 02:30 Uhr", "Am 1. jedes Monats um 02:30 Uhr", "Jeden Montag alle 30 Minuten ab 2 Uhr"], richtig: 0,
    erklaerung: "Reihenfolge: Minute · Stunde · Tag des Monats · Monat · Wochentag. `1` im Wochentagsfeld = Montag. Unter Windows entspricht `schtasks`." },
  { id: "FISI-7-25", modul: "FISI-7", typ: "mc", niveau: 1, abschnitt: "5. Befehle für Admins", frage: "Welchen **Exit-Code** liefert ein Shell-Befehl bei **erfolgreicher** Ausführung?", optionen: ["0", "1", "−1", "255"], richtig: 0,
    erklaerung: "0 = Erfolg, Werte ungleich 0 = Fehler. Ein Skript prüft das Ergebnis des letzten Befehls mit `$?` (Bash) bzw. `$LASTEXITCODE` (PowerShell)." },
  { id: "FISI-7-26", modul: "FISI-7", typ: "mc", niveau: 2, abschnitt: "5. Befehle für Admins", frage: "Was ist der Unterschied zwischen `>` und `>>` bei der Umleitung der Ausgabe in eine Datei (z. B. `echo test > log.txt`)?",
    optionen: ["`>` überschreibt die Datei, `>>` hängt an das Ende an", "`>` hängt an, `>>` überschreibt", "`>` schreibt in die Datei, `>>` liest aus ihr", "Es gibt keinen Unterschied"], richtig: 0,
    erklaerung: "Für fortlaufende Protokolle in Skripten verwendet man `>>`, sonst geht der bisherige Inhalt verloren." },
  { id: "FISI-8-21", modul: "FISI-8", typ: "mc", niveau: 2, abschnitt: "4. Betrieb von Datenbanken", frage: "Daten aus mehreren Quellen (CSV-Exporte, XML-Schnittstellen, Sensorwerte) sollen **zunächst unverändert** zentral gesammelt und später ausgewertet werden. Welche Lösung passt?",
    optionen: ["Data Lake", "Reverse Proxy", "Hot-Spare-Platte", "VLAN mit Voice-Priorisierung"], richtig: 0,
    erklaerung: "Ein Data Lake speichert Rohdaten in verschiedenen Formaten (strukturiert und unstrukturiert); erst bei der Auswertung wird ein Schema angewendet." },
  { id: "FISI-11-21", modul: "FISI-11", typ: "mc", niveau: 2, abschnitt: "1. VLAN", frage: "Was leistet eine **Bridge** im Netzwerk?",
    optionen: ["Sie verbindet zwei Netzsegmente auf Schicht 2 und leitet Frames anhand von MAC-Adressen weiter", "Sie verbindet verschiedene IP-Netze und routet Pakete", "Sie verstärkt nur das elektrische Signal ohne Filterung", "Sie übersetzt private in öffentliche IP-Adressen"], richtig: 0,
    erklaerung: "Ein Switch ist im Grunde eine Bridge mit vielen Ports. Ein Router arbeitet auf Schicht 3, ein Repeater auf Schicht 1." },
  { id: "FISI-12-21", modul: "FISI-12", typ: "multi", niveau: 2, abschnitt: "2. Firewall-Arten", frage: "Welche **Kriterien** eignen sich für Filterregeln eines **Mailfilters** an der Firewall? (mehrere richtig)",
    optionen: ["Dateityp des Anhangs (z. B. .exe oder .js)", "Ergebnis der SPF- und DKIM-Prüfung des Absenders", "Spam-Bewertung und bekannte Phishing-Schlüsselwörter", "Schriftfarbe im Mailtext", "Uhrzeit, zu der die Mail gelesen wird"], richtig: [0, 1, 2],
    erklaerung: "Verdächtige Anhänge können zusätzlich in einer **Sandbox** ausgeführt werden. Beim Auswerten von Mails müssen Datenschutz und Fernmeldegeheimnis beachtet werden (Betriebsvereinbarung, Regelung zur Privatnutzung)." },
  { id: "FISI-13-21", modul: "FISI-13", typ: "mc", niveau: 3, abschnitt: "4. Weitere Dienste", frage: "Warum bereitet die Übertragung von **Fax** über eine VoIP-Anlage oft Probleme?",
    optionen: ["Fax-Signale reagieren empfindlich auf Laufzeitschwankungen und Kompression; das Protokoll T.38 überträgt Fax gesichert über IP", "VoIP unterstützt grundsätzlich keine Daten, sondern nur Sprache in Klartext", "Fax benötigt ein eigenes WLAN", "Fax-Geräte können nur an Glasfaseranschlüssen betrieben werden"], richtig: 0,
    erklaerung: "Bei VoIP wird Sprache komprimiert und in Paketen mit Jitter übertragen – das stört die Modem-Töne des Faxes. T.38 setzt Fax auf IP um." },
  { id: "FISI-16-22", modul: "FISI-16", typ: "mc", niveau: 3, abschnitt: "Monitoring mit SNMP", frage: "Welches Risiko besteht bei **SNMPv1/v2c** und wie lässt es sich vermeiden?",
    optionen: ["Der Community-String wird unverschlüsselt übertragen und kann mitgelesen werden; SNMPv3 bietet Authentifizierung und Verschlüsselung", "Die Geräte können nicht mehr gepollt werden; Lösung ist Telnet", "Die Abfragen sind zu langsam; Lösung sind mehr Switches", "Die Daten sind nach 24 Stunden gelöscht; Lösung ist ein Backup"], richtig: 0,
    erklaerung: "Weitere Maßnahmen: SNMP nur im Management-VLAN, Zugriff per ACL auf den Monitoring-Server beschränken, nur Leserechte." },
  { id: "FISI-16-23", modul: "FISI-16", typ: "mc", niveau: 2, abschnitt: "Monitoring mit SNMP", frage: "Was ist das Ziel von **Predictive Maintenance** (vorausschauender Wartung)?",
    optionen: ["Aus Messwerten wie Temperatur, Vibration oder S.M.A.R.T.-Daten absehen, wann ein Bauteil ausfällt, und es vorher tauschen", "Bauteile nach festem Kalender unabhängig vom Zustand tauschen", "Erst reparieren, wenn das Gerät ausgefallen ist", "Alle Geräte nachts automatisch neu starten"], richtig: 0,
    erklaerung: "Voraussetzung: Monitoring mit Schwellwerten und Auswertung. Reaktive Wartung = nach dem Ausfall, vorbeugende = nach Plan." }
]
