// Fragen FIAE – Ergänzungen aus dem Abgleich mit dem Prüfungskatalog und den Themen früherer Prüfungen
[
  { id: "FIAE-1-21", modul: "FIAE-1", typ: "mc", niveau: 2, abschnitt: "1. Vorgehensmodelle", frage: "Für ein großes, **risikoreiches** Softwareprojekt soll in mehreren Durchläufen jeweils zuerst das Risiko bewertet werden. Welches Vorgehensmodell ist dafür bekannt?",
    optionen: ["Spiralmodell", "Wasserfallmodell", "Kanban", "Reines V-Modell ohne Iteration"], richtig: 0,
    erklaerung: "Jeder Umlauf des Spiralmodells: Ziele festlegen → Risiken analysieren → entwickeln und testen → nächsten Umlauf planen." },
  { id: "FIAE-4-21", modul: "FIAE-4", typ: "mc", niveau: 2, abschnitt: "2. OOP-Prinzipien", frage: "Ein Team entwirft zuerst die Gesamtarchitektur und zerlegt sie dann in Module und Klassen. Wie heißt dieser Ansatz im Unterschied zum **Bottom-up-Entwurf**?",
    optionen: ["Top-down-Entwurf", "Test-driven Development", "Refactoring", "Pair Programming"], richtig: 0,
    erklaerung: "Top-down: vom Ganzen zum Detail. Bottom-up: vorhandene Bausteine (Bibliotheken, Klassen) werden zum System zusammengesetzt. Beide werden oft gemischt." },
  { id: "FIAE-5-24", modul: "FIAE-5", typ: "mc", niveau: 2, abschnitt: "Datentypen wählen", frage: "Welcher Datentyp eignet sich für den **Breitengrad** eines Standorts (z. B. 51,455643) mit hoher Genauigkeit?",
    optionen: ["DECIMAL(9,6)", "INT", "CHAR(1)", "BOOLEAN"], richtig: 0,
    erklaerung: "Koordinaten haben Nachkommastellen: DECIMAL (exakt) oder ein Geodatentyp des DBMS. Für Fotos oder Dokumente nimmt man BLOB, für Ja/Nein BOOLEAN." },
  { id: "FIAE-6-21", modul: "FIAE-6", typ: "mc", niveau: 1, abschnitt: "1. Vom Skizzieren zum Prototyp", frage: "Warum berücksichtigt man beim Entwurf von Bildschirmmasken die **Corporate Identity**?",
    optionen: ["Einheitliche Farben, Logos und Schriften sorgen für Wiedererkennung und einen professionellen Auftritt", "Sie ist für die Funktion der Software zwingend erforderlich", "Sie ersetzt die Barrierefreiheit", "Sie verhindert Eingabefehler der Nutzer"], richtig: 0,
    erklaerung: "CI und Barrierefreiheit müssen zusammenpassen: Auch das Firmendesign braucht ausreichend Kontrast." },
  { id: "FIAE-7-24", modul: "FIAE-7", typ: "mc", niveau: 2, abschnitt: "1. REST-API", frage: "Was unterscheidet **SOAP** von **REST**?",
    optionen: ["SOAP tauscht XML-Nachrichten mit festem Aufbau (Envelope) aus, REST nutzt HTTP-Methoden auf Ressourcen und meist JSON", "SOAP ist ein Datenbanktyp, REST ein Dateisystem", "SOAP funktioniert nur im LAN, REST nur über das Internet", "Beide sind identisch, nur die Namen unterscheiden sich"], richtig: 0,
    erklaerung: "SOAP: strenger Standard (WSDL, Typen, Erweiterungen), schwerer. REST: leichtgewichtig und zustandslos, daher in Web-APIs verbreitet." },
  { id: "FIAE-7-25", modul: "FIAE-7", typ: "mc", niveau: 1, abschnitt: "Entwicklungswerkzeuge", frage: "Welche Git-Aktion lädt Änderungen vom Remote-Repository herunter und führt sie in den aktuellen Branch ein?",
    optionen: ["pull", "push", "branch", "commit"], richtig: 0,
    erklaerung: "`push` lädt lokale Commits hoch, `commit` speichert lokal, `branch` legt einen Entwicklungszweig an, `merge` führt Zweige zusammen." },
  { id: "FIAE-7-26", modul: "FIAE-7", typ: "mc", niveau: 2, abschnitt: "Entwicklungswerkzeuge", frage: "Zwei Entwickler ändern in zwei Branches **dieselbe Zeile** einer Datei. Was passiert beim **Merge**?",
    optionen: ["Es entsteht ein Merge-Konflikt, der manuell gelöst werden muss", "Git übernimmt automatisch immer die neuere Version", "Beide Änderungen gehen verloren", "Git löscht den zweiten Branch"], richtig: 0,
    erklaerung: "Bei Änderungen an verschiedenen Stellen kann Git automatisch zusammenführen. Bei derselben Stelle muss ein Mensch entscheiden." },
  { id: "FIAE-9-21", modul: "FIAE-9", typ: "mc", niveau: 2, abschnitt: "3. Sortieren und Suchen", frage: "Die Liste `[5, 1, 4, 2]` wird mit **Selection Sort** aufsteigend sortiert. Wie sieht sie nach dem **zweiten** Durchlauf aus?",
    optionen: ["[1, 2, 4, 5]", "[1, 5, 4, 2]", "[1, 4, 2, 5]", "[2, 1, 4, 5]"], richtig: 0,
    erklaerung: "1. Durchlauf: kleinstes (1) nach vorn → [1, 5, 4, 2]. 2. Durchlauf: kleinstes im Rest (2) tauschen mit 5 → **[1, 2, 4, 5]**." },
  { id: "FIAE-9-22", modul: "FIAE-9", typ: "mc", niveau: 2, abschnitt: "3. Sortieren und Suchen", frage: "Welches Sortierverfahren fügt jedes neue Element **an der passenden Stelle in den bereits sortierten Teil** ein?",
    optionen: ["Insertion Sort", "Selection Sort", "Bubble Sort", "Binäre Suche"], richtig: 0,
    erklaerung: "Alle drei einfachen Verfahren haben O(n²). Insertion Sort ist bei fast sortierten Listen besonders schnell." },
  { id: "FIAE-10-21", modul: "FIAE-10", typ: "mc", niveau: 1, abschnitt: "2. Vererbung und Polymorphie im Code", frage: "Was beschreibt ein **Interface** in der objektorientierten Programmierung?",
    optionen: ["Eine Sammlung von Methodensignaturen, die implementierende Klassen bereitstellen müssen", "Eine Klasse, von der sich Objekte erzeugen lassen", "Eine Datenbanktabelle", "Eine grafische Benutzeroberfläche"], richtig: 0,
    erklaerung: "Ein Interface legt das „Was“ fest, die Klasse das „Wie“. Eine Klasse kann mehrere Interfaces implementieren, aber nur von einer Klasse erben." },
  { id: "FIAE-11-21", modul: "FIAE-11", typ: "mc", niveau: 2, abschnitt: "1. Teststufen und Testarten", frage: "Welches Verfahren ist ein **statisches** Testverfahren (ohne Ausführung des Programms)?",
    optionen: ["Code-Review", "Lasttest", "Unit-Test", "End-to-End-Test"], richtig: 0,
    erklaerung: "Statisch: Quelltext, Anforderungen oder Entwürfe werden geprüft (Review, Inspektion). Dynamisch: das Programm läuft, z. B. Unit-, Integrations-, Last- und E2E-Test." },
  { id: "FIAE-11-22", modul: "FIAE-11", typ: "mc", niveau: 2, abschnitt: "1. Teststufen und Testarten", frage: "Was unterscheidet **Verifikation** von **Validierung**?",
    optionen: ["Verifikation prüft, ob das Produkt die Spezifikation erfüllt; Validierung, ob es den tatsächlichen Bedarf des Kunden trifft", "Verifikation findet nur beim Kunden, Validierung nur beim Entwickler statt", "Verifikation prüft die Hardware, Validierung die Software", "Beide Begriffe bedeuten dasselbe"], richtig: 0,
    erklaerung: "Verifikation: „Bauen wir das Produkt richtig?“ Validierung: „Bauen wir das richtige Produkt?“" },
  { id: "FIAE-12-21", modul: "FIAE-12", typ: "mc", niveau: 2, abschnitt: "3. Struktur und Rechte (DDL, DCL)", frage: "Zwischen `Bestellung` und `Kunde` besteht ein Fremdschlüssel mit `ON DELETE CASCADE`. Was geschieht bei `DELETE FROM Kunde WHERE KundenID = 7;`?",
    optionen: ["Alle Bestellungen des Kunden 7 werden automatisch mit gelöscht", "Der Befehl wird abgelehnt, solange Bestellungen existieren", "Die Bestellungen behalten ihre KundenID 7 ohne zugehörigen Kunden", "Nur die erste Bestellung des Kunden wird gelöscht"], richtig: 0,
    erklaerung: "Option 2 entspricht `RESTRICT`. Die Löschweitergabe wahrt die referenzielle Integrität, löscht aber ggf. viele Datensätze. Das Gegenstück bei Änderungen heißt `ON UPDATE CASCADE` (Aktualisierungsweitergabe)." },
  { id: "FIAE-12-22", modul: "FIAE-12", typ: "mc", niveau: 2, abschnitt: "3. Struktur und Rechte (DDL, DCL)", frage: "Welcher **Constraint** stellt sicher, dass der Preis eines Artikels nie negativ ist?",
    optionen: ["CHECK (Preis >= 0)", "UNIQUE (Preis)", "PRIMARY KEY (Preis)", "FOREIGN KEY (Preis)"], richtig: 0,
    erklaerung: "CHECK prüft eine Bedingung. UNIQUE verbietet doppelte Werte, NOT NULL leere Werte, PRIMARY KEY identifiziert eine Zeile, FOREIGN KEY verweist auf eine andere Tabelle." }
]
